### ISSUE TITLE
collegare le pagine interne alle voci di menu

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#1]
Aggiornare l'html in modo che le pagine interne siano navigabili dalla home:
collegare Faq, Certificati e Notizie alle rispettive voci di menu

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Riapro la issue per via dei collegamenti mancanti sulle pagine Crediti, landing page (Scopri cos'è l'anagrafe nazionale), risultati di ricerca (cliccando il cerca)

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by fmilla74** [comment]
@steps88: su questo punto tutto ok?

**Comment by steps88** [comment]
si si, lo lasciavo pinnato in alto come reminder per le versioni future
