### ISSUE TITLE
[v1] DOMANDE FREQUENTI: Footer - logo errato

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#10]
Nel footer di questa pagina, il logo ANPR è errato. Allineare con Homepag
<img width="1440" alt="Schermata 2022-07-27 alle 10 06 59" src="https://user-images.githubusercontent.com/108679095/181195724-4d792e60-44d6-400d-87d9-5bf9bd2f3834.png">
e

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/91465481/185115367-f641474d-4541-431f-8ca6-5fe47955cfaf.png">
