### ISSUE TITLE
[WP] AREA TECNICA, FORMAZIONE: stile testi, spaziature

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#100]
**AREA TECNICA**

- [x] Il paragrafo Corsi di formazione ha font-weight e colore diverso dai paragrafi delle altre pagine (es. Certificati)
- [x] la CTA "Vedi tutti i corsi" ha due icone, eliminare quella di pagina interna; ha una dimensione diversa dalle CTA che usiamo nel sito intero; dovrebbe essere "Vai a tutti i corsi"

<img width="833" alt="image" src="https://user-images.githubusercontent.com/91465481/197167233-b3bd3370-9bd5-4118-b56c-e6680d5b423f.png">

**FORMAZIONE**

- [x] Dopo gli accordion con chips va previsto dello spazio per distanziare il testo
- [ ] #131
<img width="748" alt="image" src="https://user-images.githubusercontent.com/91465481/197168449-06913d93-978b-44d9-826e-8a21fbe6c841.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/91465481/197168633-a9aa72fd-f355-4e2a-aaf5-ed401676d89e.png">

**Comment by fmilla74** [comment]
puoi verificare questi tre punti sul sito di produzione. La chips su lato era così anche sul prototipo, vediamo se si può fare questa modifica in cosa alle altre.

**Comment by steps88** [comment]
Primi 3 punti verificati.
Attendiamo riscontro per la **posizione della chip** e l'uso **dell'icona** "play" per i video, che avevamo stabilito se ben riordo di mantenere come quadrato-con-freccia per segnalare l'apertura di una pagina esterna, confermi?

<img width="851" alt="image" src="https://user-images.githubusercontent.com/91465481/198043451-53c145cf-ad69-43c3-a8c7-0c9b7b9a8135.png">
<img width="793" alt="image" src="https://user-images.githubusercontent.com/91465481/198043692-38c625b8-d145-4e6e-9152-0a56241a4023.png">

**Comment by fmilla74** [comment]
stiamo mettendo su tutti link verso youtube l'icona con la freccia

**Comment by fmilla74** [comment]
Ora tutti i link verso youtube hanno l'icona con la freccia

**Comment by steps88** [comment]
Si riesce ad integrare l'ultimo punto sulla posizione della chip da mobile?

Verificato icona con la freccia
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/91465481/198694077-8825b9df-fcef-40d8-92dc-1bbd011ceb4f.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/91465481/198694207-f3993eb2-d98f-430d-be7e-f3021fbe374f.png">

**Comment by steps88** [comment]
Chiudo questa e ne creo un'altra per backlog
