### ISSUE TITLE
[WP] DOMANDE FREQUENTI: indice di pagina sticky

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#101]
È possibile uniformare il margine top al bottom quando l'indice di pagina diventa sticky? ora è piuttosto attaccato all'header 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/197175881-498fcabc-d1ca-4ebb-93b1-be063457e20f.png">

**Comment by fmilla74** [comment]
Uniformato

**Comment by steps88** [comment]
Verificato 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/91465481/200804018-bb13b11f-492c-4c0f-b363-d47b9bd03656.png">
