### ISSUE TITLE
[WP] CREDITI, INFORMATIVA PRIVACY: indice di pagina da mobile

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#102]
Navigando da mobile compare un indice dei contenuti che non dovrebbe essere presente. 
Lo stesso succede per la pagina **Informativa privacy**

Firefox e Chrome, simulatore mobile
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/197178600-44a0252b-a87a-46d5-a69c-6c460ca5ba81.png">

**Comment by steps88** [comment]
Informativa privacy 
<img width="373" alt="image" src="https://user-images.githubusercontent.com/91465481/197179517-15200a8b-4052-43ef-8243-c7c43ab66b3f.png">

**Comment by fmilla74** [comment]
anche su note legali. Lo correggiamo, grazie

**Comment by fmilla74** [comment]
corretto

**Comment by steps88** [comment]
Verificato 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/198694800-f517be28-94ba-4743-9ef5-31b5928e7cee.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/198694755-5f48dcd5-d0cd-487b-a7ae-2542ee78fd7f.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/198694659-e67dea8b-bd1a-4ff1-a0b3-6f9e071b7262.png">
