### ISSUE TITLE
[WP] INFORMATIVA PRIVACY, NOTE LEGALI: colori e formattazione testo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#103]
Verificare che quando saranno inseriti i contenuti definitivi anche i colori dei titoletti siano coerenti con quelli delle altre pagine di sito
Al momento su Informativa privacy è tutto in nero #262626 (Chi siamo, Commenti, Media, Cookie, ...ecc)
<img width="565" alt="image" src="https://user-images.githubusercontent.com/91465481/197180411-a717fb9a-df85-45a8-b497-9b480defc20c.png">

**Comment by fmilla74** [comment]
Puoi verificare sul sito di produzione con i contenuti defiitivi

**Comment by steps88** [comment]
Confermo 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/91465481/198042980-d4629734-f9e3-423f-b3ac-d33d6fd8b012.png">
