### ISSUE TITLE
[WP] NOTIZIE: il filtro Novità mostra anche gli avvisi, colore select non accessibile

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#104]
In produzione, selezionando nel filtro Novità la lista dei risultati mostra anche gli avvisi.
Inoltre, all'hover il colore del testo nella tendina della select del filtro non è accessibile (bianco su azzurro), nel prototipo html lo avevamo visto diverso (vedi screenshot)
-- Chrome

https://user-images.githubusercontent.com/91465481/197493843-d8fcd744-d787-464d-ab57-17bea2d5b93c.mp4

<img width="324" alt="image" src="https://user-images.githubusercontent.com/91465481/197493544-7076e04f-d8e9-433e-aa93-3a216ed9530f.png">

**Comment by fmilla74** [comment]
Corretto il problema sul filtro per Novità, era dovuto alla categorizzazione di alcune notizie. 
Per il secondo punto che browser stai utilizzando? Con Edge, Firefox e Chrome non riesco a riprodurlo.

**Comment by steps88** [comment]
Chrome, attraverso Citrix

**Comment by steps88** [comment]
da incognito non lo visualizzo più, ho cancellato la cache e ora nemmeno in navigazione normale.. 🤷

**Comment by fmilla74** [comment]
anche noi non l'abbiamo mai vista. forse un problema di cache

**Comment by steps88** [comment]
Risolto il bug sul filtro e l'accessibilità del dropdown
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/198042621-8d39c219-86af-4a21-8249-18099b94e049.png">
