### ISSUE TITLE
[cx] NUMERI: modalità di accesso all'area - bug da firefox nelle icone 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#105]
Le icone dei vari portali sono disallineate e di dimensioni tutte diverse, da Firefox versione desktop. Da Chrome non succede.
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/91465481/198062955-14dfc4d8-1a04-40ac-a068-87dcc60475bb.png">

**Comment by rfamiglini** [comment]
Bug fixato

**Comment by steps88** [comment]
verificato 
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/91465481/199788372-7348b527-ffac-49b3-8c9f-1bee2c4083cc.png">
<img width="367" alt="image" src="https://user-images.githubusercontent.com/91465481/199788446-096dd55c-c9b7-4679-bc73-fde9ab7dc456.png">
