### ISSUE TITLE
[cx] NUMERI - residenza: tipologie di cambio

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#106]
Da mobile la legenda del grafico non è più leggibile
<img width="373" alt="image" src="https://user-images.githubusercontent.com/91465481/198082834-eecfd789-a3ad-47c6-b374-5abb1d7f2457.png">

**Comment by rfamiglini** [comment]
Bug fixato

**Comment by steps88** [comment]
verificato <img width="362" alt="image" src="https://user-images.githubusercontent.com/91465481/199788153-05dcab12-795a-4e4a-bfbe-1f982c74c627.png">
