### ISSUE TITLE
[WP] CHECK TESTI - Missione

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#109]
eliminare “nuovo” da 

> [TITOLO FASCIA] 
> Il ruolo del Ministero dell’Interno  
> [TESTO FASCIA] 
> L’ANPR è un progetto del Ministero dell’Interno, la cui realizzazione è affidata a Sogei, partner tecnologico dell’amministrazione economico-finanziaria, che ha curato anche lo sviluppo del **~nuovo~** portale. Il Dipartimento per la trasformazione digitale della Presidenza del Consiglio dei ministri è titolare del coordinamento tecnico-operativo dell’iniziativa.  
> 
<img width="815" alt="image" src="https://user-images.githubusercontent.com/91465481/198564370-79e0584c-779a-411b-872a-4ac88363853e.png">

Modificare **14 diversi certificati digitali** in **14 diverse tipologie di certificati digitali**

[TITOLO FASCIA]
Online come presso il tuo comune 

> [TESTO FASCIA]
> I tuoi dati sono custoditi con la massima attenzione agli standard di sicurezza e sono sempre disponibili, ovunque ti trovi. I servizi digitali offerti dall’ANPR  ti mettono in contatto diretto con il tuo comune. I cittadini residenti nei 7.904 comuni e gli iscritti all’Anagrafe Italiani Residenti all’Estero (AIRE) possono verificare e chiedere online ai Comuni di competenza l’eventuale correzione dei propri dati anagrafici con il servizio di richiesta di rettifica dei dati. Inoltre, i cittadini possono scaricare **14 diversi certificati digitali** digitali in modo autonomo e gratuito, o inviare la dichiarazione di cambio di residenza senza passare allo sportello, sia per trasferimenti all’interno dello stesso comune, sia per cambi di residenza tra comuni diversi, sia per rimpatriare in Italia. 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/91465481/198569282-c93e8644-f4cd-4fd5-8ec1-818ac180ab62.png">

**Comment by fmilla74** [comment]
Modifiche effettuate, potete verificare

**Comment by steps88** [comment]
Verificate
<img width="744" alt="image" src="https://user-images.githubusercontent.com/91465481/199568223-0b5ccaaa-9261-4205-bd9c-a75f08a07e1d.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/91465481/199568594-a8fcdcd4-b9c7-46f7-9b37-38340ec226ef.png">
