### ISSUE TITLE
[v1] CERTIFICATI: Blocco titolo "certificati"

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#11]
Il testo sotto il titolo "certificati" non dovrebbe essere così largo, sul prototipo va a capo dopo "14 tipologie di..."
<img width="959" alt="Schermata 2022-07-27 alle 10 15 06" src="https://user-images.githubusercontent.com/108679095/181197545-0d5c8055-4588-4712-8e3f-12ca760c7225.png">
"

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato 
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/91465481/185115714-04ca2a9c-3adc-4719-8eea-e8f1cbfef4e6.png">
