### ISSUE TITLE
[WP] CHECK TESTI - Cos'è l'ANPR > Conosci l'ANPR

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#110]
Modifichiamo
- [x] la voce di menu **Cos'è l'ANPR** in **Conosci l'ANPR**
- [x] dentro al menu **Scopri cos'è l'ANPR** in **Conosci l'ANPR**
- [x] e nel titolo di pagina corrispondente: **Conosci l'ANPR**

<img width="230" alt="image" src="https://user-images.githubusercontent.com/91465481/198563019-2b680512-17b6-465d-a42a-a67f7e3d9626.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/91465481/198563364-16b88552-f61d-4920-89ff-1fe13bc980b9.png">

**Comment by fmilla74** [comment]
modifica del task 2 completata

**Comment by steps88** [comment]
Verificata 

<img width="219" alt="image" src="https://user-images.githubusercontent.com/91465481/199958686-eac7bc44-95ec-4fcf-89fb-2858ecc16fdd.png">
