### ISSUE TITLE
[WP] CHECK TESTI - Home

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#111]
- [x] FOOTER: correggere **Privacy policy** in **Informativa privacy** 
<img width="143" alt="image" src="https://user-images.githubusercontent.com/91465481/198564911-db29d45d-31da-480e-9cef-5c53d6254b64.png">

~FASCIA SERVIZI ANAGRAFICI: aggiungere il 5 box che prima era Domicilio digitale in:~ RILAVORATO

> [BOX 5- TITOLO]
> Notifiche
> Aggiorna i recapiti nel tuo profilo per ricevere le notifiche sulle richieste inviate al comune.
> [PULSANTE]
> Accedi

Il pulsante accedi rimanderà alla maschera di accesso di SPID, CIE, CNS

<img width="913" alt="Screenshot 2022-10-28 at 12 21 51" src="https://user-images.githubusercontent.com/91465481/198565141-b9d233cb-bcbc-49d6-a35d-ce2e7afe7dd0.png">

- [x] FASCIA NUMERI: box 2 certificati -> il sottotitolo è "**consultati** dall'avvio del servizio", non emessi

<img width="443" alt="image" src="https://user-images.githubusercontent.com/91465481/198564856-7c2b7091-2bf6-4b5e-847f-78f1d613e717.png">

**Comment by fmilla74** [comment]
Fascia numeri e footer modificati, potete verificarli sul sito. Relativamente al punto FASCIA SERVIZI ANAGRAFICI: per aggiungere il 5 box in home page (e immagino anche nella corrispondente sezione dei Servizi Anagrafici) andrebbe creata anche la pagina sotto l'area Servizi anagrafici così da ricondurre la navigazione di questa nuova card a quella delle altre già presenti.

**Comment by steps88** [comment]
Ottima osservazione. Ci abbiamo ragionato e non essendo un vero e proprio servizio alla pari degli altri, una pagina a sè sarebbe pressochè vuota, non ci sono molti contenuti, per cui facciamo retromarcia e NON inseriamolo come 5 box servizi.
Invece, possiamo aggiungere una fascia di contenuto **solo** all'interno della pagina **Servizi anagrafici** (non in home) con la stessa struttura di "Accedi in tuta sicurezza" e testi rivisti

<img width="844" alt="image" src="https://user-images.githubusercontent.com/91465481/199571056-714a60d8-532f-4518-825e-5c3c5bd579e5.png">

Questi i testi:
[TITOLO]
Ricevi le notifiche
[TESTO]
Mantieni aggiornati i tuoi recapiti all'interno del profilo personale, per ricevere le notifiche sullo stato di lavorazione delle richieste inviate al comune.
[PULSANTE] 
-to be defined-

Questa l'icona da usare 
![Notifiche email](https://user-images.githubusercontent.com/91465481/199573519-fba15212-cfb0-4966-9199-d603eb5bee48.svg)

**Comment by fmilla74** [comment]
@steps AGGIORNA IL PROFILO a cosa porta?

**Comment by fmilla74** [comment]
nuova fascia inserita, aspettiamo indicazioni per il link

**Comment by steps88** [comment]
alla pagina profiloo nell'area riservata. Sì, l'utente dovrà fare login

**Comment by fmilla74** [comment]
> alla pagina profilo nell'area riservata. Sì, l'utente dovrà fare login

L’utente dopo l'autenticazione sarà mandato alla home page dell’area riservata anche se mettiamo il link alla pagina per aggiornare il profilo. Possiamo anche non mettere la CTA

**Comment by cmigliardi** [comment]
Il cittadino sceglie solo dove riceverle – ma il sistema le invia sempre. Solo per chiarezza :

l’utente per ricevere le comunicazioni email (al momento mandiamo queste e loro le intendono come notifiche) deve inserire un’email nell’area del profilo e soprattutto validarla (attraverso un link che gli arriva tramite email).
Se non inserisce un’email validata in questa area, non riceverà mai comunicazioni.  
dal portale pubblico quando fai la login verrai sempre e comunque reindirizzato alla home page dell’area riservata.
Quindi non c’è alcun link che rimandi al profilo utente dal portale pubblico ANPR.

**Comment by steps88** [comment]
Con "profilo utente" intendo questa pagina, nell'area autenticata, Cecilia, dove l'utente va ad inserire l'email.
Se ci fosse il modo di inserire il link a questa specifica pagina siamo a cavallo.

![image](https://user-images.githubusercontent.com/91465481/200803219-3624824e-2516-44ca-8893-fa3c20814c75.png)

**Comment by cmigliardi** [comment]
ciao Stefania, 
non è possibile è un meccanismo che funziona così, l'utente deve tornare sulla scrivania.

**Comment by steps88** [comment]
Okay, se non è possibile mandare alla pagina specifica del profilo utente, andrà alla scrivania.

**Comment by fmilla74** [comment]
Quindi inseriamo la URL alla pagina del profilo con CTA "AGGIORNA IL PROFILO" anche se poi l'utente sarà rimandato sulla scrivania?   Ti avverto appena spostiamo la fascia sotto

**Comment by cmigliardi** [comment]
forse non ho capito,  ma vedendo l'immagine in apertura issue 

![image](https://user-images.githubusercontent.com/29276020/200839930-e6866cc2-de21-4b99-9045-8e6a467487a4.png)

non possiamo mettere un CTA fuori  prima dell'autenticazione.

**Comment by steps88** [comment]
Abbiamo deciso di aggiornare il testo della CTA in "Accedi e aggiorna il profilo"

**Comment by steps88** [comment]
Verificato 
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/91465481/201674801-4f4f897c-6cc0-41f4-8483-652ccbc0db04.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/201675031-d1da9be9-61a8-4b4d-b5b9-75db69d936ff.png">
