### ISSUE TITLE
[WP] CHECK TESTI - Crediti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#112]
Manca la frase iniziale:
"Per le immagini di copertina pubblicate in homepage:"

<img width="846" alt="image" src="https://user-images.githubusercontent.com/91465481/198567599-32cd762f-c2dc-408d-aeff-a15ff3675675.png">

**Comment by fmilla74** [comment]
frase iniziale inserita

**Comment by steps88** [comment]
Verificato <img width="1249" alt="image" src="https://user-images.githubusercontent.com/91465481/198693606-e16cbb9a-33e4-4a54-b2e0-650f47816ad9.png">
