### ISSUE TITLE
[WP] CHECK TESTI - Pagina Servizi anagrafici

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#113]
- [x] Modificare intro pagina mandando a capo la seconda frase dopo il punto, per non spezzare il bold:
“I servizi dell'ANPR **sono a tua disposizione** in qualunque momento e ovunque ti trovi. 
**Online e in autonomia**, hai sempre un filo diretto con il tuo comune, senza passare allo sportello.”

- [x] Modificare titolo fascia blu: 
“**Esplora i servizi disponibili**”

- [x] Card cambio di residenza in fascia blu: è l’unico contenuto che va su tre righe, le altre card restano su due. Provando a modificare il contenuto come segue, riusciamo a restare su due?
“Invia al comune la dichiarazione per cambiare residenza o rimpatriare in Italia.”

- [x] Fascia “Accedi in tutta sicurezza”: modificare descrizione come segue (su “SPID” e “CIE” ci sono due link esterni):
“L’accesso ai servizi dell’ANPR è possibile utilizzando l’**identità digitale**, scegliendo tra[ **SPID**](https://www.spid.gov.it/),[ **CIE**](https://www.cartaidentita.interno.gov.it/) o **CNS**.”

- [x] Card SPID: modificare la frase finale “scopri come ottenerla” in “scopri [come attivare SPID](https://www.spid.gov.it/cos-e-spid/come-attivare-spid/](https://www.spid.gov.it/cos-e-spid/come-attivare-spid/)” (link esterno) 

- [x] Card CIE:
“Con la nuova Carta d’Identità Elettronica” → eliminare “nuova”
“è rilasciata dal tuo Comune” → “comune” va minuscolo
La frase finale “Scopri [come accedere con CIE](https://www.cartaidentita.interno.gov.it/cittadini/entra-con-cie/)” deve mandare a link esterno: https://www.cartaidentita.interno.gov.it/cittadini/entra-con-cie/

- [x] Card CNS: modificare il testo come segue:
“La **Carta Nazionale dei Servizi (CNS)** è un documento personale che contiene informazioni di natura fiscale e sanitaria. Ha l'obiettivo di consentire la fruizione dei servizi previsti per la CIE agli utenti che non dispongono ancora del nuovo documento elettronico e integra le funzioni della Tessera Sanitaria (TS) del servizio sanitario nazionale. Anche la tessera sanitaria può essere abilitata come Carta Nazionale dei Servizi. Scopri come[  accedere con la CNS](https://www.sistemats.it/) ai servizi online.” (“come accedere con la CNS” manda a link esterno: https://sistemats1.sanita.finanze.it/portale/)

**Comment by fmilla74** [comment]
Modifiche effettuate, potete verificare. Per la card cambio di residenza in fascia blu abbiamo riportato il nuovo testo

**Comment by fmilla74** [comment]
Dobbiamo avviare la traduzione dei testi per i mini siti. Prevedete altre modifiche alle card dei servizi anagrafici o possiamo prendere la versione presente su TEAMS?

**Comment by fmilla74** [comment]
@steps88 possiamo avviare la traduzione anche delle card dei servizi? grazie

**Comment by gabripoggioli** [comment]
@fmilla74 Modifiche verificate, grazie. 
Confermo che non sono previsti ulteriori cambiamenti rispetto a quelli già indicati.

@steps88
