### ISSUE TITLE
[WP] CHECK TESTI - Pagina Certificati

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#114]
- [x] Modificare primo capoverso del paragrafo “Che cosa sono” come segue:
"Sono disponibili **14 tipologie di certificati**:
- anagrafico di nascita;
- anagrafico di matrimonio;    
- di cittadinanza;
- di esistenza in vita;
- di residenza;
- di residenza AIRE;
- di stato civile;
- di stato di famiglia;
- di residenza in convivenza;
- di stato di famiglia AIRE;
- di stato di famiglia con rapporti di parentela;
- di stato libero;
- anagrafico di unione civile;
- di contratto di convivenza."

- [x] Modificare paragrafo “Quando servono” come segue:
“I certificati sono validi e utilizzabili solo nei **rapporti tra privati**. Nei rapporti con gli  organi della Pubblica Amministrazione e i gestori di pubblici servizi, i certificati sono sempre sostituiti dalle autocertificazioni.”

- [x] Paragrafo “Come richiederli”
Portare in bold  “**tipologia**” e “**con bollo o in carta libera**”

**Comment by fmilla74** [comment]
Non andrebbe inserito anche il link per accedere ai servizi ? Questo in tutte pagine dei servizi anagrafici

**Comment by fmilla74** [comment]
Modifiche effettuate, potete verificare

**Comment by steps88** [comment]
Sì, va inserito il banner di accesso declinato per le varie pagine, come da [prototipo](https://xd.adobe.com/view/d9f96475-2b59-4a60-b3ad-aa3aa9a406b2-8caa/screen/31a386f5-cf3c-4ef8-9634-179be394cf7f)
<img width="962" alt="image" src="https://user-images.githubusercontent.com/91465481/199577312-69312bbc-67fa-4d2e-8c1e-e44698ab5845.png">


Verificate correzioni testi

<img width="414" alt="image" src="https://user-images.githubusercontent.com/91465481/199577022-7b11d281-a4d1-4ae1-a67b-cbec799d79d0.png">
<img width="750" alt="image" src="https://user-images.githubusercontent.com/91465481/199576974-2afbfb18-2d86-4d6f-8342-8e3fc94f71ad.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/91465481/199577094-72e6eaf5-361c-4e47-bb9f-22f9ea2a4c9a.png">

**Comment by fmilla74** [comment]
Trovi il banner nella pagina dei certificati. 
Ci servirebbero i testi per le altre pagine. 
Ce li potete mandare?
Grazie

**Comment by gabripoggioli** [comment]
Ciao @fmilla74 ,
di seguito la proposta di testi per il banner nelle altre pagine di Servizi anagrafici, fammi sapere se ci siamo in termini di limite di caratteri disponibile:

[VISURA E AUTOCERTIFICAZIONI]
Accedi ai servizi anagrafici per richiedere la visura dei tuoi dati o un'autocertificazione.

[CERTIFICATI]
Accedi ai servizi anagrafici per richiedere un certificato.

[RETTIFICA]
Accedi ai servizi anagrafici per inviare una richiesta di rettifica.

[CAMBIO DI RESIDENZA]
Accedi ai servizi anagrafici per inviare una dichiarazione di cambio di residenza.

cc @steps88

**Comment by steps88** [comment]
Per me va bene, occhio che per visura e cambio residenza ora andrebbe su due righe (e va bene) MA raddoppia anche l'altezza del pulsante accedi e si sforma l'icona.
Fate in modo che il pulsante rimanga alto una sola riga, allineato al centro.
<img width="918" alt="image" src="https://user-images.githubusercontent.com/91465481/200306041-f54c7036-f4cc-4e96-9100-4fbc8c5357a9.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/91465481/200306391-6cb57a93-7a9b-4f25-a4ff-6c8f63d1140b.png">

---> <img width="207" alt="image" src="https://user-images.githubusercontent.com/91465481/200306540-61f040a4-b368-496c-b752-c9545565bbee.png">

**Comment by fmilla74** [comment]
@steps88 @Clou-dia risolto nella versione desktop

**Comment by fmilla74** [comment]
risolto nella versione mobile, manca la risoluzione tablet 1080

**Comment by steps88** [comment]
Verificato a tutte le risoluzioni ✨
