### ISSUE TITLE
[WP] CHECK TESTI - Pagina Rettifica dati

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#115]
- [x] Paragrafo “Come richiederla”: nella frase “Accedi al servizio di richiesta di rettifica nella tua area riservata, e scrivi il dato corretto” ELIMINARE la congiunzione “e” → “Accedi al servizio di richiesta di rettifica nella tua area riservata, scrivi il dato corretto”

- [x] Modificare l’ultima frase del paragrafo “Come richiederla” come segue:
“**Potrai seguire** ogni passaggio di stato della lavorazione nella tua area riservata; inoltre, qualora tu l’abbia indicata nel tuo profilo utente, sarai informato anche **per email**.”

**Comment by fmilla74** [comment]
Modifiche effettuate, potete verificare

**Comment by steps88** [comment]
Verificati 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/91465481/199577853-4a47916a-483e-49dc-a76a-524f2e787f1d.png">
<img width="727" alt="image" src="https://user-images.githubusercontent.com/91465481/199578015-5138ac38-d79f-4a12-a2b4-38f0ac298165.png">
