### ISSUE TITLE
[WP] CHECK TESTI - Pagina cambio di residenza

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#116]
- [x] Testo introduttivo: aggiungere “per” prima di “la tua famiglia anagrafica” —> “Invia online al tuo comune la dichiarazione di cambio di residenza per te e per la tua famiglia anagrafica.”

- [x] Paragrafo “Come richiederlo”: modificare l’ultimo capoverso come segue:
“Prima di inviare la richiesta, ti consigliamo di **verificare attentamente i dati inseriti**: dopo l’invio, infatti, non sarà possibile effettuare ulteriori modifiche, poiché la richiesta sarà gestita direttamente dagli operatori d’anagrafe del comune di competenza. **Potrai seguire l’evoluzione della pratica** nella tua area riservata; inoltre, qualora tu l’abbia indicata nel tuo profilo utente, sarai informato anche **per email.**“

**Comment by fmilla74** [comment]
Modifiche effettuate, potete verificare

**Comment by steps88** [comment]
Verificate
<img width="676" alt="image" src="https://user-images.githubusercontent.com/91465481/199578239-ad329655-e5b5-4d5a-a8b5-83c79665506f.png">
<img width="744" alt="image" src="https://user-images.githubusercontent.com/91465481/199578343-747205b5-2727-489a-a132-3d77d95ef8cc.png">
