### ISSUE TITLE
[WP] CHECK TESTI - Domande frequenti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#117]
**CERTIFICATI:**
- 2 DOMANDA: Manca un _a capo_ dopo _...se è necessaria.._
<img width="703" alt="image" src="https://user-images.githubusercontent.com/91465481/198664685-9a52616e-61e8-4e91-a3f5-4fde78df76a3.png">

**RETTIFICA DATI**
- 3 DOMANDA: togliere grassetto dall’ultima frase in parentesi, usare l’italic e spostare il punto dopo la parentesi chiusa
<img width="669" alt="image" src="https://user-images.githubusercontent.com/91465481/198670024-3c221bc4-56f3-446c-b231-8f2b6dc3f7e9.png">

CAMBIO RESIDENZA
- 4 domanda: manca lo spazio tra seguire e lo stato; togliere grassetto dall’ultima frase in parentesi e spostare il punto dopo la parentesi chiusa
<img width="698" alt="image" src="https://user-images.githubusercontent.com/91465481/198673302-70c75926-72db-4c7d-924d-7b131fa676b7.png">

**Comment by fmilla74** [comment]
Modifiche completate, potete verificare

**Comment by steps88** [comment]
Aggiungo nella 7 domanda della sezione Generali, di aggiungere una E nella frase:
> Sono un cittadino iscritto all’AIRE **e** sono entrato nell’area riservata, ma [...]

<img width="564" alt="image" src="https://user-images.githubusercontent.com/91465481/199513522-eeaf5998-19a5-4619-b88f-68b8b990a074.png">

**Comment by fmilla74** [comment]
fatto

**Comment by fmilla74** [comment]
Dobbiamo avviare la traduzione dei testi per i mini siti. Prevedete altre modifiche alle FAQ o possiamo prendere la versione presente su TEAMS?

**Comment by fmilla74** [comment]
corretto

**Comment by steps88** [comment]
Verificato 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/91465481/199691757-e85c6146-4be4-4fa2-8f3a-e2a0cd196b30.png">
<img width="563" alt="image" src="https://user-images.githubusercontent.com/91465481/199691891-555274a4-059a-4cd8-a080-db0eb69a501b.png">
