### ISSUE TITLE
[WP] CHECK TESTI - Pagina Area tecnica

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#119]
- [x] Modificare i contenuti delle card della fascia “Esplora i contenuti disponibili” come segue (v. doc contenuti su Teams):

[CARD 1 - TITOLO]
**Accordi di fruizione**
[CARD 1 - TESTO] 
Per istituzioni ed enti che hanno necessità di accedere a dati anagrafici certificati. 
[PULSANTE]
 Scopri di più

[CARD 2 - TITOLO]
**Formazione**
[CARD 2 - TESTO] 
Tutte le informazioni sui corsi dedicati all’ANPR.
[PULSANTE] 
Scopri di più

[CARD 3 - TITOLO]
**Documentazione tecnica**
[CARD 3 - TESTO]
 La documentazione ufficiale per comunicare con l’ANPR in modalità _web services_. 
[PULSANTE] 
Scopri di più

[CARD 4 - TITOLO]
**Tabelle di decodifica**
[CARD 4 - TESTO] 
Le tabelle ufficiali di riferimento per la corretta comunicazione con l’ANPR.
[PULSANTE] 
Scopri di più

[CARD 5 - TITOLO]
**Archivio storico dei comuni**
[CARD 5 - TESTO]
Tutte le variazioni di denominazione registrate nel tempo dall’Istat per ogni comune.
[PULSANTE]
Scopri di più

- [x] Fascia “Corsi di formazione”:
Nel titolo, “formazione” va minuscolo 
Nel testo, modificare come segue:  
“I corsi formativi sull’ANPR sono **gratuiti**. Si rivolgono agli **ufficiali di anagrafe** dei comuni e ai rappresentanti delle **case _software_**.”

**Comment by fmilla74** [comment]
Per le card Accordi di fruizione, Documentazione tecnica e Formazione i testi sono quelli presenti nelle analoghe card in home page come da documento dei contenuti. Al momento non possiamo differenziarli

**Comment by gabripoggioli** [comment]
Le modifiche indicate per le card Accordi di fruizione, Documentazione tecnica e Formazione sono quelle richieste da Ministero dell'Interno. Riporterei le modifiche richieste in Area tecnica anche alle card in HP
cc @steps88 @Clou-dia

**Comment by fmilla74** [comment]
task completati

**Comment by steps88** [comment]
Aggiungo solo che nella pagina **Area tecnica** è rimasta la CTA VEDI TUTTI I CORSI che sarebbe meglio adeguare come le altre in VAI A TUTTI I CORSI

Verificato 
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/91465481/199960923-aae82d3f-7dc4-4cd7-ac63-4c4f7442318a.png">
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/91465481/199961057-a679f1dd-ee9f-4fa6-857c-9e2b9d3b67f0.png">

**Comment by fmilla74** [comment]
CTA aggiornata

**Comment by steps88** [comment]
Verificato 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/91465481/200286583-b6a855d9-8813-4187-9bb7-efe8cb9ad250.png">
