### ISSUE TITLE
[v1] CERTIFICATI: testo - mancano i bold

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#12]
Nel testo: "I certificati anagrafici sono atti ufficiali che ti consentono di dimostrare precisi requisiti relativi alla tua persona o al tuo stato. È possibile richiedere 14 tipologie di certificati:" mancano i bold in "dimostrare precisi requisiti" e "14 tipologie".
<img width="888" alt="Schermata 2022-07-27 alle 10 18 03" src="https://user-images.githubusercontent.com/108679095/181198028-6c35bbc8-3ca5-4423-834d-6c2d69a9f3ea.png">

**Comment by fcassandra** [comment]
Sono testi di esempio nel mockup, quando avremo i testi definitivi il redattore potrà mettere il bold direttamente su Wordpress dove previsto

**Comment by gabripoggioli** [comment]
I bold sono previsti dai testi che abbiamo inviato per approvazione al Ministero dell'Interno. Non abbiamo ancora ricevuto un riscontro dal Ministero. I testi che ritorneranno potrebbero essere ulteriormente rivisti e i bold modificati. Come indicato, inseriremo la versione definitiva direttamente nel CMS.
