### ISSUE TITLE
[WP] CHECK TESTI - Pagina Accordi di fruizione

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#120]
- [x] TESTO INTRODUTTIVO: "La piattaforma diretta con il Ministero dell’Interno" —> “Interno” va maiuscolo

- [x] Nel paragrafo "Che cosa sono gli Accordi di fruizione": "Gli Accordi di fruizione sono disponibili alle Pubbliche Amministrazioni" --> "pubbliche amministrazioni" va minuscolo (perché plurale). Va minuscolo anche nel primo bullet point

- [x] Nel paragrafo "Vuoi accreditarti?": "all’Indice delle Pubbliche Amministrazioni (IPA)e" anche qui "pubbliche amministrazioni" va minuscolo + aggiungere spazio tra "(IPA)" e la congiunzione "e" successiva

**Comment by fmilla74** [comment]
modifiche effettuate

**Comment by gabripoggioli** [comment]
Modifiche verificate, grazie
