### ISSUE TITLE
[WP] CHECK TESTI - Pagina Guida all'ANPR

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#121]
- [x] "la  gestione ed il monitoraggio delle dichiarazioni di cambio di residenza inviate dai cittadini tramite il portale dell’ANPR.": correggere il doppio spazio tra "la" e "gestione" + correggere "ed il monitoraggio" in "e il monitoraggio"

- [x] nella frase "l’allineamento delle basi dati eventualmente conservate localmente." che introduce i bullet point, correggere il punto fermo con i due punti ("localmente:")

- [x] nella frase [Consulta la documentazione tecnica – pdf (Apertura nuova finestra](https://www.anagrafenazionale.interno.it/wp-content/uploads/2021/03/Consulta-la-documentazione-tecnica-24-maggio-2018.pdf)), aggiornato al 24 maggio 2018" correggere "aggiornato" in "aggiornata"

- [x] nel bullet point "i lettori che sono stati recapitati direttamente al comune;" correggere il punto e virgola con il punto fermo (.)

- [x] correggere "QR-Code" in "QR code"

- [x] mettere ovunque "smart card" in corsivo ("_smart card_")

**Comment by fmilla74** [comment]
task completati. Sul primo task non vedo il doppio spazio e ho aggiunto la d che mancava.

**Comment by gabripoggioli** [comment]
@fmilla74 tutto verificato, solo la "d" nel primo punto andrebbe eliminata, non aggiunta: quindi non "ed il monitoraggio" ma "e il monitoraggio". Grazie

**Comment by fmilla74** [comment]
fatto
