### ISSUE TITLE
[WP] CHECK TESTI - Pagina Tabelle di decodifica

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#122]
Testo introduttivo: nella frase: "Le  tabelle di decodifica sono le tabelle ufficiali di riferimento per un corretta interoperabilità con ANPR .":
- eliminare doppio spazio tra "Le" e "tabelle di decodifica"
- correggere "un corretta" in "una corretta"
- aggiungere articolo prima di ANPR --> l'ANPR
- eliminare spazio tra "ANPR" e punto fermo a fine frase ("--> ANPR.")

**Comment by fmilla74** [comment]
Correzioni apportate. Non ho trovato il doppio spazio

**Comment by gabripoggioli** [comment]
Modifiche verificate, grazie.
