### ISSUE TITLE
[WP] CHECK TESTI - Homepage, fascia Area tecnica

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#123]
HP, fascia Area tecnica

- [x] nel titolo della fascia "Area Tecnica", "tecnica" va con l'iniziale minuscola

- [x] card 1, Accordi di fruizione: "Pubbliche Amministrazioni" deve avere le iniziali minuscole, non maiuscole

**Comment by fmilla74** [comment]
- la card Accordi di fruizione ora ha questo testo: Per istituzioni ed enti che hanno necessità di accedere a dati anagrafici certificati.

**Comment by fmilla74** [comment]
nel titolo della fascia "Area Tecnica", "tecnica" va con l'iniziale minuscola --> fatto

**Comment by gabripoggioli** [comment]
Tutte le modifiche verificate, grazie
