### ISSUE TITLE
[WP] CHECK TESTI - Pagina Formazione

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#124]
- [x] Nel bullet point "rappresentanti delle case software;", sostituire il punto e virgola con il punto fermo.
- [x] Paragrafo **Pillole formative**: 

- modificare la prima frase come segue: "A tua disposizione, nel canale YouTube del Dipartimento per la trasformazione digitale, 11 pillole informative inerenti le funzionalità più utilizzate dell’ANPR."
- Nella CTA "Vai sul canale Youtube", correggere maiusc/minusc in "YouTube"

- [x] Paragrafo **Corsi erogati nel 2021**: correggere maiuscole in minuscole sui mesi nell'elenco + refusi, come segue:

"Nel 2021 sono stati erogati i seguenti corsi: 
Corso Accordi di fruizione: 
Edizioni:

- 2 giugno 2021, erogato tramite Teams, rivolto agli Enti/PA - scarica le slide del corso;
- 8 luglio 2021, erogato tramite Teams, rivolto al Ministero - scarica le slide del corso;
- 12 luglio 2021, erogato tramite Teams, rivolto alle case software dei comuni - scarica le slide del corso. 

Corso Web application ANPR - 2021
Edizione 1: 

- Videoregistrazioni fruite dal 6 luglio 2021 al 19 luglio 2021;
- Webinar di approfondimento tematico tenuto il 20 luglio 2021.

Edizione 2: 

- Videoregistrazioni fruite dal 20 ottobre 2021 al 7 novembre 2021;
- Webinar di approfondimento tematico tenuto l’8 novembre 2021.

Edizione 3: 

- Videoregistrazioni fruite dal 18 novembre 2021 al 2 dicembre 2021;
- Webinar di approfondimento tematico tenuto il 3 dicembre 2021."

**Comment by fmilla74** [comment]
Se preferisci togliere gli elenchi, Corso Accordi di fruizione e Corso Web application ANPR - 2021 potrebbero essere degli H4.  Andrebbe però cambiata la frase "Nel 2021 sono stati erogati i seguenti corsi:". che ne pensi?  Le slide si trovano già al link su Vimeo per questo non sono state inserite

**Comment by fmilla74** [comment]
Ciao @gabripoggioli, volevo sapere se hai indicazioni su questo punto. Grazie

**Comment by gabripoggioli** [comment]
Ciao @fmilla74,
la struttura del paragrafo "Corsi erogati nel 2021" per me va bene come appare adesso: 

<img width="571" alt="Schermata 2022-11-09 alle 12 41 33" src="https://user-images.githubusercontent.com/101180195/200821349-a58a1503-b946-43ba-affa-62d3076ca1ce.png">

Nel mio commento avevo semplicemente riportato il testo con le correzioni già integrate per comodità.
Grazie.

**Comment by fmilla74** [comment]
ok, se la pagina va bene così e non ci sono altre indicazioni penso che questa richiesta si possa chiudere.
