### ISSUE TITLE
[WP] CHECK TESTI - Pagina Documentazione tecnica

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#125]
- [x] Modificare sottotitolo come segue (attenzione al corsivo): "La documentazione ufficiale per comunicare con l'ANPR in modalità _web services_."
- [x] Paragrafo Comuni: nella frase "L’accesso ai servizi dell’ ANPR avviene tramite l’area riservata di questo portale o tramite il sistema gestionale del comune integrato con i servizi dell’ ANPR." eliminare lo spazio tra apostrofo e ANPR
- [x] Negli elenchi, i bullet point non vanno in bold (al momento sembra che ne siano due interamente in bold)

**Comment by fmilla74** [comment]
completato il task 2

**Comment by fmilla74** [comment]
task 1 completato

**Comment by fmilla74** [comment]
task 3 completato

**Comment by gabripoggioli** [comment]
Tutti e tre i task verificati, grazie.
