### ISSUE TITLE
[cx] NUMERI: colore bottone filtro temporale

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#129]
verificare colore del bottone ok del filtro temporale

mi risulta di un colore non flat in certificati, visura e rettifica dati

<img width="107" alt="Schermata 2022-11-14 alle 11 45 38" src="https://user-images.githubusercontent.com/98462345/201641647-95fce190-cdef-4087-81ee-aac5bf47b496.png">

cc

**Comment by cmigliardi** [comment]
ok  ora vediamo

**Comment by steps88** [comment]
Credo che sia un problema di sovrapposizione dell'ombra delle card sottostanti che fanno sembrare il colore del pulsante un gradiente.

**Comment by Clou-dia** [comment]
risolto
