### ISSUE TITLE
[v1] CERTIFICATI: testo - mancano i bold 

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#13]
Nella frase: "Puoi richiedere i certificati singolarmente oppure in forma contestuale, cioè riunendo diverse tipologie di dati in un unico certificato." manca il bold in "singolarmente
<img width="976" alt="Schermata 2022-07-27 alle 10 20 43" src="https://user-images.githubusercontent.com/108679095/181198552-1cf6f54f-bea1-4fdc-852c-9c8f3e63c6e5.png">
"

**Comment by fcassandra** [comment]
Sono testi di esempio nel mockup, quando avremo i testi definitivi il redattore potrà mettere il bold direttamente su Wordpress dove previsto

**Comment by gabripoggioli** [comment]
I bold sono previsti dai testi che abbiamo inviato per approvazione al Ministero dell'Interno. Non abbiamo ancora ricevuto un riscontro dal Ministero. I testi che ritorneranno potrebbero essere ulteriormente rivisti e i bold modificati. Come indicato, inseriremo la versione definitiva direttamente nel CMS.
