### ISSUE TITLE
[cx] HOME: box in evidenza

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#130]
Testo box in evidenza

PORTALE ANPR
Una nuova esperienza a supporto dei cittadini
SCOPRI SU YOUTUBE (icona link esterno)

per il link al video vi chiedo di mettervi d'accordo con i vostri colleghi di comunicazione

**Comment by fmilla74** [comment]
@Clou-dia  @steps88 link al video inserito. Aggiunti anche il comunicato e le notizie mancanti.

**Comment by steps88** [comment]
Verificato!
