### ISSUE TITLE
CORSI DI FORMAZIONE - portare la chip di stato a capo sotto al titolo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#131]
da mobile, è meglio portare la chip di stato a capo sotto al titolo, in modo da lasciare il 100% dell'ingombro al titolo (che ora risulta invece su 4 righe)

![image](https://user-images.githubusercontent.com/91465481/201713604-41622d41-e237-4dcc-82d6-50ff25743484.png)

**Comment by fmilla74** [comment]
modifica rilasciata
