### ISSUE TITLE
NOTIZIE: indice di pagina non coerente

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#135]
L'indice di pagina della sezione notizie nella pagina foglia della singola notizia riporta il titolo corretto "Conosci l'ANPR" ma l'elenco dell'indice di pagina dell'altra sezione "Servizi Anagrafici"

qui due esempi:
<img width="1343" alt="Schermata 2022-12-12 alle 11 42 36" src="https://user-images.githubusercontent.com/98462345/207026885-ad140b7f-3823-46dc-878f-b107663890ac.png">
<img width="1383" alt="Schermata 2022-12-12 alle 11 32 27" src="https://user-images.githubusercontent.com/98462345/207026888-1b1f7ec1-330a-402e-9d8c-d788ec249dea.png">

nella pagina di elenco notizie è corretto

<img width="1361" alt="Schermata 2022-12-12 alle 11 32 15" src="https://user-images.githubusercontent.com/98462345/207027596-3082fb15-9e3f-43e6-b8fa-d7c1581a97e0.png">

**Comment by steps88** [comment]
Verificato 
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/91465481/207633974-08dee0cf-5344-4212-ba86-31f4266d82b3.png">
