### ISSUE TITLE
[SERVIZI ANAGRAFICI] Banner "Accedi ai servizi" + menu sticky con frecce a capo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#138]
A risoluzione tablet (1024) il pulsante di accesso dentro al banner va su due righe, dovrebbe rimanere su una 
Inoltre sarebbe meglio che la frecce dropdown nel menu non andasse a capo

<img width="745" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/a2be461b-ad02-4fe2-a19c-8f15eeabae56">

**Comment by fmilla74** [comment]
Il problema segnalato è stato risolto e potete verificarlo in ambiente di validazione. Sempre in validazione trovate la risoluzione della segnalazione sul logotipo a capo per alcune versioni di Safari.

**Comment by steps88** [comment]
Verificato, grazie 

https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/eb8f5e27-c7de-462a-9b0d-43aff363c278

**Comment by fmilla74** [comment]
rilasciato in produzione
