### ISSUE TITLE
[v1] CERTIFICATI: testo "come richiederli" - mancano i bold

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#14]
nella frase: 
"Dopo l’autenticazione, all’interno della tua area riservata puoi:

selezionare la persona per la quale richiedi il certificato (per te o per un componente della tua famiglia anagrafica);
selezionare il tipo di certificato da richiedere;
specificare il motivo della richiesta;
scegliere la modalità di ricezione (via email, download o entrambe);
ottenere il certificato digitale."

Mancano i bold in: "persona", "tipo", "motivo", "modalità di ricezione
<img width="863" alt="Schermata 2022-07-27 alle 10 22 21" src="https://user-images.githubusercontent.com/108679095/181199072-f7516a7d-ba6c-4456-837b-ac2672576027.png">
"

**Comment by fcassandra** [comment]
Sono testi di esempio nel mockup, quando avremo i testi definitivi il redattore potrà mettere il bold direttamente su Wordpress dove previsto

**Comment by gabripoggioli** [comment]
I bold sono previsti dai testi che abbiamo inviato per approvazione al Ministero dell'Interno. Non abbiamo ancora ricevuto un riscontro dal Ministero. I testi che ritorneranno potrebbero essere ulteriormente rivisti e i bold modificati. Come indicato, inseriremo la versione definitiva direttamente nel CMS.
