### ISSUE TITLE
[SDG] Form di instradamento servizi: ri-ordinare la data di nascita nel riepilogo dell'accesso

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#140]
[ID 4 e 5]

Cambiare l'ordine della data di nascita nello specchietto riepilogativo della form di instradamento e del riepilogo della dichiarazione di trasferimento da [da aaaa-mm-dd] a [dd-mm-aaaa]

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/143604868/b391857c-ddb0-402a-9c8d-2d7560ee606d)

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/143604868/b9d424de-7b78-4ee9-beb7-a13cb4863bd1)

https://scval.anpr.interno.it/serviziCittadino/iscrizione_online/home

Ricordarsi di inserire @assignee

**Comment by ncapozzi** [comment]
Buonasera,
il formato della data yyyy-mm-dd è stato preso dalla login eidas (Documento eIDAS SAML Attribute Profile pag. 9) e da qui mantenuto in tutte le form dell'iscrizione anche se nelle altre funzionalità dei servizi al cittadino è dd/mm/yyyy. Se dobbiamo uniformare il tutto applichiamo dd/mm/yyyy a tutte le form dell'iscrizione (inserimento dati anagrafici, generalità del richiedente e familiari, riepilogo etc.). Dateci conferma per favore
<saml:Attribute
FriendlyName="DateOfBirth"
Name=" http://eidas.europa.eu/attributes/naturalperson/DateOfBirth"
NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
<saml:AttributeValue xsi:type="eidas:DateOfBirthType">
1970-05-28
</saml:AttributeValue>
</saml:Attribute>

**Comment by ncapozzi** [comment]
Colgo l'occasione per fare di nuovo presente che chi compila la dichiarazione è un "dichiarante" non un richiedente come ci avevate chiesto di indicare (per la dichiarazione di cambio di residenza la sezione è denominata Generalità)

**Comment by Davidemaria-ricci** [comment]
Ciao Nicoletta,
si uniformiamo ovunque con il formato [dd/mm/yyyy]

**Comment by Davidemaria-ricci** [comment]
@ncapozzi perdona il rework; abbiamo approfondito il tema internamente e il formato data universale prevede yyyy-mm-dd, essendo un servizio rivolto a stranieri principalmente lasciamo così.

Grazie e scusa ancora
