### ISSUE TITLE
[SDG] Convalida mail: link convalida mail non valido

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#142]
[ID 9]

Il link arrivato per mail per verificarla non funziona

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/143604868/5bf277d0-46e7-47b2-b5aa-335e5452e46e)

[eventuale link](https://scval.anpr.interno.it/serviziCittadino/open/verificaEmail?key=115567_112254_13ef3660-e581-4e4a-951c-a4dcf7421f1c)

**Comment by gppbarone** [comment]
Buonasera Davide, il link per validare l'email l'hai provato da dentro Citrix? Io ho provato a validare il tuo link e ci sono riuscito senza problemi. Facci sapere.

**Comment by Davidemaria-ricci** [comment]
Confermo, funziona

Grazie
