### ISSUE TITLE
[SDG] Rivedere tutti i breadcrumb 

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#146]
ID test 11- 12

I breadcrumb a cominciare dalla pagina di snodo della scelta dei due tipi ditrasferimento e proseguendo per il processo sia di Nuova residenza che di Residenza in famiglia esistente non sono corretti.

vedi 

![scval anpr interno it_serviziCittadino_iscrizione_online_iscrizione-anagrafica_registrazione-residenza_129246](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/ff5e4d26-ddf9-4035-8ad3-95fc801dfb5e)
![scval anpr interno it_serviziCittadino_iscrizione_online_iscrizione-anagrafica_richiesta-iscrizione](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/b5f89b94-87c4-435e-9d06-6dfb5ef3d1d9)

**Comment by ncapozzi** [comment]
Buongiorno Claudia
non abbiamo capito cosa intendi esattamente. Se vuoi possiamo anche sentirci

**Comment by Clou-dia** [comment]
Il riferimento è ai breadcrumb che ci sono nell'immagine. Dopo aver scelto la tipologia di dichiarazione avevamo concordato che gli step di verifica dati e mail non dovevano più essere presenti. 

Il breadcrumb corretti sono stati comunicati sia nel **documento contenuti** che su [miro](https://miro.com/app/board/uXjVM-DOoWY=/?moveToWidget=3458764557967789861&cot=14), abbiamo anche un vostro OK

La cosa bizzarra è che in alcune sezioni è corretto, in altre no, per questo la issue generica sul rivedere i breadcrumb

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/8d51bfda-d602-4849-b122-aef23805cac0)

**Comment by Clou-dia** [comment]
qui per esempio è corretto 


![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/6cb359d6-d321-4a0d-9f03-db185e6d5880)

**Comment by ncapozzi** [comment]
Ciao Claudia
naturalmente se accedi ad una pratica già inserita da "Le tue dichiarazioni" quando arrivi ai dati del richiedente le breadcrumb sono diverse da quando inserisci la pratica la prima volta. In più "Le tue dichiarazioni" è linkabile perchè puoi tornare alla lista.

Nell'iscrizione l'unica voce che resta linkabile è HOME  quando si arriva "Nuova residenza o "Residenza in famiglia esistente"
Ti trovi in: Home / Trasferire la residenza in Italia / Inserisci i dati anagrafici / Email di registrazione / Scegli la dichiarazione di trasferimento/ Nuova residenza

Vuoi che togliamo solo Inserisci i dati anagrafici / Email di registrazione 
Ti trovi in: Home / Trasferire la residenza in Italia / Scegli la dichiarazione di trasferimento/ Nuova residenza
oppure anche le altre voci non più linkabili?
Ti trovi in: Home / Nuova residenza

**Comment by Clou-dia** [comment]
Si va bene la proposta
Home / Trasferire la residenza in Italia / Scegli la dichiarazione di trasferimento/ Nuova residenza
or
Home / Trasferire la residenza in Italia / Scegli la dichiarazione di trasferimento/ Residenza in famiglia esistente

**Comment by Clou-dia** [comment]
Verificati i breadcrumb del form di trasferimento.

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/6f4a4f7a-a0b6-403f-908c-4f702b9470a5)


![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/06a7acef-b8f7-4cea-b979-c4305f7c8171)


Non mi torna tuttavia che il **breadcrumb della pagina di snodo** delle due tipologie di residenza abbia gli step dati e email, li eliminerei anche da qui, vedi img

Breadcrumb della pagina seguente:

Ti trovi in: Home / Trasferire la residenza in Italia / Scegli la dichiarazione di trasferimento

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/41882263-739c-48d9-9e5e-3da3d91c42db)

**Comment by gppbarone** [comment]
Ciao Claudia, abbiamo rilasciato la modifica sulla breadcrumb, facci sapere se è tutto ok, grazie.

**Comment by Clou-dia** [comment]
Verificato, grazie

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/f0ecf91c-826d-4676-9ab4-24b10daca4e2)
