### ISSUE TITLE
[SDG] Inserimento dati / per tutti i drop-down richiamare vocabolari controllati SCHEMA 

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#148]
Overall

Richiamare vocabolari controllati Schema per tutti i menù a tendine per i quali sono presenti dei vocabolari controllati (quando sarà effettuata la traduzione verificare anche le versioni in inglese)

Abbiamo riscontrato alcune discrepanze, ad esempio, per i titoli di studio
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/143604868/c0bb1f16-4f2d-42f4-b570-135fd8ad3146)

Verificare vocabolari al seguente url: https://schema.gov.it/

**Comment by ncapozzi** [comment]
Buongiorno,
come noto i vocabolari di riferimento sia per i servizi riservati al cittadino sia per i Comuni sono da sempre quelli pubblicati al link https://www.anpr.interno.it/area-tecnica/tabelle-di-decodifica/ e condivisi con il Ministero dell'Interno che deve essere coinvolto per eventuali modifiche. Non si tratta quindi di un bug e la richiesta non è pertinente con i test che state facendo allo scopo di verificare i requisiti condivisi nella specifica MI-28-AN-13 Servizi ANPR per cittadini UE_Rev DTD_Sogei(6 settembre)

**Comment by Davidemaria-ricci** [comment]
Buongiorno,

effettueremo un passagio con il MINT sul tema in quanto la fonte dell'informazione è la medesima (ISTAT) con la differenza che schema è nato successivamente alla creazione delle tabelle di decodifica e assolve al ruolo di semantica unica per l'interoperabilità (anche le altre PA dovranno puntare ai quei vocabolari controllati e in ambito SDG bisogna cercare di favorire la piena interoperabilità).

Cambio la label in features così da affrontare il tema a 360 gradi sull'intera ANPR in un secondo momento, dopo i colloqui con il MINT.

Grazie

**Comment by Clou-dia** [comment]
in corso attività di allineamento ai vocabolari controllati, chiudo issue
