### ISSUE TITLE
[SDG] Processo di trasferimento / Tasti "Avanti" "Indietro"

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#149]
**Flusso** Tutti

Per migliorare la UX e l'interazione con il form vi chiediamo di aggiungere al form di trasferimento i tasti 

- [ ] "Indietro" come secondary button (outline) a sx
- [ ] "Avanti" come primary button (filled) a dx 

La modalità è alternativa all'interazione delle voci con il side menu

al click sul pulsante "Avanti" viene effettuato il salvataggio automatico, come da funzionalità attuale

**Comment by ncapozzi** [comment]
Questa richiesta era già stata fatta e rimandata a sviluppi futuri. Al momento non si farà visto che la compilazione dei pannelli non è sequenziale ma di libero accesso senza rispettare un ordine. (si potrà prevedere in futuro, quando lo stepper sarà implementato)

**Comment by Clou-dia** [comment]
Aggiungo la label **backlog** alla issue
L'interazione con questo form come detto più volte non è affatto intuitiva e poco usabile. 
La richiesta dello stepper è differente. Certo stepper più questi pulsanti potrebbero migliorare largamente l'esperienza utente. Quindi per noi questa è una feature must have.

**Comment by Clou-dia** [comment]
chiudo, già incluso nel progetto di progettazione area riservata
