### ISSUE TITLE
[v1] CERTIFICATI: footer - logo errato

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#15]
Logo ANPR nel footer errato, allinearlo come in homepag
![Schermata 2022-07-27 alle 10 25 00](https://user-images.githubusercontent.com/108679095/181199510-823dd854-b2c2-4651-b49f-d60c6bce6519.png)
e

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/91465481/185116615-5785b1e3-b44f-459f-b3ec-ec953ff688f4.png">
