### ISSUE TITLE
[SDG] Download modulo da firmare / rinominare file

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#150]
ID 25

Rinominare il pdf di riepilogo della dichiarazione che viene scaricato da "modulo_xxxx" a "modulo dichiarazione_xxxx"

**Comment by ncapozzi** [comment]
Ok procediamo

**Comment by Clou-dia** [comment]
verificato 

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/64a031a9-ce04-4f24-87a4-89e390686fde)
