### ISSUE TITLE
[SDG] Richiedente / dropdown Posizione professionale

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#151]
**Flusso** Nuova residenza
**Tab** Richiedente 

**Descrizione**: nel dropdown di **Posizione professionale** non dovrebbe esserci la voce _non applicabile (es. condizione non professionale_ in quanto l'utente può selezionare direttamente la _Condizione non professionale_ dal relativo dropdown. 
È infatti comunque errato bloccare il campo input se viene selezionata quella voce (vedi 2 screenshot)

![Image](https://user-images.githubusercontent.com/91465481/267610625-d19f8256-f2d3-4e72-baec-9e8ad981a616.png)

![Image](https://user-images.githubusercontent.com/91465481/267617200-471a6caa-911f-4d13-8623-8bc824d67bde.png)

**Comment by ncapozzi** [comment]
Buongiorno, ok procediamo come indicato

**Comment by steps88** [comment]
Verificato 
![Schermata 2023-10-03 alle 17 05 38](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/6a86cbac-7a2d-48bd-9714-2a4acde8c444)
