### ISSUE TITLE
[SDG] Famiglia / Aggiunta componente non visibile

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#152]
Il feedback di aggiunta componente e la tabella con l'item del componente aggiunto sono troppo distanti tra loro, considerato che il focus della pagina sale: o si sposta la notifica (vicino alla tabella) o la tabella dei componenti (in alto) 

![Image](https://user-images.githubusercontent.com/91465481/267621643-453ec7f9-1bb9-49e2-bc21-37b274951a27.png)

**Comment by ncapozzi** [comment]
Stiamo analizzando la richiesta. Vi facciamo sapere quando sarà rilasciata (Milestone da definire)
