### ISSUE TITLE
[SDG] Richiedente / Campo Cittadinanza aggiungere info

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#153]
il campo Cittadinanza ha bisogno di un bottone info: "sono accettati solo paesi dell'Unione Europea" come avviene per il campo sopra, provincia di ultima residenza

![Image](https://user-images.githubusercontent.com/91465481/267623807-d0df7530-edb5-49a3-9721-8ca19aed7d0f.png)

**Comment by gppbarone** [comment]
Buongiorno Claudia, il campo cittadinanza nel pannello Richiedente contiene solo le cittadinanze dei paesi dell'Unione Europea, quindi non darebbe nessuna informazione aggiuntiva.

**Comment by Clou-dia** [comment]
La richiesta è di aggiungere un tooltip per spiegare contestualmente al campo "Cittadinanza" perchè si trovano solo paesi europei, potrebbe non essere compreso. 

il tooltip potrebbe contenere il testo "Il richiedente deve essere cittadino di uno stato membro dell'Unione Europea"

**Comment by steps88** [comment]
Verificato 


![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/8201f746-5728-4e1b-983f-4694cdb0a4af)
