### ISSUE TITLE
[SDG] Immobile / Manca alert contestuale su campi obbligatori non compilati

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#155]
Per ciascuna tipologia di contratto,se non compilo i dati obbligatori non dà errore contestuale, ma solo al termine della compilazione della dichiarazione ovvero quando sono sul tab Riepilogo.
Non è particolarmente usabile, potrebbe dare errore al salvataggio dei dati della tab Immobile (ovvero quando mi appare la notifica di Salvataggio corretto: se ci sono dati obbligatori mancanti il salvataggio NON è corretto) 

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/7a0af8a1-3f28-46aa-9613-f1133a880fb1)

**Comment by ncapozzi** [comment]
Questa gestione è comune anche a Cambio di residenza e richieste di rettifica ed è presente in tutti i pannelli. Nasce dal fatto che la compilazione non è obbligatoriamente sequenziale ma lascia libertà all'utente di spostarsi da un pannello all'altro e di tornare sullo stesso anche più volte. Per questo motivo il controllo relativo alla presenza di dati obbligatori è stato posizionato sul Riepilogo.
Vi proponiamo di trasformarla in feature e di rivedere la gestione nell'ambito del rifacimento dell'area riservata.

**Comment by steps88** [comment]
Capiamo, ma visto che è comunque previsto un salvataggio dei dati ogni volta che si passa da una scheda all'altra, perchè non inserire il controllo dei campi obbligatori in quel momento? sarebbe un passo avanti in un'esperienza migliore

L'esperienza ideale poi si, la rivedremo con l'area riservata

**Comment by ncapozzi** [comment]
facciamo una verifica dell'effort. Vi facciamo sapere in che tempi si può fare
Comunque come tu stessa osservi sarebbe un miglioramento, e quindi per noi non è un BUG visto che comunque al Riepilogo viene controllata la presenza o meno dei campi obbligatori

**Comment by ncapozzi** [comment]
Ti confermiamo che la modifica avrebbe impatto su tutta l'applicazione servizi al cittadino per come è stata progettata e realizzata a livello architetturale e pertanto l'eventuale modifica è da rimandare al rifacimento dell'area riservata.

**Comment by Clou-dia** [comment]
issue risolta nelle attività di riprogettazione del area autenticata dell'ANPR
