### ISSUE TITLE
[SDG] Richiedente / Relazione di parentela

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#157]
Quando è l'intestatario della scheda a compilare la form, il campo **Relazione di parentela** precompilato con Intestatario scheda non dovrebbe essere modificabile

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/7755a9e5-fe80-463b-a82a-75c8f2931996)

**Comment by ncapozzi** [comment]
Non è un BUG ma un requisito consolidato e condiviso.

Chiudete voi le issue in questi casi?
