### ISSUE TITLE
[SDG] Famiglia / Modifica componente

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#159]
Nel momento in cui voglio modificare un Componente appena aggiunto, appare una modale che dice che con la modifica verrà eliminato e rimosso dalla tabella, e che dovrà essere reinserito.

In realtà il flusso per l'utente è che riapre il form del componente dove i campi sono precompilati, li modifica e salva le modifiche. 
Sarebbe perciò meglio:

- [ ] modificare il testo della modale secondo la reale esperienza - Taggo @gabripoggioli per la revisione del testo
- [ ] modificare il testo del bottone da Aggiungi componente a Salva

![Image](https://user-images.githubusercontent.com/91465481/267699897-3db259d4-bf27-4036-8cdb-467c1be72302.png)

**Comment by ncapozzi** [comment]
Buonasera
attendiamo il testo della modale modificato

**Comment by ncapozzi** [comment]
Lo pianifichiamo quando avremo il nuovo testo

**Comment by gabripoggioli** [comment]
Se non dobbiamo dire che con la modifica il componente verrà eliminato e rimosso dalla tabella e che dovrà essere reinserito, la modale non serve più, possiamo semplicemente non prevederla.

È sufficiente rinominare il pulsante “Aggiungi componente” in “Salva”.

@Davidemaria-ricci @ncapozzi @steps88

**Comment by Davidemaria-ricci** [comment]
verificato
