### ISSUE TITLE
[v1] NOTIZIE: select visualizza

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#16]
L'accordion "visualizza" aperto dovrebbe essere bianco con i testi blu. L'accordion dovrebbe aprirsi sotto il box, e l'aro dovrebbe cambiare verso.
<img width="631" alt="Schermata 2022-07-27 alle 10 31 52" src="https://user-images.githubusercontent.com/108679095/181200884-5f33df34-d3fb-42f1-8631-708f20b864b9.png">

**Comment by fcassandra** [comment]
E' una select e non un accordion. Il cambio di aro è un refuso sul mockup perchè sulla select non è previsto.
Non abbiamo chiaro l'altro punto perchè la leggibilità dei campi della select ci sembra molto buona:

![image](https://user-images.githubusercontent.com/83815138/181251863-6dfb3911-c072-486e-86d4-bb572c652ad1.png)

**Comment by FraCrea** [comment]
Grazie per la precisazione molto puntuale, è un refuso. 
Rispetto alla select aperta, dovrebbe essere visualizzata come da tuo screenshot.
Io però, su safari, la vedo la vedo nativa
<img width="631" alt="Schermata 2022-07-27 alle 10 31 52" src="https://user-images.githubusercontent.com/108679095/181255074-fe7fac63-1dd6-4b87-a8af-7837c2cc8a18.png">

**Comment by fcassandra** [comment]
ok, verifichiamo la visualizzazione su safari

**Comment by fmilla74** [comment]
abbiamo verificato e ti confermo che utilizziamo le select native, la presentazione è gestita dal browser.

**Comment by steps88** [comment]
Le due issue sono collegate --> #23

**Comment by steps88** [comment]
Per quanto riguarda la select nativa, c'è un motivo particolare per cui viene utilizzata quella nativa?

**Comment by fcassandra** [comment]
La scelta è dettata del fatto che è quasi uno standard e sicuramente una best practice di sviluppo html.
Così viene garantita di default l'accessibilità del componente, inoltre su dispositivi mobile c'è il vantaggio che vengono visualizzate le liste come da sistema operativo e l'interazione utente è la migliore possibile.
Mi sembra che anche sul kit bootstrap italia sia stata fatta la stessa scelta.

**Comment by steps88** [comment]
Confermo, verificato anche su BS Italia.
