### ISSUE TITLE
[SDG] Verifica accesso tramite ID ANPR

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#165]
ID 28 e 29

Effettuare test in ambiente di produzione con dati reali

**Comment by ncapozzi** [comment]
Non fattibile in produzione a meno di non avere una utenza eIDAS reale per un cittadino realmente presente in ANPR.

Vediamo se si può fare qualche cosa in pre-produzione quando ci abilitano la login eIDAS

**Comment by Clou-dia** [comment]
chiudo la issue per rilascio avvenuto
