### ISSUE TITLE
[SDG] Recupero certificato di nascita con CF

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#166]
ID da 39 a 42

Effettuare test in ambiente di produzione con dati reali

**Comment by ncapozzi** [comment]
Non fattibile in produzione a meno di non avere una utenza eIDAS reale per un cittadino realmente cancellato in ANPR.

**Comment by Clou-dia** [comment]
chiudo per rilascio avvenuto
