### ISSUE TITLE
[SDG] Check conformità dati componente per residenza in famiglia esistente

### ISSUE THREAD

**Issue by Davidemaria-ricci** [teamdigitale/anagrafenazionale.interno.it-site#168]
ID 16

Effettuare test in prod per verifica della conformità dei dati del componente della famiglia anagrafica presso la quale si trasferisce la propria residenza

**Comment by ncapozzi** [comment]
Buonasera Davide,
questo test lo puoi fare anche in dpval3
caso negativo: metti dei dati anagrafici assurdi sicuramente inesistenti in banca dati
caso positivo: ti metto in chat su teams i dati di un cittadino esistente in ANPR di validazione.
Così puoi verificare la differenza nel msg di risposta nei due casi. Ti ricordo che in caso di esito negativo l'errore comunque non è bloccante e consente al cittadino di proseguire come era stato deciso per il cambio di residenza

**Comment by Davidemaria-ricci** [comment]
Collaudo in ambiente di test verificato e andato a buon fine. 

Lascio issue con stessa label come reminder per test in ambiente di prod (proviamo a effettuare una chiamata di prova M2M su un cittadino reale per verificare che venga restituito l'esito positivo)
