### ISSUE TITLE
[v1] NOTIZIE: logo footer

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#17]
logo anpr footer non corretto, allinearlo come footer Homepage
<img width="1440" alt="Schermata 2022-07-27 alle 10 34 31" src="https://user-images.githubusercontent.com/108679095/181201418-d109ffde-9673-4d45-8e66-372fae0b3a25.png">

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/91465481/185126828-a72be94e-fd6e-42a3-b4ba-81175e8e87c0.png">
