### ISSUE TITLE
[SDG] Step email dopo cancellazione pratica

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#170]
Ho cancellato una pratica in bozza, per esempio perchè ho sbagliato a inserire "Nuova residenza" invece di "Residenza in famiglia esistente" e ho iniziato nuovamente il processo di trasferimento. 
Vedo la pagina informativa
Avevo già registrato i dati e la mail.

- [x] Bypassare la pagina di inserimento/validazione mail
- [x] Inserire testo allo snodo Nuova residenza/Residenza famiglia esistente dove indicare che per cambiare la scelta si deve eliminare la bozza della pratica (@gabripoggioli imposta il testo per piacere)

https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/c8fbed04-91a0-40bf-80c7-addf8b16bade

milestone da assegnare @ncapozzi @gppbarone

**Comment by gabripoggioli** [comment]
Di seguito il testo con l'integrazione richiesta:

---

[TITOLO PAGINA] 
**Scegli la dichiarazione di trasferimento** 

[SOTTOTITOLO PAGINA] 
Puoi scegliere di presentare una dichiarazione di **Nuova residenza** oppure una dichiarazione di trasferimento di **Residenza in famiglia esistente**. 

**Nota bene:** se hai già una dichiarazione in corso e desideri modificare la scelta che hai espresso tra Nuova residenza e Residenza in famiglia esistente, è necessario eliminare la bozza della precedente dichiarazione e iniziarne una nuova.

cc @Clou-dia @Davidemaria-ricci

**Comment by Clou-dia** [comment]
issue verificata
