### ISSUE TITLE
[NUMERI - ELETTORALI]  Correzioni tipografiche

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#173]
Elenco le correzioni sui testi della sezione **Dati elettorali**:

### Intro sezione
**Titolo:** Dati elettorali (elettorali in minuscolo)
**Sottotitolo**: Entro dicembre 2023 tutti i comuni sono tenuti a trasmettere all’Anagrafe nazionale i dati elettorali dei propri cittadini

### KPI
**Titolo:** Comuni che hanno trasmesso i dati elettorali
**Legenda grafico**: hanno trasmesso / non hanno trasmesso

### Mappa
**Titolo:** Stato di completamento della trasmissione dei dati elettorali
**Sottotitolo**: Percentuale di comuni che hanno trasmesso i dati elettorali, per regione. Seleziona un’area per vedere il dettaglio
**Legenda grafico**: Ha trasmesso / Non ha trasmesso

### Box di ricerca
**Titolo:** Il tuo comune ha trasmesso i dati elettorali?
**Sottotitolo**: Verifica se il tuo comune ha già trasmesso i dati elettorali all’ANPR

_In validazione_
![2610 Validazione](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/3c88a89f-492f-4c6a-bcc9-46a7074228ee)

_Desiderata_
![2610 DTD Pg_Numeri - liste elettorali v2](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b937fc62-bdc7-430f-9d45-8e89107f1fbf)

**Comment by anpr-opendata-team** [comment]
Ciao @steps88, per i contenuti nessun problema, prendiamo in carico.
Anche in questo caso notiamo delle differenze stilistiche, ad esempio il titolo in blu , l'aggiunta del colore arancione nel grafico a torta, l'utilizzo della card con bordo blu.

**Comment by steps88** [comment]
@anpr-opendata-team Le differenze stilistiche sono dovute al kit dataviz che usiamo per fare i mockup, non è necessario ora riportare queste modifiche di stile, ma attenetevi a quelle di contenuto. Grazie, scusate la confusione

**Comment by steps88** [comment]
mancano queste cose:

### Mappa
**Titolo:** lo stile del titolo deve essere quello usato nelle altre card, come quella appena sopra (grigione bold)
**Sottotitolo:** Percentuale **di** [non "dei"] comuni che hanno trasmesso i dati elettorali**,** [virgola] per regione. **Seleziona un’area per vedere il dettaglio** [<-- va aggiunta questa frase]
**Legenda**: è possibile mettere un box grigino (non bianco se no non si vede lo zero) sotto alla legenda? come abbiamo fatto per l'altra mappa, + allineare il titoletto a sx e tenere lo stile del testo come nell'altra mappa o portare in grassetto quello della 1a mappa 



![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/39c29c9e-bcb0-482d-8210-4505e48e661b)
