### ISSUE TITLE
[NUMERI - ELETTORALI] KPI Comuni che hanno trasmesso

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#174]
- [x] Migliorare l'ingombro della card, non è necessario che prenda tutta la larghezza della pagina. Così evitiamo di avere tutto quello spazio bianco tra testo e grafico
- [x] Inoltre vorremmo inserire il valore di aumento rispetto ai 7gg precedenti

_In validazione_
<img width="619" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/542c3c9a-d014-4a88-aaeb-ef7b2cc7f331">

_Desiderata_
<img width="1056" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/bebcff08-9010-464b-b80d-bb568d290924">

**Comment by anpr-opendata-team** [comment]
Ciao @steps88, possono essere lavorate entrambe le modifiche. Tuttavia, nel "Desiderata" notiamo una discordanza di stile rispetto a quello delle altre card, già in produzione, contenenti il grafico a torta.

**Comment by steps88** [comment]
@anpr-opendata-team  le differenze di stile non esplicitate non consideratele, attenetevi agli aspetti descritti nella issue

**Comment by steps88** [comment]
Non vedo miglioramento nell'ingombro della card Famiglie

Verificato il 2 punto.

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/6c570e6f-d8e2-4cea-8184-e4525f3871ff)

**Comment by steps88** [comment]
Verificato

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b954dc6a-5921-4dc9-8934-f5aa1bbd708f)
