### ISSUE TITLE
[NUMERI - ELETTORALI] Mappa delle adesioni > Stato di completamento 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#175]
Invece di mostrare i comuni subentrati vorremmo mostrare la **% di comuni subentrati per regione**:

- [x] Aggiungere il tooltip per esplorare il dato
- [x] diminuire l'altezza del grafico, sotto ai 450px
- [x] Aggiungere la legenda della scala di colori

_In validazione_
<img width="736" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/1c9a8987-ca26-4d93-9fb8-a3f4fde3889a">

_Desiderata_
<img width="579" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/fecc085e-2bbb-4ae8-83d6-6d8c97d9eb22">

**Comment by anpr-opendata-team** [comment]
Ciao @steps88, faremo le prove del caso per arrivare alla resa desiderata e torniamo da voi con delle tempistiche.
Il nuovo tab "info" cosa dovrebbe contenere? Facciamo presente che è la prima volta che viene richiesto l'inserimento in un grafico.

**Comment by steps88** [comment]
@anpr-opendata-team _Tab info_ non è necessario, è presente perchè nel kit dataviz che usiamo per fare i mockup

**Comment by steps88** [comment]
Correzioni di UI:

**Titolo:** lo stile del titolo deve essere quello usato nelle altre card, come quella appena sopra (grigione bold)

**Legenda:** i numeri si perdono sullo sfondo, così come il bianco a sx. È possibile mettere un box grigino (non bianco se no non si vede lo zero) sotto alla legenda? come abbiamo fatto per l'altra mappa, + allineare il titoletto a sx e tenere lo stile del testo come nell'altra mappa (o portare in grassetto quello della 1a mappa)

Verificata

https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/35742f1b-f530-40b3-8879-62ea0e8cf20b
