### ISSUE TITLE
[NUMERI - ELETTORALI] Box di ricerca comune

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#176]
Per le migliorie di testo vedi #173 
- [x] Modificare il bottone _Filtra_ in **Cerca**

Alcune considerazioni a livello di **layout**:

- [x] "N elettori" dovrebbe vedersi solo se ho effettuato la ricerca
- [ ] alert di successo: "Dati elettorali trasmessi ~il~ **in data**  18/10/2023"; eliminare il punto a fine frase; vedi screenshot per layout _N elettori_ 
- [x] alert di errore: eliminare il punto a fine frase e il numero di elettori
- [x] eliminare il tooltip (non è necessario)

_In validazione_ 

<img width="850" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/fab67514-bedd-4afb-a700-a1358b73c609">
<img width="835" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/bf1c5b4c-1a28-414e-a16e-e70ae0aea867">
<img width="824" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/e53642e6-0b16-4683-b172-6860b8b4efc4">

_Desiderata_
<img width="625" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/cbbb1e3c-c456-464c-bb64-947a55ed4678">
<img width="631" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/ae5dd7eb-9202-4963-b44b-59dfd03fab2e">
<img width="619" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/7e9dcada-c498-4166-b188-cedd630b01d2">

**Comment by anpr-opendata-team** [comment]
Buongiorno @steps88, 
abbiamo sviluppato la card in uniformità con quanto fatto per la ricerca "Persone residenti in Italia". 
Le modifiche richieste risulterebbero discordati con quanto già presente in produzione.
Riporto ad esempio la card di ricerca "Persone residenti in Italia"

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/115147861/40e31832-9568-40f3-b794-d69d3209660b)

Come procediamo?

**Comment by steps88** [comment]
@anpr-opendata-team Capisco, giustamente. Non avendo la parte di incremento per gli elettori al momento cercherei almeno di portare sulla stessa riga del numero  una la parola "elettori"

**Comment by steps88** [comment]
Manca la correzione testuale:

alert di successo: "Dati elettorali trasmessi il **in data** 18/10/2023"

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/682ad66c-0f14-434f-8d62-4bc3662ccab3)

**Comment by steps88** [comment]
<img width="684" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/fb922e08-77cd-4dbe-91dc-07e21e0baf55">
<img width="564" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/2af30a08-ca73-45b2-8f74-13a546ac1f04">
