### ISSUE TITLE
[GUIDA ALL'ANSC] Logo

### ISSUE THREAD

**Issue by costanzarosati** [teamdigitale/anagrafenazionale.interno.it-site#177]
troviamo un logo più adeguato rispetto a quello attuale?

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/126264837/0bb4ef75-350d-49bc-8dfa-c161db1daf78)

**Comment by steps88** [comment]
Userei quella generale di Area tecnica togliendo i checkbox @fmilla74 
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/5a3a386e-05af-4fc3-a9dd-f58c2cc5d9ee)

**Comment by fmilla74** [comment]
![ico-area_tecnica_scheck](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/84016913/08cfa3ee-7d78-47ae-a21d-91f8612fd912)
@steps88  così va bene?

**Comment by steps88** [comment]
Ottimo, grazie

**Comment by fmilla74** [comment]
la trovi in validazione

**Comment by steps88** [comment]
Va aggiornata anche nella pagina Scopri l'area tecnica, la fascia azzurra
<img width="777" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/3d9156ca-548b-4108-b627-921e3c85d595">

Verificato <img width="732" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/7bcec492-8c9d-411a-80e2-84ad586624ee">

**Comment by fmilla74** [comment]
hai ragione, l'ho aggiunta anche in area tecnica

**Comment by steps88** [comment]
<img width="828" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/33a13616-0e3e-4f66-9ef1-83d91ab2db98">
