### ISSUE TITLE
[GUIDA ALL'ANSC] Revisione testo in paragrafo "scegliere le modalità di adozione"

### ISSUE THREAD

**Issue by costanzarosati** [teamdigitale/anagrafenazionale.interno.it-site#178]
In guida all'ANSC --> paragrafo "scegliere le modalità di adozione" --> elenco puntato
è da rivedere la seguente frase 
"rilascio di estratti, certificati e copie;"
in
"rilascio di certificati e copie e gestione delle richieste relative al rilascio di estratti;"

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/126264837/a5785232-867c-48d1-afad-42250374999b)

**Comment by fmilla74** [comment]
Il testo è stato aggiornato in validazione. Potreste integrare la modifica anche nel file condiviso? grazie

**Comment by steps88** [comment]
Verificato


![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b6a35515-f4d5-44eb-89b5-950b466922f8)
