### ISSUE TITLE
[v1] CERTIFICATI: componenti da "accordion con chips" non dovrebbero esserci

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#18]
In questa pagina ci sono dei componenti non previsti, da "accordion con chips" in poi che sembrano far parte di una pagina di test.
<img width="920" alt="Schermata 2022-07-27 alle 11 06 22" src="https://user-images.githubusercontent.com/108679095/181209464-2dc81310-e234-49af-bc79-344b9361b475.png">
<img width="946" alt="Schermata 2022-07-27 alle 11 11 07" src="https://user-images.githubusercontent.com/108679095/181209565-0dc37b0e-9371-46a4-b306-e1a3f617ae4f.png">

**Comment by fcassandra** [comment]
Come condiviso in fase di pianificazione questa di proposito contiene degli elementi significativi di altri template che saranno utilizzati per lo sviluppo su wordpress. In questa pagina potete verificare tabelle, accordion per la formazione e gli altri elementi che ritrovi oltre ai certificati
