### ISSUE TITLE
[DOCUMENTAZIONE TECNICA] "Servizi dello stato civile"

### ISSUE THREAD

**Issue by costanzarosati** [teamdigitale/anagrafenazionale.interno.it-site#180]
In documentazione tecnica --> paragrafo "Servizi dello stato civile"
La frase 
"Per tutta la documentazione ufficiale relativa all’Archivio nazionale informatizzato dei registri dello stato civile (ANSC) consulta la pagina dedicata." 
deve essere integrata come segue
"Per tutta la documentazione ufficiale relativa all’Archivio nazionale informatizzato dei registri dello stato civile (ANSC) consulta la pagina dedicata Guida all'ANSC." 
"Guida all'ANSC" deve essere un link alla relativa pagina

**Comment by costanzarosati** [comment]
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/126264837/332af123-5df0-42bc-88d2-664afb2fafe3)

**Comment by fmilla74** [comment]
La pagina è stata collegata

**Comment by steps88** [comment]
c'è un errore di lettura dei caratteri 
<img width="769" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/75a58671-6668-4002-a0e0-1e168e0170d5">

**Comment by fmilla74** [comment]
@steps88 risolto

**Comment by steps88** [comment]
@fmilla74 ora possiamo eliminare le ancore nel sottotitolo e all'inizio del testo? 
grazie

Verificata correzione
<img width="790" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/f05fe7e2-7f09-451c-8e59-914f92811fd4">

**Comment by fmilla74** [comment]
@steps88 ancore eliminate. Aggiorno la pagina con la versione condivisa con Titoli H4 e elenchi?

**Comment by steps88** [comment]
sì, procedi pure, grazie mille

**Comment by fmilla74** [comment]
@steps88 nuova versione portata in validazione, ciao

**Comment by steps88** [comment]
Un'ultima correzione: 
Segnalazione e anomalie --> Segnalazion**i** al plurale

Verificato
![Schermata 2023-10-31 alle 15 39 52-fullpage](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/04f66b10-87c5-4a45-8e4c-061f3e25ddae)

**Comment by fmilla74** [comment]
corretto
