### ISSUE TITLE
[ANSC] Correzioni testuali

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#181]
In homepage, nella fascia _area tecnica_:
- [x] nel sottotitolo, correggere _anagrafici_ con **demografici**
<img width="484" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/3c0dfce2-8273-448b-b409-3e88c5a12994">

in pagina _Area tecnica_:
- [x] nel sottotitolo, correggere _anagrafici_ con **demografici**
- [x] nella fascia di dettaglio, c'è un typo sull'acronimo e 
- [x] si era concordato di posizionare la Guida nel mezzo, con la sfondo azzurro per metterla in risalto 

<img width="729" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/ad50005e-fe70-472d-b27b-e3aa90e82d12">
<img width="696" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/3b210f57-616c-4e7e-ad1f-a1408c12821b">

**Comment by fmilla74** [comment]
in validazione a meno dell'ultimo punto ancora in lavorazione

**Comment by fmilla74** [comment]
effettuato anche l'ultimo punto

**Comment by steps88** [comment]
Tutto verificato

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/d447da4b-3214-4007-ba19-280b4513aca8)

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/200b26da-7949-40a0-b4a9-57e1553960f0)

![Image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/fdf836fc-d47f-43b6-a468-78c2f3ea0f22)
