### ISSUE TITLE
[ANPR] Lista elementi da considerare durante la riprogettazione dell'area riservata 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#183]
**Generali**

- [ ] Aggiornare componente header in area riservata con nav rivista  
- [ ] Aggiornare componente footer  
- [ ] Progetto pagina di KO rispetto agli scenari + messaggi di errore  (rivedere il posizionamento dei messaggi all'utente che attualmente compaiono nella parte alta della schermata a favore di soluzioni che forniscono le informazioni necessarie in modo più contestuale)
- [ ] Migliorare componente back to top (floating button) 
- [ ] Introdurre modulo feedback in tutte le pagine di servizio (come da area pubblica)
- [ ] Informativa da acconsentire ad ogni singolo accesso: non si può memorizzare? O togliere o mettere flag “non visualizzare più” > passaggio con DTD legal 
**SOGEI**: se il cittadino si collega molto raramente, non sarebbe opportuno fargli rivedere l'informativa privacy anche le volte successive alla prima?
- [ ] Architettura informativa 
- [ ] Gerarchia dei testi e componenti (UI) 

**Scrivania**

- [ ] renderla responsive rispetto ai servizi offerti, più user centered 
- [ ] Integrare maggiormente area pubblica e riservata (FAQ, news, aggiornamenti) 
- [ ] Inserire notifiche/comunicazioni PER TE, all’utente, non sul sistema 

**Trasversali nei flussi**

- [ ] Uniformare le informazioni utili nella prima pagina del servizio in area riservata  
- [ ] Seguire i content type minimi di egov benchmark (scheda servizio “cosa ti serve sapere” “informazioni utili” 
- [ ] Processo visuale di degli step (come eIDAS) 
- [ ] Guida contestuale (pop up? Boh) 
- [ ] Cosa succede dopo (riepilogo, thank you page)  
- [ ] Pulsanti avanti e indietro con salvataggio automatico (“Salva e prosegui”) e controllo di obbligatorietà di campi o allegati contestuale alla pagina 
- [ ] Basta Notifiche in alto > contestuali (o modali?)
- [ ] No Aggiorna stato mail > aggiornamento automatico 
- [ ] Form con testo placeholder e suggerimenti di compilazione ( -!- occhio all’accessibilità, etichetta sempre visibile) (i placeholder verranno utilizzati per dare informazioni aggiuntive all'utente solo nei casi effettivamente necessarie a favore di soluzioni ugualmente efficaci dal punto di vista comunicativo ma più accessibili)
- [ ] Tabella annidata per allegati in area riservata (es. SDG) (per Rettifiche e Cambio di residenza occorre chiedere ai Comuni l'elenco degli allegati da prevedere, come è stato fatto per SDG)
- [ ] Area di drag&drop x allegati? Forse

**Comment by steps88** [comment]
@ncapozzi editate pure autonomamente la lista se ci sono elementi nel vostro riepilogo che non sono stati riportati, grazie

**Comment by cstortone** [comment]
Buongiorno, non è chiaro il requisito "Uniformare le informazioni utili nella prima pagina del servizio in area riservata"

**Comment by steps88** [comment]
Abbiamo notato che la prima pagina di ciascun servizio non è uniforme (a volte ci sono info operative, a volte no) per cui vorremmo uniformare la struttura dei contenuti della pagina di atterraggio del servizio, per tutti i servizi
