### ISSUE TITLE
[SITI IN LINGUA] Homepage

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#184]
### Homepage

- [x] l'area attiva che parte dal logo ANPR + scritta si estende su tutto l'header, sarebbe meglio ridurlo
- [x] aggiungere una voce di menu per la pagina di Domande frequenti, che è l'unica sottopagina che abbiamo ma ci si può accedere solo da un CTA che onestamente si perde un po'

https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b8f427d6-8058-4f72-bf70-d0b18d66e940

Attenzione a maiuscole e minuscole nel logotipo:
- ~FR: Unique. Pour Tous > Unique. Pour **t**ous (t minuscola)~
- ~EN: One Database. For Everyone > One **d**atabase. For **e**veryone (e ed e minuscole)~
- [x] EN: Registry Services > Registry **s**ervices (s minuscola)

<img width="322" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/1dee8ea1-94b2-47a1-a5ae-50c82b9c4df3">
<img width="320" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/63bf37f2-46a8-4013-b66a-306f9abac0e0">
<img width="447" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/bdfaaa0a-c05b-4f3d-870a-bdcb5931e864">

**Comment by fmilla74** [comment]
Seguono le immagini desktop e mobile con la nuova voce di Domande frequenti.
Se va bene la implementiamo nel sito

Desktop
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/84016913/17516ba2-88c0-4946-98f8-1c9a44710429)

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/84016913/2a8a32d9-2c12-421d-a9d9-e1850a0907ac)

Mobile

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/84016913/612db63e-7e12-4096-adcc-fa5da5d09f8e)

**Comment by steps88** [comment]
Per coerenza tra area pubblica e area riservata NON traduciamo "Unica. Per tutti.", ho aggiornato la issue rimuovendo i punti. Collegata a #186 

Ok per la voce di menu **Domande frequenti**

**Comment by fmilla74** [comment]
@steps88: La richiesta è di inserire "Unica. Per tutti" per tutte le lingue?

**Comment by steps88** [comment]
@fmilla74 esatto

**Comment by fmilla74** [comment]
in validazione trovi  "Unica. Per tutti" per tutte le lingue.
Inoltre completati task 2 e 3

**Comment by steps88** [comment]
Il punto 1 è realizzabile?

Verificato 2 3 e traduzione
<img width="1329" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/e304b263-931d-4ba0-a365-6bf2eb500a99">
<img width="1329" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/104c1fac-7cca-4041-9dcb-3a1883b8abf7">
<img width="1333" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/71c0e28e-d6c9-4e74-aba2-cc67cfdced60">
<img width="1329" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/bab958cc-494e-4f64-84af-f1f00421eaa2">
<img width="1331" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/9ee03c10-3015-4efa-8945-b42008b39017">
<img width="692" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/2ab1f2cd-babd-460b-8e91-66dc77439e48">

**Comment by fmilla74** [comment]
@steps88 risolto anche il punto 1

**Comment by steps88** [comment]
Verificata, grazie
