### ISSUE TITLE
[SITI IN LINGUA] Traduzione header footer mancante in AR

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#186]
Al momento per tutte le lingue sia header che footer in area riservata non sono completamente tradotti, manca la traduzione di "Servizi Anagrafici":

<img width="839" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/2cb60838-9a87-46d0-aefb-15df6523a7b8">
<img width="840" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/e707d77d-7d8c-477c-a694-d1bdd3bd388c">
<img width="837" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/998a34c8-8bda-4cd5-934a-82f6b376c15a">
<img width="841" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/06336258-7709-4441-b0d5-845eb5143bb3">
<img width="597" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/35c0f4ca-47cb-49b8-bddd-4787b5ec8f8e">
<img width="491" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/5a7a7c74-896f-4e25-b305-9fa75ff9e3ae">
<img width="576" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/7e5765e4-6acc-4f37-90fb-c680ce048059">
<img width="667" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/cbcc2784-9a38-42df-9477-bf24c0b4ba96">

**Comment by ncapozzi** [comment]
Buongiorno, anche "Anagrafe nazionale" deve essere tradotto?

**Comment by steps88** [comment]
No, Anagrafe nazionale non va tradotto

**Comment by steps88** [comment]
@ncapozzi @fmilla74  abbiamo rivalutato la traduzione dell'area riservata e siamo arrivati a questa conclusione:

IT
**Servizi anagrafici** 
Anagrafe Nazionale

EN
**Anagrafe Nazionale** 
National registry

DE
**Anagrafe Nazionale** 
Nationales Meldeamt

FR
**Anagrafe Nazionale** 
Registre nationale

SLO
**Anagrafe Nazionale** 
[traduzione di anagrafe nazionale in sloveno]

**Comment by ncapozzi** [comment]
Buongiorno, scusate ma non è chiaro
"Servizi anagrafici" non deve essere presente nelle 4 lingue?
Sembrerebbe che nelle 4 lingue va riportato solo Anagrafe nazionale sia in italiano che tradotto nella lingua scelta es.

EN
Anagrafe Nazionale
National registry

**Comment by steps88** [comment]
La logica è mantenere per tutte le lingue il titolo in italiano **Anagrafe Nazionale** e come sottotitolo la traduzione di _Anagrafe Nazionale_ nella lingua scelta.
L'unica eccezione è la versione italiana che ha come titolo _Servizi anagrafici_ e sottotitolo _Anagrafe Nazionale_

Torna?

**Comment by Clou-dia** [comment]
Questa issue vale anche per area pubblica @fmilla74
