### ISSUE TITLE
[ANPR] Feedback 31/10

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#187]
### Feedback a seguito della riunione del 31/10 su [ricerca in Miro](https://miro.com/app/board/uXjVNUKcgA0=/) e [prototipo  Adobe XD](https://xd.adobe.com/view/d22f2170-10fb-4150-ae98-9e89aaba3bf1-877c/) 

**Architettura informativa**: preferiamo la DUE, più scalabile e chiara, coerente con l’area pubblica, con alcune migliorie: 

1. Portare **Autocertificazioni** fuori da **I miei dati** 
2. Nella pagina **I miei dati** avere un componente sticky, che ti segue allo scroll, che porta ai diversi servizi disponibili (cosa ti serve?) 
3. Avvisi di manutenzione anche in area riservata
4. Modificare Dati anagrafici -> Dati demografici _(in ambito ANPR si parla sempre di anagrafe comunale e dati anagrafici relativamente al singolo cittadino - cognome, nome, ecc., - vedi anche DPCM 194/2014; l'eventuale modifica andrebbe verificata con i Comuni e il Ministero)_
5. **La mia scrivania**: abbiamo dovuto ragionare anche su questa pagina, dateci un occhio sulla Miro a dx (prendetelo come punto di partenza, non oro colato) 

**Footer:** più stringato ed essenziale, no loghi e logotipi, prendere a modello ANPR pubblico  

**componente laterale con Faq e servizi utili:** valutare come si comporta a risoluzioni inferiori? E con testi lunghi? È fixed? vedi punto 2 appena sopra

**Ricerca:** può essere una ricerca che ti chiede direttamente "Che cosa vuoi fare?" per instradarti al servizio, non per darti informazioni; cerca tra i servizi e le schede di servizio, non nei passaggi interni ai flussi  

**Flussi di servizio:** considerare come benchmark anche [modello comuni](https://www.figma.com/file/FHlE0r9lhfvDR0SgkDRmVi/Comuni---Modello-sito-e-servizi?type=design&node-id=79-200932&mode=design&t=NwUqmE9A9PQUJAjl-0) (pagina "Servizio" = scheda servizio, prototipi dei flussi di servizio; stato pratica; richiesta di assistenza) in generale anche per le schermate mobile  

#183

**Comment by cstortone** [comment]
Ciao, in merito a "Avvisi di manutenzione anche in area riservata" nell'incontro del 25 ottobre si era concordato di non riportare in area riservata gli avvisi giù presenti in area pubblica.

**Comment by steps88** [comment]
> Ciao, in merito a "Avvisi di manutenzione anche in area riservata" nell'incontro del 25 ottobre si era concordato di non riportare in area riservata gli avvisi giù presenti in area pubblica.

la cosa che per noi ha senso è avere in area riservata solo gli avvisi di manutenzione, ma senza creare un'area "avvisi", perché una volta che c'è stata la manutenzione l'avviso può essere cancellato e basta, senza bisogno di storico
