### ISSUE TITLE
[versione rilascio] HEADER - Voci di menu

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#19]
Anche se siamo in attesa dell'approvazione dei contenuti del sito da parte del Ministero dell'Interno, possiamo comunque già allineare le label delle voci di menu a quelle inviate come definitive. Attenzione all'esatta corrispondenza di maiuscole/minuscole e accenti.

**[PRIMO LIVELLO]**
Cos’è l’Anagrafe nazionale
**[SECONDO LIVELLO]**
Missione
Numeri
Notizie
Scopri cos’è l’Anagrafe nazionale →

**[PRIMO LIVELLO]**
Servizi anagrafici
**[SECONDO LIVELLO]**
Visura e autocertificazioni
Certificati
Rettifica dati
Cambio di residenza
Domicilio digitale
Scopri i servizi anagrafici →

**[PRIMO LIVELLO]**
Area tecnica
**[SECONDO LIVELLO]**
Accordi di fruizione
Formazione
Documentazione tecnica
Tabelle di decodifica
Archivio storico dei comuni
Guida all’Anagrafe nazionale
Scopri l’area tecnica →

**[PRIMO LIVELLO]**
Domande frequenti

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by gabripoggioli** [comment]
Modifica verificata, grazie. Chiudo la issue.
