### ISSUE TITLE
[ANSC] Guida all'ANSC - card formazione mancante

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#197]
Notiamo ora che mancherebbe **LA CARD** di rimando alla sezione di formazione, come da screenshot.

Di seguito il testo da inserire:
[TITOLO]
Partecipa alla formazione sull'ANSC
[TESTO]
Consulta il calendario della formazione sull'ANSC dedicata agli ufficiali di stato civile. I corsi sono organizzati da SNA e ANUSCA in collaborazione con Sogei e il Dipartimento per la trasformazione digitale.
[CTA]
VAI ALLA FORMAZIONE

<img width="774" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/50a4a086-b38d-41cc-a481-f92a28db74c9">

**Comment by fmilla74** [comment]
Trovi la nuova card in validazione. Se va bene la portiamo in produzione.

**Comment by steps88** [comment]
Per me ok, andiamo in produzione

**Comment by fmilla74** [comment]
Pubblicato in produzione

**Comment by steps88** [comment]
Verificato, grazie! <img width="956" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/e307f341-ded5-4c57-b397-3b2c99947d7f">
