### ISSUE TITLE
[ANPR] Feedback 8/11/2023

### ISSUE THREAD

**Issue by cstortone** [teamdigitale/anagrafenazionale.interno.it-site#198]
In merito a **Scrivania**, sono emerse le seguenti considerazioni:

1. I dati da visualizzare sono:

- prima sezione: “Dati utente” > generalità, contatto, residenza, famiglia (?)
- seconda sezione: "Di cosa hai bisogno > Servizi disponibili
- terza sezione: “Attività” e “In evidenza” 

2. È confermato che vengono mantenute le autocertificazioni con anteprima per responsabilizzare l'utente sulla verifica dei propri dati.

Servizio **Certificati**
L'utente deve poter scegliere tra Anagrafici, Elettorali, di Stato Civile. Considerare che mentre i dati anagrafici da certificare sono sempre presenti, quelli elettorali e di Stato civile potrebbero non esserlo e quindi l'opzione in questi casi non deve essere presente.

In merito ai **Certificati esenti da bollo**, le considerazioni emerse sono le seguenti:

- Rendere più parlanti i motivi di esenzione: ripartire da uno studio di razionalizzazione fatto in precedenza (DTD fornisce il file exl)
- Individuare il componente più adeguato per visualizzare i motivi di esenzione (lista a tendina, elenco aperto in pagina)
- Verificare la soluzione ANIS per la gestione pulsanti per ottenere il certificato (download, email, domicilio digitale) in alternativa alle checkbox attualmente presenti
- Valutare la possibilità di vedere l'anteprima automaticamente senza dover cliccare “Anteprima”

In merito alle modalità di **supporto all’utente,** la linea guida è capire come possiamo dare come assistenza e uniformare la modalità di visualizzazione contestuale. Attenzione alla visualizzazione mobile.

**Azioni concordate:**
- Apportare le modifiche a Scrivania, Profilo utenti, Certificati
- Analizzare rettifica dati e cambio residenza.

#183

**Comment by steps88** [comment]
Le nostre aggiunte (trovate anche post-it nel Miro)

### **Scrivania** 
- **dinamicità** – l'ordine delle sezioni dovrà essere dinamico: se l'utente ha delle pratiche o attività in corso vedrà prima-terza-seconda sezione; al primo accesso invece le vedrà come da vostro ordine, prima-seconda-terza
- **primo accesso:** la sezione dati se non completa potrà contenere degli inviti che descrivono i vantaggi a completare i dati mancanti
- **Tone of voice**: più che "Di cosa hai bisogno" preferiamo una forma più colloquiale "Che cosa vuoi fare?" e di conseguenza modificare i nomi dei servizi: fare un'autocertificazione, richiedere un certificato, rettificare i dati, cambiare residenza

### **Certificati**
_componente per visualizzare i motivi di esenzione_: riteniamo che la tendina (come ad oggi implementata) abbia delle limitazioni tecniche che non la rendono abbastanza user friendly: banalmente non si possono inserire testi lunghi o esempi, e l'utente non ha visibilità completa su tutte le esenzioni possibili

### **I miei dati**
- **Layout card:** preferiamo la versione 2, che si basa su modello comuni. Vorremmo però che lo spazio all'interno delle card fosse ottimizzato: quando ci sono contenuti la cui lunghezza è standard (es. CF, anno, ID ANPR, n° atto di nascita, ...) possono essere affiancati invece che incolonnati (es. la card carta d'identità) per evitare di allungare la pagina e dover scrollare molto
- **componente floating "FAQ + servizi"**: non ci torna l'inserimento delle domande frequenti, per questioni di lunghezza del testo e di non dinamicità rispetto al contenuto. Piuttosto manteniamo solo i collegamenti fissi ai servizi disponibili "Cosa ti serve?"
- **menu laterale**: immaginiamo abbia un comportamento a tab (vs ad ancore) per praticità nell'attaccarci azioni di analytics 
- **Sottotitolo alla sezione "Dati demografici"**: prima ancora di parlare di incongruenze bisogna descrivere cosa l'utente sta vedendo. 
- **Bottom page**: ci immaginiamo di avere a fondo pagina un'area di supporto (comune a tutti i servizi) che possa contenere le FAQ relative al servizio in uso, eventuali approfondimenti su terminologia o rif. legislativi, contatti d'assistenza e feedback form
- **Feedback form** "Questa pagina ti è stata utile" non potrà essere come in area pubblica, ma dovrà indagare l'esperienza d'uso del servizio


### **Sulle azioni da concordare**
Analizzare rettifica dati e cambio residenza: 
- ricordatevi di considerare i dati che ci avete condiviso il 3 agosto ("ANPR area riservata")
- nel file Figma trovate il flusso eIDAS "Trasferimento in Italia" che può darvi spunti
