### ISSUE TITLE
[ANPR] Feedback 15/11/2023

### ISSUE THREAD

**Issue by ncapozzi** [teamdigitale/anagrafenazionale.interno.it-site#200]
In merito a **rettifica dati**:
Abbiamo visto il flusso del servizio ed è stato deciso di:
-	tenere il flusso della validazione e-mail prima dell’accesso al servizio, solo se non è già presente nei tuoi dati e se il cittadino non ha il domicilio digitale
-	modificare la pagina di conferma validazione email per rimandare l’utente sul servizio di partenza;
-	indicare nella scheda informativa quando riceverà le informazioni in domicilio e quando per email;
-	ridefinire meglio le guide contestuali (approfondire benckmark).

Va stabilito:
- se alcuni allegati possano essere contestuali ai dati del servizio (owner SOGEI e DTD). Ci sembra di ricordare che DTD avrebbe fatto una verifica con Anusca per verificare se possibile avere un elenco degli allegati richiesti come già presente per l'iscrizione cittadini UE. Rimane comunque necessario un approfondimento dettagliato 
- se possibile inserire un pulsante sticky per l’accesso al servizio nella prima pagina di accesso (owner SOGEI); 
- come archiviare le informazioni sul banner di feedback, quale tripletta usare per dare motivazioni di difficoltà nell’uso (owner SOGEI e DTD). Va verificato se il Ministero è interessato a salvare queste informazioni su DB ANPR (owner DTD);
- se bastano autocertificazioni per gli enti PA in ottica di de-certificazione (owner DTD).

In merito a **certificati**:
- Confermiamo la modalità di ricezione del certificato. L’utente può scegliere la modalità di ricezione che preferisce (download, email, domicilio digitale). Inoltre per i certificati in bollo attualmente seleziona la modalità di ricezione prima di pagare e al pagamento riceve automaticamente il certificato se ha scelto email o domicilio digitale
- alla fine del flusso del servizio gestire attraverso un “banner” l'invito ad inserire email e domicilio digitale.

**Azioni concordate per la prossima settimana: analisi del servizio di Residenza**

**Comment by steps88** [comment]
Non ci torna l'ultimo punto:

> alla fine del flusso del servizio gestire attraverso un “banner” l'invito ad inserire email e domicilio digitale.

Non ci sembra il luogo adatto al banner, l'email viene verificata prima di entrare nel flusso (abbiamo concordato poco sopra), mentre il domicilio digitale manderebbe fuori dalla piattaforma ANPR

Aggiungo:
**“aggiorna stato mail”:** Sogei ha in carico la verifica per avere l'aggiornamento automatico (eliminando quindi il pulsante)

**Guida contestuale**: ci torna l'accordion, non molto la posizione. Da cittadino vorrei prima vedere i miei dati e poi eventualmente cercare un aiuto. Inoltre cosa contiene? come si comporta? come si comportano gli elementi interni?

**Area di supporto**: razionalizzare le informazioni, c'è molta roba. Assistenza telefonica forse non è così prioritaria (meno ingombrante) 

**Flusso certificati**: 
- eliminare la 2 thank you page (dopo aver richiesto l'invio alla mail)
- Portare motivazione di richiesta certificato PRIMA della scelta in bollo / in esenzione > da approfondire con Nicoletta

Due aspetti che non abbiamo toccato in riunione ma abbiamo pensato dopo sono:
- sarebbe utile che al primo accesso l'utente fosse invitato a compilare i propri dati (% di completamento profilo?)
- sarebbe utile usare i vocabolari controllati per i menu a tendina, quando possibile

**Comment by ncapozzi** [comment]
Buonasera,

per quanto riguarda l'Area di supporto attualmente nel prototipo abbiamo domande correlate, approfondimenti legislativi e di terminologia, assistenza e link utili come da voi suggerito. Sono d'accordo che c'è molta roba che il cittadino non leggerà mai, diteci voi cosa togliere. Per es. domande correlate, approfondimenti legislativi e di terminologia sarebbero più utili posizionati puntualmente sul contenuto specifico.

"Portare motivazione di richiesta certificato PRIMA della scelta in bollo / in esenzione > da approfondire con Nicoletta":
non mi è chiaro cosa vorreste fare, scegliere prima esenzione o bollo e poi il tipo di certificato (di nascita, residenza, matrimonio, etc.)? L'ordine attuale di scelta segue quello del rilascio effettuato dal Comune e credo sia stato a suo tempo concordato con il Ministero.

Due aspetti............
sarebbe utile che al primo accesso l'utente fosse invitato a compilare i propri dati (% di completamento profilo?) -> si può compilare solo i dati del profilo, per dati anagrafici mancanti deve rivolgersi al Comune
sarebbe utile usare i vocabolari controllati per i menu a tendina, quando possibile -> tutti i menù a tendina sono caricati a partire da tabelle registrate su Database, il cittadino non può digitare nulla in questi casi ma selezionare una delle voci visualizzate nella lista. Il contenuto è quello approvato dal Ministero e pubblicato in formato xls nell'area pubblica

**Comment by steps88** [comment]
### paragrafo 1
Lo stato dell’arte (4/12) dell’area supporto per noi è soddisfacente 

### paragrafo 2
Con "motivazione di richiesta certificato" intendiamo Vorremmo chiedere all’utente chi gli chiede il certificato, se ente pubblico o privato così da indirizzare su (certificato/autocertificazione) e poi continuare (con bollo/esente).

In particolare, guardando il flusso odierno di richiesta certificato (4/12) abbiamo commenti specifici:
Pg.24: chiedere QUI chi richiede il certificato [pubblico / privato] e fornire esempi di enti x ciascuno 

Pg.25: OK

Pg 26: _QUI_ differenziare tra elettorali/civile/anagrafico. Ad esempio mostrando 3 accordion con titolo + descrizione per ciascuna tipologia di dati, e all’apertura contengono le checkbox dei singoli certificati. Eliminare l’alert in alto, si può mettere nell’informativa privacy. 

Pg. 27: Non ci convince il layout, si innestano troppi elementi. Dividere in 2 step separati: 1) chiedo se il certificato serve per una delle esenzioni, 2) se nessuna delle precedenti ti rimando al cert. in bollo. Eliminare alert nel bollo, al max nella thankyou page. Non inseriamo immagini. 

Pg. 28: Attenzione ai copy: non “hai richiesto” ma "stai richiedendo" e soprattutto OTTIENI CERTIFICATO non "scarica": questa non è la thankyou page, idem per la pag.30. 

Attenzione anche ai pulsanti a fondo pagina: non ESCI --> ANNULLA 

### paragrafo 3
> sarebbe utile che al primo accesso l'utente fosse invitato a compilare i propri dati (% di completamento profilo?) -> si può compilare solo i dati del profilo, per dati anagrafici mancanti deve rivolgersi al Comune

OK, compilare i dati di profilo, di contatto

**vocabolari controllati:** Forse su questo punto serve un approfondimento tecnico. Il contenuto delle tabelle non cambia e non deve essere approvato nuovamente. Come da LLGG bisogna adottare vocabolari controllati per avere open data di livello 4 e non livello 2 come excel. https://docs.italia.it/italia/daf/lg-patrimonio-pubblico/it/stabile/modellodati.html  

Questo adattamento va fatto per garantire l’interoperabilità. Va fatto nel portale e va poi comunicato alle software house in maniera ufficiale. Andranno modificate infatti proprio le tabelle. C’è un attività dedicata nel PO2024. 

Dal punto di vista pratico bisogna riempire **la tabella attuale con i dati ottenuti dalla get API su schema.gov.it**, e mantenere aggiornata la tabella.
