### ISSUE TITLE
[ANPR] Feedback 22/11/2023

### ISSUE THREAD

**Issue by ncapozzi** [teamdigitale/anagrafenazionale.interno.it-site#201]
**Oggetto**: Servizio Residenza 

- È necessario identificare un elenco preciso degli allegati richiesti dalla procedura. Si propone un incontro con i comuni oppure l'analisi statistica per identificare gli allegati più frequenti. 
- La lista degli allegati potrebbe essere aperta a varie opzioni (aprire una discussione con Minardi, Masotti, Toscano?). 
- Documenti obbligatori: attualmente l'unico documento obbligatorio è il permesso di soggiorno per i cittadini extra UE. 
- Possibili servizi informativi nella TYP: considerare l'aggiunta di card informativi riguardanti servizi correlati come cambio medico e pediatra, denuncia tari, richiesta parcheggio disabili. 
- Rendere coerente il flusso con il servizio di Rettifica inserendo una TYP finale. 
- Nella verifica dei dati dei componenti della famiglia di destinazione preselezionare la verifica tramite codice fiscale. Etichettare come "suggerito". Questi dati sono obbligatori ma non devono necessariamente essere corretti.  
- Riconsiderare se nel caso di altri componenti maggiorenni che devono convalidare la dichiarazione, può essere opportuno ripristinare l’UPLOAD del modulo firmato manualmente come alternativa alla Convalida tramite SPID/CIE/CNS 

**Funzionalità di supporto:** 

Per l’area di supporto verrà data continuità alla proposta prototipata: 

- Nelle pagine descrittive del servizio è presente la sezione: 
“Potrebbe esserti utile” 

“Approfondimenti” 

“Cosa ti serve?” 

“Hai bisogno di aiuto” (es. Rimando alle FAQ di area pubblica) 

- Sono previste Guide contestuali durante l’utilizzo dei servizi (es. riportare su pagine HTML il contenuto delle attuali guide pdf) 

**Prossima settimana:** 

- Possibile incontro con ANCI, test di usabilità, vedere area “Le mie attività”, SDG, autocertificazioni, certificati per avvocati.

**Comment by ncapozzi** [comment]
Buonasera,

relativamente alla frase" Nel flusso mostrato manca “Aggiungi componente” perchè l’utente può aggiungerne uno che non fa parte del tuo nucleo famigliare" faccio presente che non si può aggiungere nella lista dei soggetti che si spostano un componente che non appartenga al nucleo familiare di partenza. Nel caso di cui si parlava ieri con il Dott. Minardi e la Dott.ssa Masotti i due cittadini interessati devono  fare 2 richieste separate.

Relativamente alla frase "proattiva: suggerire delle card di servizi utili / reminder alla fine del flusso di cambio residenza: cambio medico/pediatra, TARI, parcheggio" faccio presente che molti Comuni inviano automaticamente la comunicazione di cambio di residenza per es. alla ASL o nettezza urbana (io a Roma non ho dovuto comunicare niente a nessuno). Comunque il comportamento potrebbe essere diverso tra un Comune e un altro, quindi è sconsigliato secondo me dare indicazioni di questo tipo che potrebbero essere diverse da un Comune all'altro. Inoltre sarebbe meglio fornire solo e tutte le info necessarie al completamento della pratica di cambio di residenza rimandando magari al proprio Comune per verificare se ci sono adempimenti successivi da fare.

Schede servizio
Per le schede servizio tenere presente i seguenti content type (infomarmazioni minime valutate daegov benchmark):
a chi è rivolto,
tempistiche di accesso e di erogazione, -> come ben sappiamo i tempi di gestione della pratica possono cambiare da Comune a Comune (se si intende questo), quindi cosa indichiamo?
condizioni di servizio (recesso e simili), -> cosa si intende esattamente?
contatti specifici del servizio, -> l'email nel footer che inseriremo a breve sarà sostituita da una form da compilare per la richiesta di assistenza
possibilità di richiedere assistenza, -> vedi punto precedente
ultimo aggiornamento dei contenuti su pagina

**Comment by steps88** [comment]
Rispondo per punti:
**Aggiungi componente** > OK, ci siam confuse con eIDAS

**proattività** > Siamo d'accordo nel metterli a fine flusso (così non distraiamo l’utente) e nel dare suggerimenti generici + esempi che rimandino eventualmente a verificare con il proprio comune

**schede servizio**
> tempistiche di accesso e di erogazione, -> come ben sappiamo i tempi di gestione della pratica possono cambiare da Comune a Comune (se si intende questo), quindi cosa indichiamo? 

indichiamo i termini di legge entro i quali deve essere lavorata la pratica

> condizioni di servizio (recesso e simili), -> cosa si intende esattamente? 

Se non esiste una condizione di servizio si può tralasciare il paragrafo 

> contatti specifici del servizio, -> l'email nel footer che inseriremo a breve sarà sostituita da una form da compilare per la richiesta di assistenza 

OK, nel futuro. Per il momento abbiamo solo la mail
