### ISSUE TITLE
[ANPR] correzioni varie ed eventuali

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#202]
Usare "Informativa privacy":
- nel breadcrumb
- nel footer
<img width="787" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/58a2b96b-a55d-45c9-8a6b-a833e83d99fc">
<img width="611" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/e3225504-4f86-456a-ac0a-0cc2a6ec80ac">

**Comment by fmilla74** [comment]
@Clou-dia @steps88 ho effettuato la modifica in validazione. Per cambiare il valore del breadcrumb ho dovuto rivedere anche il titolo della pagina. Ho inserito il titolo esteso subito sotto in bold. Se va bene mettiamo la modifica in produzione cc: @e-mattei

**Comment by steps88** [comment]
Perfetto, cambierà anche l'url?

**Comment by steps88** [comment]
unica sottigliezza, la p di privacy nel footer va messa minuscola. 

Sistemato questo, possiamo andare in produzione! ✨
<img width="688" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/60285e4a-d0b0-4fb5-a3b4-d97a725b6f91">

**Comment by fmilla74** [comment]
La url resta uguale, ho inserito la p minuscola

**Comment by steps88** [comment]
la url rimane /privacy-policy?

**Comment by fmilla74** [comment]
Per ora non l'ho cambiata. Vuoi che la modifichiamo?

**Comment by steps88** [comment]
per coerenza direi di sì, grazie

**Comment by fmilla74** [comment]
la modifica alla url è stata pubblicata

**Comment by steps88** [comment]
perfetto! per noi si può andare in produzione
<img width="815" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/326f3ac7-c2bb-466c-afcd-7298e409dff5">

**Comment by fmilla74** [comment]
la modifica è stata pubblicata

**Comment by steps88** [comment]
<img width="954" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/435c8a20-b901-43b5-b15f-7d8b5e0ef1e8">
<img width="994" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/2dd52026-4431-4a11-ae2c-8981f8c8807b">
