### ISSUE TITLE
[ANPR] Feedback 6/12 - Lista di riepilogo dei risultati test di usabilità 

### ISSUE THREAD

**Issue by ncapozzi** [teamdigitale/anagrafenazionale.interno.it-site#204]
ANPR AREA AUTENTICATA – Lista di riepilogo dei risultati test di usabilità
1.	Profilo: 
- Rendere l’aggiornamento della mail automatico, oppure cambiare label in “Conferma validazione mail”;
- Rendere più evidente l’entry point per il servizio di rettifica. 
2.	Rettifica
- Campi input data: utilizzare input date con controllo inserimento;
- Visualizzare l’errore di compilazione solo una volta concluso l’inserimento;
- Verificare la gerarchia pulsanti nella thank you page. 
3.	Messaggio informativa valutare quando visualizzarlo (sarebbe opportuno visualizzarlo al primo accesso e poi solo nei casi in cui cambi l’informativa).
4.	Certificato in bollo
- Messaggio di pagamento andato a buon fine: descrivere dove trovare il certificato (“Il tuo pagamento è andato a buon fine. Puoi trovare i tuoi certificati nella sezione Le tue attività”)
- Denominazione file pdf (con la nuova progettazione l’anteprima è già visualizzata, di conseguenza l’utente scarica solo il certificato).
5.	Scrivania diventa Homepage
6.	Le tue attività possono diventare “Le tue richieste”
7.	Messaggio di inattività
- Posizionato in alto
- Avviso tramite modale qualche minuto prima
8.	Informare l’utente sul significato dell’ID ANPR: tramite tooltip?

**Comment by Clou-dia** [comment]
Come richiesto in call, se possibile identificare quali punti della lista sono stati già inseriti nel prototipo

**Comment by dioguardimarianna** [comment]
**ANPR AREA AUTENTICATA – Lista di riepilogo dei risultati test di usabilità**

1. Profilo:
    **•	Rendere l’aggiornamento della mail automatico, oppure cambiare label in “Conferma validazione mail”; - IN CORSO DI VERIFICA
    •	Rendere più evidente l’entry point per il servizio di rettifica.**
    •	Entry point profilo utente - Fatto
    •	Messaggi contestuali- Fatto
    •	Pagina di conferma validazione poco funzionale- Fatto
    •	Informare l’utente sul significato dell’ID ANPR: tramite tooltip? - Fatto

2. Rettifica:
    **•	Campi input data: utilizzare input date con controllo inserimento;
    •	Visualizzare l’errore di compilazione solo una volta concluso l’inserimento;
    •	Verificare la gerarchia pulsanti nella thank you page.
    •	Dichiarazione di voler ricevere notifiche più chiara per l’utente
    •	Tooltips con chiusura al click in qualsiasi parte della pagina**
    •	Pulsante salva in ciascun pannello – Fatto
    •	Costruire un percorso a step per gli utenti – Fatto
    •	Messaggi contestuali – Fatto


3. Messaggio informativa valutare quando visualizzarlo (sarebbe opportuno visualizzarlo al primo accesso e poi solo nei casi in cui cambi l’informativa). – Fatto

4. Certificato in bollo
•	Pulsante anteprima non chiaro – Fatto
•	Informativa richiesta ad ogni accesso - Fatto
•	Messaggio di pagamento andato a buon fine: descrivere dove trovare il certificato (“Il tuo pagamento è andato a buon fine. Puoi trovare i tuoi certificati nella sezione Le tue attività”) - Fatto
•	Denominazione file pdf (con la nuova progettazione l’anteprima è già visualizzata, di conseguenza l’utente scarica solo il certificato).
**•	Residenza
•	Migliorare la gerarchia dei contenuti**
•	Suddivisone a step – Fatto
•	Inserire contenuto di riepilogo nello step finale – Fatto
•	Messaggi contestuali – Fatto
 
**5. Scrivania diventa Homepage
6. Le tue attività possono diventare “Le tue richieste”
7. Più evidente la voce di menu attiva**
8. Richieste recenti non visibili perché in basso alla pagina - Fatto
9. Messaggio di inattività
**•	Posizionato in alto
•	Avviso tramite modale qualche minuto prima**

Oltre a queste modifiche emerse dai test di accessibilità, abbiamo visualizzato la pagina di Assistenza dove erano necessarie le seguenti modifiche:
•	Captcha visibile solo per il form di assistenza pubblico;
•	Prevedere solo due campi per la descrizione puntuale della problematica (ragionare su possibili contenuti da inserire)
