### ISSUE TITLE
[SDG] Flusso in inglese - Lista paesi

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#206]
La lista dei paesi (Sia per Luogo di nascita che per Cittadinanza) nel flusso in inglese è in italiano. Sarebbe possibile averla in inglese?

<img width="431" alt="Schermata 2023-12-20 alle 16 46 08" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/fb8a0ee0-65d8-4b70-9dee-8cbea1afb76c">

**Comment by Clou-dia** [comment]
@ncapozzi questa issue è stata mail analizzata? Possiamo verificarla?

**Comment by ncapozzi** [comment]
Buongiorno, è stata analizzata, realizzata e rilasciata in tutti gli ambienti insieme alle funzionalità per i cittadini UE

**Comment by Clou-dia** [comment]
grazie, se possibile uno screenshot aiuterebbe e chiudiamo la issue

**Comment by ncapozzi** [comment]
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/29276002/edcc2bef-7923-4412-a945-a3d8720a457f)

**Comment by Clou-dia** [comment]
grazie, chiudo
