### ISSUE TITLE
[ANPR] - Feedback incontro 10/01/2024 - Backlog riprogettazione - Certificati e autocertificazioni

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#207]
Di seguito i punti emersi durante la call

**Certificati**
- **Modale informativa servizio** Per ogni servizio si preveda che l'informativa privacy con il checkbox di accettazione del servizio venga inserito tra la scheda servizio e il primo step del flusso, come una modale (vedasi eidas)
- Lo step **Uso** "Chi ti sta chiedendo il certificato?" valido solo per certificati anagrafici. 
- Scelta di **certificati in bollo**: aggiungere info sul pagamento (etichetta o testo) e togliere _Nessuna delle precedenti_ dalla lista esenzioni 
- Nella pagina di **riepilogo** inseriamo i pulsanti “Indietro – Ottieni”; nella thank you page inseriamo “Scarica – invia 1 – invia 2”. 

**Decisione su 1 o tre schede servizio Certificati**

Lasciamo una pagina snodo generica di Certificati, con 3 rimandi specifici alle varie tipologie (vedi INPS) e per ciascuna tipologia avremo una scheda servizio dedicata. Allo stesso modo nel menu di navigazione avremo un 3 livello di approfondimento che parte da Certificati e mostra le 3 sottovoci. Così agevoliamo anche il SEO. 
Vedi esempio INPS per pagina snodo.
<img width="609" alt="Schermata 2024-01-16 alle 10 59 36" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/98462345/69e0d577-bc1d-4bdd-872a-bc48e71c3173">

**Autocertificazione**
Visto che c’è chi richiede specificatamente le autocertificazioni e se vogliamo spingere la decertificazione serve renderla autonoma. Quindi l'accesso alle autocertificazioni avverrà da homepage, da pagina i tuoi dati e dal bivio dei certificati anagrafici.

**Content type delle schede servizio**

- A chi è rivolto il servizio  
- Che cos’è (descrizione) 
- Cosa serve 
- Come richiederlo  
- Quanto costa 
- Tempi e scadenze 
- Che cosa ottieni

**Comment by ncapozzi** [comment]
Buonasera, 
aggiungiamo che sono state condivise ed approvate alcune modifiche per motivi di accessibilità:

-     Per il servizio certificati nello step “uso del certificato” usare i radio button con a comparsa i motivi di esenzione, in caso di esenzione da bollo;
-     Per tipologia di residenza scelta a radio button invece che a card;
-     Per la scelta dei componenti della famiglia usare una tabella sia su servizio residenza che su certificati;
-     Nel servizio residenza per la sezione “immobile” usare radio button con elenco a comparsa.
