### ISSUE TITLE
[versione rilascio] DOMANDE FREQUENTI - Aggiungere sezione Area tecnica

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#21]
In coda alle sezioni di domande frequenti già inserite (Generali, Visura e autocertificazioni, Certificati, Rettifica dati, Cambio di residenza), aggiungere un'ultima sezione **Area tecnica**.

**Comment by fcassandra** [comment]
La modifica attiene prettamente ai contenuti e sarà effettuata durante il caricamento delle pagine e contenuti su wordpress

**Comment by gabripoggioli** [comment]
Perfetto, grazie del chiarimento, chiudo la issue.
