### ISSUE TITLE
[ANPR] - Feedback incontro 24/01/2024 

### ISSUE THREAD

**Issue by ncapozzi** [teamdigitale/anagrafenazionale.interno.it-site#210]
Presenti: 
per Sogei: Marianna Dioguardi, Giuseppe Barone, Alessandro Pucci, Alessandro Palombi, Capozzi Nicoletta, Alesandra Zangari. 
per DTD: Stefania Guerra, Gabriella Poggioli, Claudia Pollina

RESIDENZA
•	Il button "? Supporto" deve essere nelle card grigie, più specifico sulle sezioni di pertinenza.
•	togliere numero di pratica dal titolo: dargli meno importanza
•	Viene richiesto un file con tutti i testi dei messaggi KO
•	aggiungere un reminder ai servizi collegati extra-ANPR (cambio medico/pediatra, TARI, parcheggio)
•	alla login va aggiunta eIDAS
•	confermato il wizard ma vanno rivisti i testi in una sessione dedicata
CITTADINI UE
•	In HP fare due/tre righe per i servizi: "Devi ancora accedere" e "Cos'altro puoi fare" e Certificato (è solo per chi in ANPR c'è stato ed ha un CF
•	Mantenere il menu con HP e Domande frequenti
•	Va fatto un ragionamento sui link del footer. Quali link? Solo Domande frequenti?
•	Togliere "Questa pagina ti è stata utile"
•	email di registrazione deve essere uno step dedicato
•	"Aggiungi altro componente" mostrare una lista dei componenti inseriti in modo che l'utente possa visualizzare i dettagli ed eventualmente modificarli o cancellare il componente
•	Negli allegati manca la colonna OOTS
•	Negli allegati prevedere il passaggio dell'antivirus in automatico
•	“Approfondimenti” rimandano verso portale UE Europe oppure su sistemi di interoperabilità 
•	"Cosa ti serve" non serve
Punti aperti
•	Definire riepilogo e capire come fare il caricamento del documento firmato senza rimandare l'utente alla sezione allegati
•	Organizzare una demo con Comuni e Anusca nei  primi giorni di febbraio, e poi Ministero Interno che deve ancora vedere cambio residenza, richiesta di rettifica e certificati

Mercoledì 31/1 completeremo la condivisione dei flussi relativi ai cittadini UE mentre mercoledì 7/2 sarà dedicato alla versione mobile.

**Comment by steps88** [comment]
Ad oggi non abbiamo ancora ricevuto il file con tutti i testi dei messaggi KO. Ci date una tempistica? @ncapozzi 

Ministero Interno deve vedere solo certificati e certificati per avvocati, gli altri flussi sono già stati condivisi.

**Comment by ncapozzi** [comment]
Buongiorno
Allego elenco msg e  testi email
[Messaggi Area Riservata.xlsx](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/files/14221488/Messaggi.Area.Riservata.xlsx)
[testi_email_sc.docx](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/files/14221489/testi_email_sc.docx)
