### ISSUE TITLE
[ANPR] Area riservata / Dati elettorali: correzione maiuscole minuscole in microcopy

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#211]
È opportuno correggere l'utilizzo delle maiuscole/minuscole nei seguenti microcopy nei servizi relativi ai dati elettorali in Area riservata

**VISURA**

- [ ] non "Numero Sezione" ma "Numero sezione"

<img width="112" alt="Schermata 2024-03-14 alle 09 11 18" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/101180195/e3cec369-0b38-4be7-ad9d-df9c22275c0d">

- [ ] non "Senato della repubblica" ma "Senato della Repubblica"

<img width="236" alt="Schermata 2024-03-14 alle 09 12 38" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/101180195/73e8e9e6-807a-4d78-b8c9-5cdd639cc4b5">

**FLUSSO CERTIFICATI**

- [ ] non "di Godimento dei Diritti Politici" ma "di Godimento dei diritti politici"
- [ ] non "di Iscrizione nelle Liste Elettorali" ma "di Iscrizione nelle liste elettorali"

<img width="242" alt="Schermata 2024-03-14 alle 09 14 52" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/101180195/b6b84063-63ea-41ed-b40d-79448b6f58f5">

**Comment by ncapozzi** [comment]
Fatto e rilasciato anche in produzione, saluti
