### ISSUE TITLE
[SITI IN LINGUA] Modifica testuale post integrazione dati elettorali

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#212]
Nella fascia di accesso ai servizi nella HP in inglese:

<img width="724" alt="Schermata 2024-03-18 alle 13 06 01" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/101180195/c84b9ceb-5420-44c6-b75f-77a9172fe293">

- [x] Modificare il titolo "Citizens' area" in "Available services"
- [x] Modificare la label della CTA "GO TO CITIZENS' AREA" IN "LOG IN TO SERVICES"

**Comment by fmilla74** [comment]
@gabripoggioli modifiche effettuate

**Comment by gabripoggioli** [comment]
<img width="713" alt="Schermata 2024-03-25 alle 11 44 14" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/101180195/2f7f9dc1-4bdc-48f8-8670-59eb41e35d7b">

Modifiche verificate, chiuso la issue, grazie mille
