### ISSUE TITLE
[AR] Modale Informativa privacy

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#214]
- [x] Lo stile dei testi dell'informativa stessa va migliorato: alcuni sono molto grandi (es. titoli troppo grandi) 
- [x] Mancano i loghi PNRR nel footer
- [x] l'altezza del componente footer deve essere adattata al contenuto
<img width="632" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/61677ec4-a24b-4aa3-9599-f974d5a87ac0">
<img width="1182" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/f7575378-0461-4b95-ac98-48879addaa8a">

**Comment by Clou-dia** [comment]
@ncapozzi @gppbarone in stage alla data attuale non ci sono avanzamenti sui tre punti segnalati nella issue

**Comment by ncapozzi** [comment]
@Clou-dia non avevamo aggiornato lo stato ma gli interventi sono stati eseguiti

**Comment by steps88** [comment]
Non vedo avanzamenti ![Image](https://github.com/user-attachments/assets/07ee37aa-9361-4f8f-84ff-adacd8295fec)

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
non vedo modifiche

**Comment by ncapozzi** [comment]
@steps88 Abbiamo verificato che le modifiche sono presenti. Puoi provare il refresh della pagina?
Per quanto riguarda i titoli, come ti ho evidenziato anche nella #231, sono h1, h2 e h3

**Comment by steps88** [comment]
Se confronto gli stili di testo con quelli dell'Informativa privacy sull'attuale sito, ci sono delle differenze:

- [x] **(i) Dati trattati tramite il Sito** è h2, dovrebbe essere **h3** (è un sottoparagrafo di "Tipologia di dati, modalità e finalità del trattamento")
- [x] **Dati di navigazione** e tutti i titoli prima di **(ii) Dati anagrafici trattati nell'ambito di ANPR** di conseguenza dovrebbero essere h4
- [x] **(ii) Dati anagrafici trattati nell'ambito di ANPR** dovrebbe essere h3
- [x] **Comunicazione e diffusione dei dati** dovrebbe essere h3
- [x] **Diritti degli interessati** > h3
- [x] **Diritto di reclamo** > h4

**Comment by steps88** [comment]
Verificato ![Image](https://github.com/user-attachments/assets/07581cad-c3b0-4b0f-b3f5-7bd7e262dbdd)
