### ISSUE TITLE
[AR] Modale Dati di contatto

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#215]
Eliminare le righe separatrici se il contenuto interno non scrolla 

<img width="627" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/a371e90b-925c-41ab-ab86-953fd943c59a">

**Comment by ncapozzi** [comment]
Intendi la riga verticale a sinistra? 
Ci potete confermare per favore se nelle modali i pulsanti vanno tenuti sempre a sinistra?

**Comment by steps88** [comment]
Intendo le righe orizzontali in grigio
Sinistra o centro, basta essere coerenti, personalmente direi centro

**Comment by Clou-dia** [comment]
Dalla verifica risultano ancora presente le linee orizzontali anche senza necessità di scroll del testo nel pop up

<img width="1243" alt="Schermata 2024-09-05 alle 18 42 44" src="https://github.com/user-attachments/assets/c828143c-2f09-4ed9-a59a-fbdd7da8eb80">

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Ridurre lo spazio tra titolo e testo "i dati di contatto" e aumentarlo tra testo e l'alert

<img width="933" alt="image" src="https://github.com/user-attachments/assets/e6068405-529e-48ee-a270-5a5d83c95a88">

**Comment by ncapozzi** [comment]
@steps88  puoi verificare

**Comment by steps88** [comment]
Verificato ![Image](https://github.com/user-attachments/assets/9fb12b41-e592-4bd9-b511-73ead26ed9fa)
