### ISSUE TITLE
[AR] Homepage 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#216]
- [x] Il logo ANPR deve essere cliccabile e portare alla homepage dell'area riservata
- [x] i Link nel megamenu dopo aver cliccato diventa nero > usare la sottolineatura invece del colore 
- [x] con megamenu aperto se si clicca ai margini laterali bianchi, il megamenu non si chiude
- [x] usare Bottoni outline e non primary per: visualizza i tuoi dati, richiedi assistenza (sempre su tutte le pagine) 
- [x] rimuovere l'ombra al box "Benvenuto cittadino"
- [x] Footer: mancano i loghi PNRR, Altezza da rivedere > + slim 
- [x] Tendina del profilo utente: ~modificare "Contatti" con "I tuoi dati"~ eliminare il CF
-  ~Manca la sezione **Notizie**~
- [x] rivedere l'ordine degli elementi in base a primo accesso / accessi successivi com segue

Ordine degli elementi al **primo accesso**:  
- Benvenuto 
- Di cosa hai bisogno > aggiungere qui lo sfondo  
- I tuoi dati > togliere lo sfondo 
- Le tue richieste [eliminata perchè non ha richieste]

Ordine degli elementi agli **accessi successivi al primo**: 

- Benvenuto 
- Le tue richieste  
- Di cosa hai bisogno > aggiungere qui lo sfondo  
- I tuoi dati > togliere lo sfondo 

### [mobile] 
i tuoi dati - accordion: mantenerli aperti di default e non chiusi (almeno il primo) 

<img width="318" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/39c45ce4-a0e8-488b-867d-daadc96a8577">

<img width="163" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/4694917c-478d-43db-988a-14df0f8ff961">

**Comment by ncapozzi** [comment]
Tendina del profilo utente: modificare "Contatti" con "I tuoi dati", -> si chiama "Contatti" perchè rimanda solo ai Contatti (email e recapiti telefonici) mentre "I tuoi dati" rimanda a contatti più data demografici
eliminare il CF -> OK
 Manca la sezione Notizie ->eliminata come deciso con scambio email del 17/4 per evitare problemi con le traduzioni. Si era deciso in quell'occasione di tenere le notizie solo in area pubblica

**Comment by ncapozzi** [comment]
Se il cittadino ha delle richieste l'ordine è già quello da voi evidenziato.
Se il cittadino NON ha ancora effettuato richieste, abbiamo convenuto anche con i colleghi della UI, di non visualizzare proprio la sezione con la frase "Non ci sono richieste in corso" che tra l'altro al primo accesso è per forza così. Posta al quarto posto la maggior parte degli utenti non la vedrebbe proprio, e comunque la sezione rettifiche nell'ordine da voi suggerito potrebbe cambiare posto anche durante la stessa sessione di lavoro: inserisco una richiesta trovo la fascia al secondo posto, poi la elimino e mi ritroverei appunto la fascia al quarto posto solo con la frase. Quindi anche per non creare confusione abbiamo preferito non esporre la fascia in assenza di richieste se siete daccordo altrimenti secondo noi meglio fissa al secondo posto
Ordine degli elementi al primo accesso:
Benvenuto
Di cosa hai bisogno > aggiungere qui lo sfondo
I tuoi dati > togliere lo sfondo
Le tue richieste
Ordine degli elementi agli accessi successivi al primo:

Benvenuto
Le tue richieste
Di cosa hai bisogno > aggiungere qui lo sfondo
I tuoi dati > togliere lo sfondo

**Comment by ncapozzi** [comment]
[mobile] i tuoi dati - accordion: mantenerli aperti di default e non chiusi (almeno il primo)
Nel prototipo sono stati disegnati aperti per mostrare il contenuto ma in realtà la pagina potrebbe avere molte sezioni oltre quelle sempre presenti (generalità, famiglia, residenza, cittadinanza, atto di nascita, documenti, matrimonio, divorzio, vedovanza...dati elettorali). Per il cittadino può diventare complicato lo scorrimento verticale con gli accordion già tutti aperti. Come procediamo?

**Comment by steps88** [comment]
Il consiglio è di mantenere aperto **almeno il primo**, vederli aperti porta comunque il cittadino a controllarli che male non fa

**Comment by steps88** [comment]
### ordine richieste 
> Se il cittadino NON ha ancora effettuato richieste, abbiamo convenuto anche con i colleghi della UI, di *non visualizzare proprio la sezione* con la frase "Non ci sono richieste in corso" che tra l'altro al primo accesso è per forza così. 

Va bene!

**Comment by Clou-dia** [comment]
Alla data attuale 5/9 task sono completati.

In particolare sull'ordine la verificato l'ordine degli elementi agli accessi successivi al primo, che risulta diverso dal concordato. 
  Benvenuto
  Le tue richieste
  I tuoi dati 
  Di cosa hai bisogno 
  
 Per verificare nuovamente un primo accesso come possiamo fare?

**Comment by ncapozzi** [comment]
@Clou-dia  Questa è la situazione aggiornata
-	 i Link nel megamenu dopo aver cliccato diventa nero > usare la sottolineatura invece del colore  FATTA
-	 usare Bottoni outline e non primary per: visualizza i tuoi dati, richiedi assistenza (sempre su tutte le pagine)  NON FATTA
-	Footer: mancano i loghi PNRR, Altezza da rivedere > + slim  FATTA
-	rivedere l'ordine degli elementi in base a primo accesso / accessi successivi com segue  NON FATTA

Per un primo accesso potete utilizzare VNZMGL75A01A089H, VNZFGL00A41A089J

**Comment by steps88** [comment]
manca solo l'ultimo punto sull'ordine degli elementi al 1 e secondo accesso 
(l'immagine mostra un secondo accesso e la sezione "I tuoi dati" dovrebbe stare dopo "Di cosa hai bisogno"
![Image](https://github.com/user-attachments/assets/1c8f1d26-235b-4842-a00b-6d34107a3c52)

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
@ncapozzi ci resettate un utente per vedere la pagina al primo accesso per favore?

**Comment by steps88** [comment]
Verificato 
![image](https://github.com/user-attachments/assets/1e5ff7ea-aee2-4e8d-bcb6-00a92231491e)
