### ISSUE TITLE
[AR] I tuoi dati

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#217]
- [x] "Dati di contatto" ha un font diverso da "dati demografici", ma sono allo stesso livello gerarchico, dovrebbero essere uguali
- [x] Il pulsante “Nascondi” va solo nei box bianchi (Carta di identità e residenza hanno il nascondi nella parte azzurra)
- #227

- [x] **[mobile]** “I tuoi dati demografici” tenere aperto almeno il primo accordion interni alle sezioni (card bianche) 

Sul 2 punto, del pulsante Nascondi, eravamo d'accordo di tenerlo solo all'interno delle card bianche perchè a quelle azzurre ci si arriva già col menu laterale.

<img width="674" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/08be6e71-2f59-409a-a949-b81eb5c67657">
<img width="514" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/10f72b90-5917-480e-800a-6b21412ccdc0">
<img width="671" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/a49b0b20-7e9f-4a0b-97b7-fce9b8d8ef9e">

**Comment by ncapozzi** [comment]
Le azioni per rettifica dati e autocertificazione sono finite in fondo alla pagina, sotto ai box dei dati; nel mockup erano previsti sotto il side menù a sx per desktop.-> avere sia il menù che i pulsanti a sinistra portava ad avere un contenuto che superava l'altezza della finestra di un browser su un portatile da 13 pollici, risultando quindi nella presenza della barra di scorrimento verticale

[mobile] “I tuoi dati demografici” tenere aperti di default tutti gli accordion interni alle sezioni (card bianche) > #216 stesso commento

**Comment by steps88** [comment]
Sul mobile: 
Il consiglio è di mantenere aperto **almeno il primo**, vederli aperti porta comunque il cittadino a controllarli che male non fa

sulle azioni nella sidebar, ho convertito in issue la riga della checklist cosi possiamo discuterne separatamente @ncapozzi

**Comment by steps88** [comment]
Primi due punti verificati 
![Image](https://github.com/user-attachments/assets/49b1acc9-200e-4da3-9565-021d21f71597)

**Comment by anpr-opendata-team** [comment]
@sguerra issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Verificato anche il terzo punto, gli accordion risultano tutti aperti
<img width="427" alt="image" src="https://github.com/user-attachments/assets/c6923a0b-d1e6-4508-bc2c-8a5925bd426c">
