### ISSUE TITLE
[AR] Modifica contatti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#218]
- [x] **Al 1 accesso** dovrei vedere UN solo campo Telefono e non 2. Quando ne ho salvato uno, dovrei vedere l’input per aggiungere il 2, che da mockup è una CTA button “Aggiungi altro recapito”

- [x] BUG: Se entro nuovamente nella pagina di modifica dopo aver salvato un recapito e aggiungo il secondo, il primo sparisce: devo per forza compilare entrambi i box per averli salvati entrambi 
- [x] Copy: usare "recapito telefonico" (include fisso o cellulare) 
- [x] Salva recapiti telefonici > Solo "Salva" 
- [x] Valida email: una volta cliccato il bottone, il campo email diventa rosso – Meglio nero/azzurro o comunque non rosso/verde 
- [x] Dopo la verifica, il bottone post verifica dovrebbe dire Salva (invece ora “valida email”) 
- [x] **Pagina di email verificata correttamente** > rendere la UI parlante con la riprogettazione (es. Non tutta blu, vedi template dei messaggi di errore)
<img width="1366" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/53a6d821-4334-4524-b5f4-666985e18fb9">
<img width="1369" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/ae7c5e1a-6927-4da6-86fa-3c57bd41fb59">

![ANPR AR valida email](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/3d85e755-1bbd-446b-b39d-c7113db88222)

<img width="823" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/65df38fe-3917-4cad-a64d-5d80b8a6c61d">

**Comment by ncapozzi** [comment]
Riporto quanto già anticipato con email del 19/4 	i recapiti telefonici attualmente salvati sul db hanno i formati più diversi e quindi abbiamo dovuto adottare una strategia un po' diversa da quella inizialmente pensata per gestire anche tutto il pregresso. Anticipo che stiamo ancora rivedendo la gestione  anche in considerazione del fatto che i recapiti telefonici possono essere eliminati non essendo obbligatori. 
Considerato che i recapiti telefonici possono essere max due, sono stati lasciati fissi i campi Telefono e Altro telefono ed è stato tolto il tasto Aggiungi

**Comment by steps88** [comment]
Cerchiamo di allinearci sulle casistiche:
- Se l'utente ha già inserito **2 recapiti**:
  - visualizza i campi input _precompilati_ e **non** vede il tasto Aggiungi

- Se ha già inserito **1 recapito**:
  - visualizza il primo input _precompilato_ e il tasto Aggiungi _abilitato_
  - cliccando sul tasto Aggiungi comparirà il 2 input vuoto

Se l'utente ancora **non ha aggiunto un recapito** telefonico:
- visualizza il primo input _vuoto_ e il tasto Aggiungi _disabilitato_

Concordi? 
Altrimenti fateci sapere se ci sono casi che non stiamo considerando

**Comment by steps88** [comment]
Non vedo avanzamenti ![Image](https://github.com/user-attachments/assets/568da83e-5e61-48b3-b2ae-c70e41a35e6d)

**Comment by ncapozzi** [comment]
Buonasera @steps88,
procediamo come avevi indicato per quanto riguarda il tasto "Aggiungi" del secondo recapito telefonico.
Le altre richieste sono già state implementate.

**Comment by steps88** [comment]
Mancano i primi 2 punti, gli altri verificati
![image](https://github.com/user-attachments/assets/24ed55d7-f9e2-4087-ad81-24335fd5de27)
![image](https://github.com/user-attachments/assets/9332103e-09bb-416f-b56b-443221a9cd56)

**Comment by steps88** [comment]
#234

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Verificato
![image](https://github.com/user-attachments/assets/b06017dd-99fc-4e2a-bf7f-7fa33dc24cb0)
