### ISSUE TITLE
[versione rilascio] Homepage: avviso in hero space

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#22]
Quando si fa resize del browser (Chrome nel mio caso) il banner/avviso in Home in hero space si posiziona in uno spazio con sfondo bianco, non si modifica con lo sfondo come da prototipo mobile

<img width="593" alt="Schermata 2022-07-28 alle 12 25 50" src="https://user-images.githubusercontent.com/98462345/181521276-24e73d16-f3ec-48e7-a0cb-117783a9f402.png">

**Comment by fmilla74** [comment]
su questo punto  trovi un post su teams

**Comment by Clou-dia** [comment]
> 

ma il thread su sticky mobile? li non c'era l'alert però? se invece altro potresti linkarlo gentilmente?

**Comment by fmilla74** [comment]
ti ho appena taggata. è l'ultimo post del canale su Teams

**Comment by Clou-dia** [comment]
> ti ho appena taggata. è l'ultimo post del canale su Teams

visto, va bene.

Chiudo commento in attesa della prossima release con nuova versione

**Comment by fmilla74** [comment]
@Clou-dia , avviamo le modifiche dell'avviso (la fascia a se stante, non è overlay)

**Comment by fcassandra** [comment]
Le modifiche sono già disponibili nella versione 1.1 appena rilasciata

**Comment by fmilla74** [comment]
Abbiamo ricontrollato e le modifiche sono ancora in test. Le vedrai con il prossimo rilascio.

**Comment by fcassandra** [comment]
rilasciata versione con le modifiche concordate
