### ISSUE TITLE
[AR] Certificati: scheda di servizio

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#220]
- [x] Rivedere la UI del sottotitolo di pagina, ad esempio come nel sottotitolo di pagina nell'area pubblica
- [x] Quando è fixed on top, centrare il bottone _Utilizza servizio_ rispetto al box (per tutte le tipologie di certificati)
- [x] Eliminare la linea grigia in “Guida alla compilazione” 
<img width="1416" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/d5d9c37d-2e78-430f-8aa8-cd1c51366868">
<img width="1392" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/72076999-f6c4-4715-acb2-bfd035d93232">

**Comment by ncapozzi** [comment]
Quando è fixed on top, centrare il bottone Utilizza servizio rispetto al box (per tutte le tipologie di certificati) -> in orizzontale o in verticale?

**Comment by steps88** [comment]
in verticale: il margine top è minore di quello bottom ora

**Comment by steps88** [comment]
È sparita l'ombra del titolo di pagina quando diventa fixed, come mai?
![Image](https://github.com/user-attachments/assets/b4cc15ff-4b5d-403c-b0a8-b348ea11fb56)

### Il resto è verificato 
![Image](https://github.com/user-attachments/assets/659a8c59-5a02-4bde-a298-dfeb267e1f51)

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Verificata 
<img width="1419" alt="image" src="https://github.com/user-attachments/assets/676695aa-14cd-4af7-ad2a-d534957eddc2">
<img width="1416" alt="image" src="https://github.com/user-attachments/assets/5568d968-cf23-472c-baad-a6ff01d0e414">
