### ISSUE TITLE
[AR] Certificati: flusso

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#221]
- [x] Da desktop, aumentare l’ingombro (larghezza) del box di testo sotto il titolo (Se hai bisogno di riunire...), per evitare che faccia scendere troppo il contenuto importante
<img width="1316" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/280a5d03-2e71-4e32-90c0-9538d3579802">

- [x] Aiuto > link non apre una modale (anche solo placeholder vuota) ma porta all’informativa privacy 
- [x] Stepper: quando _fixed on top_  eliminare margini/padding top e bottom
<img width="1420" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/ea2a36d8-c3ae-45fc-ad22-697350d59566">

- [x] Intestatario > Diminuire la spaziatura tra prima colonna (radio button) e colonna nome  
- [x] Nel caso in cui sia solo un componente nella famiglia anagrafica pre-selezionare il radio button relativo 
- [x] Intestatario scheda: aggiungere una (i) informativa che apre modale “Aiuto” (per spiegare cosa significa)
<img width="951" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/eff19a03-8d41-4a34-a880-ee2846aace7c">

- [x] Uso > in bollo: aumentare un poco lo spazio tra prima frase (in bollo) e testo descrittivo (Se ti è richiesto...)
<img width="865" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/367a82eb-29b0-433d-a199-fb963e723a08">

### Riepilogo
- [x] Eliminare linea grigia 
- [x] Allineare in colonne separate i metadati e i dati dell’utente 
- [x] Scarica l’anteprima: meglio usare bottone secondary outline > non c'è modo di evitare di **scaricare** il pdf ma incorporarlo o aprirlo in nuova scheda?
- [x] Vai al pagamento > la posizione del pulsante dovrebbe essere al posto di "avanti" ed essere disabilitato fino a che non si vede l’anteprima 
<img width="792" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b09b6a91-be7e-42b5-b1b7-77e2e2184e4c">

- [x] [mobile] Bottone annulla lasciare solo icona (modificare cestino con “x”) ed eliminare testo annulla 
<img width="376" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/aef3177e-ec5a-4dfc-8538-d9a6c0c4796b">

**Comment by ncapozzi** [comment]
Se non ricordo male per tutti i link ?Aiuto apriamo una modale nella quale riportiamo il contenuto della guida operativa specifico per la pagina dove è posizionato il link. Confermate?

**Comment by ncapozzi** [comment]
Scarica l’anteprima: meglio usare bottone secondary outline > non c'è modo di evitare di scaricare il pdf ma incorporarlo o aprirlo in nuova scheda? -> il comportamento dipende dalle impostazioni del browser che si sta utilizzando

**Comment by steps88** [comment]
> Se non ricordo male per tutti i link ?Aiuto apriamo una modale nella quale riportiamo il contenuto della guida operativa specifico per la pagina dove è posizionato il link. Confermate?

Sì corretto, ora però non si apre una modale ma l'informativa privacy in nuova pagina del browser

**Comment by ncapozzi** [comment]
Si grazie Stefania ho visto, vi chiedevo solo conferma di come vi aspettate che debba essere.

**Comment by ncapozzi** [comment]
[mobile] Bottone annulla lasciare solo icona (modificare cestino con “x”) ed eliminare testo annulla
Possono andare bene i pulsanti full-width?
![MicrosoftTeams-image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/29276002/14f5c417-357c-4730-9170-2c54029a0f99)

**Comment by steps88** [comment]
> [mobile] Bottone annulla lasciare solo icona (modificare cestino con “x”) ed eliminare testo annulla Possono andare bene i pulsanti full-width? ![MicrosoftTeams-image](https://private-user-images.githubusercontent.com/29276002/341804291-14f5c417-357c-4730-9170-2c54029a0f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTQ5NjksIm5iZiI6MTcxOTIxNDY2OSwicGF0aCI6Ii8yOTI3NjAwMi8zNDE4MDQyOTEtMTRmNWM0MTctMzU3Yy00NzMwLTkxNzAtMmM1NDAyOWEwZjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA3Mzc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MWZlODMwYTQyNGZhZjM1ODU3ODUyZmJiZjIxZDQwNDA5ODZlNWFmYTdmMDdjYzE3MTA3ZGNmZWM0MDMyMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ww1IrmSeBpCRKQETcWjjv0Abwzz8p9UMhe_g7Kyg820)

Non vedo la necessità in questo caso Nicoletta, altrimenti avremmo un set di 4 pulsanti full width (scarica anteprima, vai al pagamento, indietro, annulla). 
La richiesta è fare in modo che nel pulsante Annulla non ci sia un a capo tra icona testo e, se riuscite a portare su unaa riga sola, teniamo pure icona+testo

**Comment by ncapozzi** [comment]
@steps88 per quanto riguarda i link di **?Aiuto** stavamo pensando che se utilizziamo una modale l'utente non può tenere aperte contemporaneamente la pagina di inserimento dati e la modale di aiuto con le istruzioni da seguire. Se invece della modale apriamo una pagina, l'utente ci sembra più facilitato perché può contemporaneamente leggere le istruzioni ed inserire i dati. Che ne pensi?

**Comment by steps88** [comment]
Mi torna, addirittura userei l'apertura in nuova finestra invece che nuova pagina, così da poterla muovere / affiancare / rimpicciolire come se fosse una modale

**Comment by steps88** [comment]
Mancano 2 punti, inoltre è spuntato un box che racchiude tutte le info e rende la pagina diversa da come trattiamo le precedenti, toglierlo per favore.
![Image](https://github.com/user-attachments/assets/13fc8ff8-7be9-44e2-8b20-b62b0cbd3848)


### Verificati:
Larghezza testo
![Image](https://github.com/user-attachments/assets/d9be2f9f-e088-47e6-8a5a-90c400b47dce)
Modale aiuto in nuova finestra
![Image](https://github.com/user-attachments/assets/d3761cf9-e998-4027-9e00-868bcd047ede)
Distanza bollo ![Image](https://github.com/user-attachments/assets/36b7e9cf-2ee4-4615-88e5-861ea5536f66)

**Comment by ncapozzi** [comment]
@steps88  per verificare "Nel caso in cui sia solo un componente nella famiglia anagrafica pre-selezionare il radio button relativo" puoi accedere con uno dei due CF che vi abbiamo mandato il 13/09/2024 per Iscrizioni  cittadini UE nelle liste elettorali

**Comment by ncapozzi** [comment]
@steps88  Intestatario scheda: aggiungere una (i) informativa che apre modale “Aiuto” (per spiegare cosa significa) -> Possiamo aggiungere l'informativa nella pagina di **?Aiuto** già predisposta per la form, altrimenti dovremmo aggiungere la solita i con tooltip ma la frase è troppo lunga. "L'intestatario della famiglia anagrafica è il componente della famiglia rispetto al quale si definiscono i legami di parentela degli altri componenti. Per famiglia anagrafica si intende un insieme di persone legate da vincoli di matrimonio, parentela, affinità, adozione, tutela o da vincoli affettivi. I membri devono coabitare e avere dimora abituale nello stesso Comune (Decreto del Presidente della Repubblica 30/05/1989, n. 223, art. 4). La composizione della famiglia anagrafica risulta dallo stato di famiglia."

**Comment by ncapozzi** [comment]
@steps88  inoltre è spuntato un box che racchiude tutte le info e rende la pagina diversa da come trattiamo le precedenti, toglierlo per favore. -> è un problema di Chrome sulla VDC che non visualizza l'anteprima aperta. 
Dovreste avere questa opzione bloccata, provate con edge
![image](https://github.com/user-attachments/assets/1997c81d-3b0e-4643-886d-99c183f7e76e)

**Comment by steps88** [comment]
@ncapozzi **Intestatario scheda:** aggiungere una (i) informativa che apre modale “Aiuto” (per spiegare cosa significa) -> Possiamo aggiungere l'informativa nella pagina di **?Aiuto** già predisposta per la form

Quel che intendo è proprio di usare la (i) come CTA che apre la modale di aiuto, possibilmente nel punto in cui si parla di Intestatario scheda

**BOX**: non mi riferisco al box che mostra l'anteprima del pdf, quello ok. Mi riferisco al box attorno al contenuto proprio (titolo, dati, pdf) nelle schermate precedenti non è presente

**Comment by ncapozzi** [comment]
@steps88 tecnicamente possiamo posizionare la "i" come in figura tuttavia faccio notare che nel resto dell'area riservata la "i" attiva un tooltip e viene associata a singoli campi o listbox mentre qui abbiamo un elenco utenti in sola visualizzazione. Ci sarebbero altre alternative possibili, la pagina di ?Aiuto o il testo della form che ho indicato con la freccia. Comunque se vuoi facciamo come in figura con la i che attiva la modale
![image](https://github.com/user-attachments/assets/c02ad527-be30-4b6f-b846-8d4e2f328414)

**Comment by steps88** [comment]
Potrebbe essere un (?) che riprende quello di aiuto invece che la (i) - so che è un workaround..

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Verificate 
![image](https://github.com/user-attachments/assets/31616078-e149-483f-88ea-e59217f44f0b)
![image](https://github.com/user-attachments/assets/8158e55d-17b9-4eca-890f-08d5052fa342)
