### ISSUE TITLE
[AR] Le tue richieste

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#222]
- [x] Funzionalità “ordina per data”: mostrarla solo se ci sono richieste in più date diverse tra loro
- [x] Invertire data e chip [di pagamento]
- [x] Uso: spostare dopo Instestatario e Richiedente
- [x] Bottone "Dettaglio" > usare [link testuale](https://designers.italia.it/design-system/componenti/buttons/) invece del bottone primary
- [x] 🆕 aggiungere un sottotitolo di pagina

- [x] Potrebbe esserti utile + Approfondimenti > eliminare la fascia (già da wireframe) 
- [x] Quali sono i codici colore per le chips? [variano](https://designers.italia.it/design-system/componenti/chips/)? es. Pagamento in sospeso > arancio? avrebbe senso
 
<img width="770" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/737d4478-e50b-46e0-bbdc-2e3a9c7b1d8c">

**Comment by ncapozzi** [comment]
Bottone "Dettaglio" > usare link testuale invece del bottone primary
non possiamo prevedere un link al dettaglio perché a seconda dello stato, l’utente può fare azioni diverse. Quindi la decisione che è stata presa è quella di sostituire questo link, con i pulsanti azioni possibili sul tipo di stato in cui si trova la pratica. Non prevediamo un misto tra pulsanti e link, cioè quando disponibile dettaglio vediamo il link e negli altri casi pulsante… per uniformità manteniamo i pulsanti per ogni tipo di azione se siete d’accordo, altrimenti il link si vedrebbe solo per l’azione “Dettaglio”.

**Comment by ncapozzi** [comment]
Quali sono i codici colore per le chips? variano? es. Pagamento in sospeso > arancio? avrebbe senso
Attualmente le chips sono sempre blu, secondo me preferibile al multicolor

**Comment by steps88** [comment]
> per uniformità manteniamo i pulsanti per ogni tipo di azione se siete d’accordo, altrimenti il link si vedrebbe solo per l’azione “Dettaglio”.

Credo sia importante diversificare le azioni primarie e secondarie dal semplice "dettaglio" di una pratica, per questo mi aspetto di vedere diversi tipi di pulsanti, come già accade nel riepilogo della richiesta di un certificato (vedi screenshot). 
Ad es. 
- Scarica > primario 
- Invia a mail > primario outline
- dettaglio > Pulsante link 

Usare una serie di pulsanti visivamente uguali, appiattisce il layout e non crea gerarchia nell'importanza delle azioni.
<img width="466" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b7848ab6-3d51-490c-a6f1-bc2699db79f5">

Avevo già segnalato la necessità nella proposta di UI
<img width="1070" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/77269eff-49f6-4c06-9a9e-68af7241be91">

**Comment by steps88** [comment]
> Quali sono i codici colore per le chips? variano? es. Pagamento in sospeso > arancio? avrebbe senso
> Attualmente le chips sono sempre blu, secondo me preferibile al multicolor

Sono d'accordo, da design system:

> ### Rispetta i ruoli
> Ciascun colore della palette ha un ruolo e funzione specifica. Ad esempio, il **colore primario è associato a elementi di azione** mentre un colore **neutro è riservato a elementi di supporto o sfondi**. Il rispetto di questi ruoli assicura coerenza visiva e chiarezza nella fruizione dei contenuti.
> 
> ### Applica con parsimonia
> I colori contribuiscono alla creazione di una **gerarchia visiva** che **mette in evidenza ciò che è davvero importante** nel contesto della pagina. Non sono quindi elementi puramente decorativi, ma strumenti essenziali **per orientare e semplificare l'esperienza utente attraverso lo stimolo visivo**.

Non essendo elementi interattivo forse è più indicato il [badge](https://designers.italia.it/design-system/componenti/badge/)
<img width="559" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/fd82813f-0ac2-48ad-990f-f865a065dead">

A livello semantico accosterei:
- elementi andati a buon fine (conclusa, pagato) > badge success o primary 🟦
- elementi in sospeso > badge warning 🟧
- elementi in bozza > badge secondary ⬜️
- elementi NON andati a buon fine > badge danger 🟥

Se hai una lista di possibili stati possiamo definirli con più precisione

**Comment by ncapozzi** [comment]
Gli elementi utilizzati sono già di tipo badge
A seguire gli tati possibili delle pratiche e le azioni previste per ciascuno

CAMBIO RESIDENZA:
dichiarazione non ancora inviata al comune
- BOZZA: Modifica, Elimina ⬜️
- IN ATTESA DI CONVALIDA (componente maggiorenne che deve convalidare): Convalida 🟧
- IN ATTESA DI CONVALIDA (richiedente): Dettaglio, Elimina ⬜️
In tutti gli altri stati da quando il comune riceve la pratica (tranne SOSPESA): Dettaglio, Scarica.
- APERTA 🟦
- IN LAVORAZIONE 🟦
- IRRICEVIBILE  (NON andata a buon fine) 🟥
- ACCOLTA CON RISERVA 🟧❓
- SOSPESA: -> azioni Integra, Scarica 🟧
- INTEGRATA 🟦
- ACCOLTA DEFINITIVAMENTE (andata a buon fine) 🟩
- ANNULLATA (NON andata a buon fine) 🟥

Per ISCRIZIONE CITTADINI UE gli stati sono gli stessi del cambio di residenza tranne IN ATTESA DI CONVALIDA che non è previsto

RICHIESTA DI RETTIFICA:
- BOZZA: Modifica, Elimina ⬜️
In tutti gli altri stati da quando il comune riceve la pratica (tranne SOSPESA): Dettaglio, Scarica.
-	APERTA 🟦
-	IN LAVORAZIONE 🟦
-	IRRICEVIBILE  (NON andata a buon fine) 🟥
-	SOSPESA -> azioni Integra, Scarica 🟧
-	INTEGRATA 🟦
- 	EVASA  (andata a buon fine)🟩
-	RESPINTA  (NON andata a buon fine) 🟥

RICHIESTA CERTIFICATO: Dettaglio
- PAGATO 🟩
- PAGAMENTO IN SOSPESO 🟧

ISCRIZIONE LISTE ELETTORALI
- BOZZA: Modifica, Elimina ⬜️
In tutti gli altri stati da quando il comune riceve la pratica: Dettaglio, Scarica.
- APERTA 🟦
- IN LAVORAZIONE 🟦
- ACCOLTA DEFINITIVAMENTE (andata a buon fine)🟩
- RIFIUTATA (NON andata a buon fine)🟥

**Comment by ncapozzi** [comment]
Buongiorno, perchè se lo stato è lo stesso il colore è diverso?
CAMBIO RESIDENZA:
IN ATTESA DI CONVALIDA (componente maggiorenne che deve convalidare): Convalida 🟧
IN ATTESA DI CONVALIDA (richiedente): Dettaglio, Scarica, Elimina ⬜️

Avevo dimenticato gli stati per i certificati, che colori mettiamo?
RICHIESTA CERTIFICATO: Dettaglio
. PAGATO
.PAGAMENTO IN SOSPESO

**Comment by steps88** [comment]
Non mi è chiaro in attesa di convalida quale sia la differenza tra i due stati, non vedendo azioni di convalida nel richiedente non mi sembrava necessario l'arancio, ma se viene richiesta un'azione allora avrebbe senso
-> IN ATTESA DI CONVALIDA (richiedente): Dettaglio, Scarica, Elimina ⬜️ -> Il richiedente può  eliminare la pratica fino a quando anche solo uno dei maggiorenni coinvolti non ha validato.

Ho segnato con ❓quelli su cui ci stiamo confrontando internamente, e aggiorno la tua issue di partenza includendo i pagamenti così teniamo una sola reference
-> Se può essere utili ACCOLTA CON RISERVA rispetto al cittadino è come APERTA o IN LAVORAZIONE quindi userei ⬜️ anche in questo caso

**Comment by ncapozzi** [comment]
Manca la conferma dei colori delle chips

**Comment by ncapozzi** [comment]
Buonasera @steps88, manca sempre la conferma dei colori delle chips

**Comment by steps88** [comment]
@ncapozzi ho aggiornato i colori delle chips

Attenzione ad usare con coerenza il bottone Dettaglio: per il certificato è link testuale, per cambio residenza è bottone primary. > entrambi link testuali con freccia (come da proposta UI)
![Image](https://github.com/user-attachments/assets/06a2766f-6bc0-44e0-bb21-7f4ad47c792c)

**Comment by steps88** [comment]
Una nota: Hai bisogno di aiuto avrebbe bisogno dello sfondo per distinguerlo dal resto del contenuto

**Comment by steps88** [comment]
Aggiungo un punto alla descrizione della issue, per coerenza con le altre pagine: **aggiungere un sottotitolo di pagina**

**Comment by ncapozzi** [comment]
@steps88 quando ci fornirete i testi per favore indicate una frase da inserire

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
@ncapozzi la frase da inserire come sottotitolo è stata inserita nel file di testo da @gabripoggioli. Se inserire un placeholder valido la issue.
Come facciamo invece a validare i colori delle chips?

**Comment by steps88** [comment]
Non vedo avanzamenti

**Comment by ncapozzi** [comment]
@steps88 i punti che non hai ancora marcato sono
aggiungere un sottotitolo di pagina - > i testi li abbiamo avuti solo in questi giorni
i colorii delle chips -> sono stati già impostati impostati secondo le tue indicazioni, non ti risulta?

C'è qualche altra modifica che non trovi?

**Comment by steps88** [comment]
Non vedo riscontri con
 l'utenza di Margherita Hack, li vedo con Carla Matteoli 
![Image](https://github.com/user-attachments/assets/76765b78-9be7-4cd8-bf0a-a7b8affbecdd)
![Image](https://github.com/user-attachments/assets/df1d18d1-bdec-49fb-9a43-2b3bf92862d7)

**Comment by ncapozzi** [comment]
Buongiorno @steps88,
sembrerebbe che stai facendo i test in pre-produzione invece che in validazione dpval3.........dove avete fatto i test in tutti questi mesi. Puoi verificare per favore?

**Comment by steps88** [comment]
Corretto, chiudo la issue.
![image](https://github.com/user-attachments/assets/78e47769-1f3c-4716-986e-b40fb8dc14c5)
