### ISSUE TITLE
[AR] Autocertificazioni: scheda di servizio

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#224]
- [x] Quando è _fixed on top_, centrare il bottone "Ottieni autocertificazione" rispetto al box 
- [x] Rivedere la UI del sottotitolo di pagina, ad esempio come nel sottotitolo di pagina nell'area pubblica
- ~manca guida alla compilazione~ 

<img width="680" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/928a7841-2f36-417f-9f7f-361713e18ed9">
<img width="680" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/69b09f0b-604b-43e9-be38-d80bb36eeea5">

**Comment by ncapozzi** [comment]
manca guida alla compilazione: vista la facilità di utilizzo, la guida operativa non è mai stata prevista per le autocertificazioni (no bollo, no altra lingua). E comunque non sono documenti contrassegnati da qrcode e sigillo, non hanno scadenza e pertanto non vengono salvate sulla base dati, Il cittadino potrebbe anche scriversela a mano in autonomia

**Comment by steps88** [comment]
Verificato 
![Image](https://github.com/user-attachments/assets/c848ae00-42ae-42a6-b8a3-974007995f46)
![Image](https://github.com/user-attachments/assets/b0ed0304-8ad7-4798-babe-c415056ba6ac)
