### ISSUE TITLE
[AR] Autocertificazioni: flusso

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#225]
- Tra Documento e Riepilogo manca il controllo di compilazione dei campi: se non compilo non dà errore, se cancello uno dei 2 non dà errore > non sono obbligatori
- [x] [mobile] incolonnare i campi, non affiancarli
 
<img width="238" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/c2960c1b-5e04-4dbc-b98d-8e29b7da1cea">

- [x] Scarica l’anteprima: meglio usare bottone secondary outline > non c'è modo di evitare di scaricare il pdf ma incorporarlo o aprirlo in nuova scheda? collegato a  #221 
- [x] Eliminare linea grigia
- [Deprecata] [mobile] Bottone "annulla" lasciare solo icona (modificare cestino con “x”) ed eliminare testo <<annulla>> 
<img width="272" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/a141a954-7210-40b2-b6f6-6bf21a698d4d"> vedi #239 

### Riepilogo: 
- [x] Allineare in colonne separate i metadati e i dati dell’utente
- [x] Eliminare la fascia Potrebbe esserti utile + approfondimenti 
- [x] [mobile] ridurre spazio tra i due bottoni

<img width="269" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/e3d180bd-07ac-4c98-b438-0da3c6f411ea">

**Comment by ncapozzi** [comment]
Tra Documento e Riepilogo manca il controllo di compilazione dei campi: se non compilo non dà errore, se cancello uno dei 2 non dà errore-> gli estremi del documento non sono mai stati obbligatori (vedi anche i commenti alla issue 224)

**Comment by steps88** [comment]
Attenzione allo sfondo dell'alert che si vede bianco
![Image](https://github.com/user-attachments/assets/00e93848-f276-4e03-bbe8-f21668b0da60)


Verificato
![Image](https://github.com/user-attachments/assets/c11fffd3-5f3e-44d2-91d7-9d995ad6e007)
![Image](https://github.com/user-attachments/assets/34b2d837-1992-4b87-898c-32532d59e007)

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Verificata 
![image](https://github.com/user-attachments/assets/95a10144-8e31-4ad3-965f-0604e89951c2)
