### ISSUE TITLE
[AR] RETTIFICA: flusso - tab Carica allegati

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#229]
### Tab Carica allegati 

- [x] CTA Carica documento > secondary outline 
~Manca la sezione “Aiuto” e la frase relativa  Se hai bisogno di aiuto puoi consultare...~ [(vedi prototipo)](https://xd.adobe.com/view/67ef8b44-c93b-447a-a9fa-5f4040672a3a-32bc/screen/8e20fd65-2cb7-4c29-8652-fecaac741475/) 

MODALE ALLEGA FILE
- [x] Allega file > Il nome del pulsante a lato del campo dovrebbe essere "Seleziona file" e non Carica allegato, oppure l’icona lente d’ingrandimento 
- [x] [Mobile] il pulsante Avanti è solo testo e non button (come da desktop)
- [x] Sarebbe buona cosa ricordare i limiti dei file caricabili anche nella modale
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/5bbdea16-4ff7-4147-b673-3b66ecf72b5b)
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/b7d78e22-6ab0-4190-8c6a-f9008b4fba54)

**Comment by ncapozzi** [comment]
Manca la sezione “Aiuto” e la frase relativa Se hai bisogno di aiuto puoi consultare... -> nella form specifica non ci sono ulteriori informazioni da fornire oltre quelle già mostrate nel testo della form. In questo senso non sempre troverete ?Aiuto. Comunque per questo aspetto stiamo predisponendo i testi la dove occorre

**Comment by ncapozzi** [comment]
[Mobile] il pulsante Avanti è solo testo e non button (come da desktop) -> è stato realizzato come da prototipo mobile, potete specificare qual è il problema?

**Comment by steps88** [comment]
> [Mobile] il pulsante Avanti è solo testo e non button (come da desktop) -> è stato realizzato come da prototipo mobile, potete specificare qual è il problema?

Da desktop la gerarchia dei pulsanti è chiara, da mobile l'Avanti perde di importanza 
<img width="523" alt="image" src="https://github.com/user-attachments/assets/5b9e4c6e-b10d-4274-96d4-0e2e701f033e">
<img width="225" alt="image" src="https://github.com/user-attachments/assets/e7e33bdc-f4b2-4eee-aced-c8acd3127274">

Succede anche in altri punti, per esempio al riepilogo:
<img width="513" alt="image" src="https://github.com/user-attachments/assets/12941786-daf3-4d0c-98fc-4cfa54071f6d">
<img width="209" alt="image" src="https://github.com/user-attachments/assets/304a3d57-f92f-4ee6-a69e-13b34c5b0184">

**Comment by steps88** [comment]
![Image](https://github.com/user-attachments/assets/17d2e35c-baae-4e61-a725-f57324af4956)

**Comment by ncapozzi** [comment]
@steps88 con questa immagine vuoi dire che dobbiamo rendere "Seleziona file" Secondary outline?

**Comment by steps88** [comment]
No @ncapozzi l'immagine è per verificare i punti risolti

**Comment by anpr-opendata-team** [comment]
@steps88 issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Verificata per cambio di residenza

<img width="376" alt="image" src="https://github.com/user-attachments/assets/50811e68-fa2a-4b40-9604-0e981bd0fce0">

**Comment by ncapozzi** [comment]
@steps88 cosa manca per chiudere questa issue?
