### ISSUE TITLE
[v1] NOTIZIE: funzionalità filtro

### ISSUE THREAD

**Issue by Clou-dia** [teamdigitale/anagrafenazionale.interno.it-site#23]
Tendina dei filtri nella pagina notizie nativa. Inoltre vorremmo verificare la funzionalità dei filtri che sembra essere non funzionante

Chrome per mac <img width="873" alt="Schermata 2022-07-28 alle 16 32 54" src="https://user-images.githubusercontent.com/98462345/181551356-1e98b130-548e-4170-a38b-5285c2bf0f4a.png">

**Comment by fmilla74** [comment]
Utilizziamo le select native e la presentazione è gestita dal browser. Per la funzionalità di ricerca delle notizie, come anticipato nella mail di rilascio, sarà possibile verificarla successivamente su wordpress.

**Comment by steps88** [comment]
Confermo l'uso di select nativa per migliorare accessibilità e leggibilità. Per lo stesso motivo non è necessario avere un pulsante OK, come segnalato più volte durante la revisione dei mockup.

**Comment by fmilla74** [comment]
Come condiviso negli incontri, la presenza dell’OK garantisce sicuramente l’accessibilità in tutte le condizioni di utilizzo da parte di tutte le tipologie di persone con disabilità, 
Le verifiche su come garantire l’accessibilità senza OK sono da pianificare,  valuteremo nel corso del prossimo mese se riusciamo ad inserirle per il rilascio del 30 ottobre oppure per un rilascio successivo. 

Per quanto riguarda 
-	colore testo etichetta on top #435a70: questo colore non era tra quelli richiesti per il sito 

vedi mockup : https://xd.adobe.com/view/f9fd0853-8e58-4bcf-8eac-59e5a47481a5-acae/screen/747a8e62-27e0-4882-84e5-c4a487286e3e/specs/  
 
Vuoi che introduciamo un nuovo colore?

-	font-size etichetta on top 14px, non 18, con il Titillium per garantire una buona leggibilità del testo pensiamo sia meglio adottare 16px come da mockup 

Va bene?

**Comment by fmilla74** [comment]
@steps88 avrei bisogno di un ritorno su questi 2 punti per poter indirizzare le richieste per il rilascio del 30 agosto. grazie

**Comment by steps88** [comment]
colore: sì, aggiungiamolo
font-size: ok per i 16px

Per il pulsante OK: potreste specificare in che modo la sua assenza comprometterebbe l'accessibilità?

**Comment by fmilla74** [comment]
Per il pulsante OK senza l'ok l'utente cambierebbe i risultati nella pagina senza aver compiuto un'azione esplicita. Il bottone serve per evitare proprio che i cambiamenti di contesto non attivati dagli utenti possano disorientarli  (criterio di successo 3.2.1 3.2.1 e 3.2.2)

Inoltre queste due modifiche  sono una personalizzazione della select nativa e sarebbe preferibile non farle
- colore testo dentro la select #17324d
- font-size dentro la select 18px, non 20

Le altre le mettiamo nel prossimo rilascio

**Comment by steps88** [comment]
Ok per l'OK. 

con _dentro la select_ intendo nel campo input non aperto, non dentro la tendina aperta.. C'è un motivo per cui sarebbe preferibile non farle? 
l'accessibilità del colore su quello sfondo è verificata (AAA 13.12:1), mentre la dimensione del font a 18px è più che sufficiente sia desktop che mobile

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by fmilla74** [comment]
Nel rilascio trovi anche questa richiesta di modifica: il colore testo dentro la select #17324d e il font-size dentro la select 18px. Da un'ulteriore verifica è emerso che non c'erano controindicazioni a metterla in campo

**Comment by steps88** [comment]
Verificato
<img width="752" alt="image" src="https://user-images.githubusercontent.com/91465481/188099399-f2020941-fffb-4205-b0ed-860ae5314f84.png">
