### ISSUE TITLE
[AR] RETTIFICA: flusso - tab Riepilogo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#230]
### Tab Riepilogo

- [x] eliminare linea grigia e includere il contenuto in card (tipo Informativa privacy per intenderci)
- [x] correggere la gerarchia dei testi (h1, h2, h3..) tra titolo di pagina e anteprima della rettifica
- ~~Trattare il numero di pratica [come nel prototipo](https://xd.adobe.com/view/08903de2-9639-4cd8-aa69-2c5a71cb8125-5dc3/screen/80c75335-0af7-4c70-b333-86831a519156/)~~

![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/097a43b2-6f5a-41c6-814a-a1f4b39ab5f9)

**Comment by anpr-opendata-team** [comment]
@steps88 issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi
Il numero di pratica fa parte dell'anteprima riepilogo diversamente da quanto mostrato nel prototipo ed è incluso nel pdf che possono scaricare sia i cittadini che i Comuni

**Comment by steps88** [comment]
ok per il numero di pratica. La dimensione del testo all'interno dell'anteprima dovrebbe però essere inferiore a quella di "Riepilogo"

**Comment by steps88** [comment]
Verificato 
![Image](https://github.com/user-attachments/assets/0edd7498-dde6-4dd4-9467-c9a40f35a570)
