### ISSUE TITLE
[AR] CERTIFICATI AVVOCATI: contatti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#234]
Applicare le modifiche richieste per la pagina Contatti dei cittadino #218 
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/211f98dd-a6ea-46b8-b17c-74667ae9d6d1)

**Comment by anpr-opendata-team** [comment]
@steps88 issue completata da tempo, hai già chiuso anche #218 di riferimento. Non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Verificata
![image](https://github.com/user-attachments/assets/14a4b186-1505-4910-986c-232ac9f32c49)
