### ISSUE TITLE
[AR] CAMBIO DI RESIDENZA: scheda di servizio

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#235]
- [x] Alert di metà pagina > arancio e non grigio secondario 

- [x] Manca il modulo feedback  

- [x] [mobile] L'indice dei contenuti che si aggiorni in base al paragrafo in cui ci si trova con lo scroll
![image](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/96a690a5-15c2-45c4-9f01-767dc9fc8aa6)
<img width="357" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/07aa74f4-feb3-4a7b-9d11-b609001c1e81">

**Comment by ncapozzi** [comment]
Manca il modulo feedback -> nell'ambiente di test prima di fare login è necessario selezionare il link https://trawlpls01-01.srv.sogei.it/fdkUtente/js/bundle.min.js e accettare il certificato. Questo ovviamente non sarà necessario in produzione.

[mobile] L'indice dei contenuti che si aggiorni in base al paragrafo in cui ci si trova con lo scroll -> ci risulta già così

**Comment by steps88** [comment]
> [mobile] L'indice dei contenuti che si aggiorni in base al paragrafo in cui ci si trova con lo scroll -> ci risulta già così
DA MOBILE mi aspetto che l'aggiornamento sia visibile nel testo _esposto_, oltre che nel menu a tendina.
![ANPR AR titoloSezione](https://github.com/user-attachments/assets/f33fbb3d-7cc4-45c7-945b-b9e8fa1d9fc8)

Ok per il modulo feedback, ora lo vedo correttamente
<img width="1082" alt="image" src="https://github.com/user-attachments/assets/faaaf252-eff3-4aec-a1d6-eaf088f60d4c">

**Comment by steps88** [comment]
Manca solo il punto sull'indice dei contenuti mobile, si può fare?

**Comment by anpr-opendata-team** [comment]
@steps88 issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Verificato su tutte le schede di servizio 💖 
![ANPR AR indice contenuti_fix](https://github.com/user-attachments/assets/0c0e1305-259e-4fd6-9781-7e4456e1e198)
