### ISSUE TITLE
[AR] breadcrumb: solo pagina precedente

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#238]
da mobile, per evitare di avere breadcrumb molto lunghi, vorremmo lasciare solo il link alla pagina precedente.
Nell'esempio sarebbe "cambio di residenza"

<img width="376" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/54f34e7b-2a27-44c3-9129-8c0b9447267e">

**Comment by steps88** [comment]
Non vedo modifiche

**Comment by ncapozzi** [comment]
@steps88 possiamo rinominarli “Nuova residenza” e “Residenza in famiglia esistente”, va bene?

**Comment by steps88** [comment]
L'ultimo step del breadcrumb non è necessario sia visibile, è la pagina corrente, quella che si legge nel titolo. Dovrebbe essere tolta la homepage e lasciato solo "Cambio di residenza"
ovvero il livello superiore alla pagina corrente, in tutti i flussi, non solo questo

**Comment by ncapozzi** [comment]
@steps88 , abbiamo pensato che in alcuni casi anche lasciare solo il link alla pagina precedente potrebbe non risolvere il problema, considerate anche le traduzioni in altre lingue.
Nel caso specifico del cambio di residenza il link omonimo porterebbe alla scheda informativa, poco utile se hai già iniziato una bozza
Il suggerimento pertanto sarebbe togliere proprio il breadcrumb dalla versione mobile, tenuto conto che alla Home si può tornare cliccando sull'immagine di ANPR. Restiamo in attesa di riscontro.

**Comment by steps88** [comment]
Riteniamo sia più utile mantenere il breadcrumb ma solo con la pagina precedente, così da avere il primo ramo gerarchicamente utile a portata di mano.

Esempio: "**_Homepage_ > _Certificati_ > _Certificati anagrafici_** > Ottieni un certificato" diventerebbe solo "**_Certificati anagrafici_**" cliccabile

**Comment by anpr-opendata-team** [comment]
@steps88 issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Vedo riportata ancora la pagina corrente
<img width="376" alt="image" src="https://github.com/user-attachments/assets/f8892fd0-710f-4899-8427-ac1e346ab244">
<img width="376" alt="image" src="https://github.com/user-attachments/assets/b5831e5c-e971-4404-aa47-d4eb316ec601">

Il breadcrumb per Cambio di residenza dovrebbe poi rimanere con rimando alla scheda di servizio (vedi 2 immagine)

**Comment by ncapozzi** [comment]
@steps88 puoi verificare

**Comment by steps88** [comment]
Verificato 
![Image](https://github.com/user-attachments/assets/861f7b6a-cfaf-4c51-ac98-943da1514157)
![Image](https://github.com/user-attachments/assets/8179c633-2757-4593-b9a6-c515b8df84e1)
