### ISSUE TITLE
[AR] CAMBIO RESIDENZA: Tab Tipologia residenza

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#242]
Accorpo qui tutte le issue relative al tab Tipologia residenza, prima nella issue #236 
- [x] “Aiutami a scegliere” > primary **outline** 
- [x] #239 
- [deprecated] i pulsanti disabilitati dovrebbero essere grigi, non chiari opacizzati
- [x] [mobile] il pulsante Avanti è diverso da desktop
- [x] 🆕 Spostare **dopo la form** i pulsanti Avanti ed Annulla: sotto al wizard d'aiuto si perdono facilmente 
<img width="913" alt="image" src="https://github.com/teamdigitale/anagrafenazionale.interno.it-site/assets/91465481/3a417d51-9f6f-4fd1-82ce-f37308903766">

**Comment by ncapozzi** [comment]
Buonasera @steps88 la richiesta "i pulsanti disabilitati dovrebbero essere grigi, non chiari opacizzati", vuol dire che tutti i pulsanti, rossi, blu o bianchi che siano, quando sono disabilitati sono grigi!?

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by apuccisogei** [comment]
@steps88 ciao, dalle linee guida risultano opacizzati e non grigi. Potresti spiegare meglio la richiesta?

**Comment by steps88** [comment]
Risolta e verificato
![image](https://github.com/user-attachments/assets/0b24c639-7bec-4532-8bfe-2af2f4b73b2c)
