### ISSUE TITLE
[AR] Stepper interattivo: non chiaro che sia interattivo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#245]
Sarebbe meglio sottolineare il testo dello step a cui si può tornare indietro per indicare l'interattività dell'elemento e rendere ben evidente lo stato di _hover_

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Non vedo hover, dovrebbe sparire la sottolineatura, no?
![Image](https://github.com/user-attachments/assets/9c2c5f00-75cf-4583-a2ef-737bf5919a40)

**Comment by ncapozzi** [comment]
@steps88 puoi verificare

**Comment by steps88** [comment]
Non mi risulta 
![ANPR AR hover stepper 2](https://github.com/user-attachments/assets/98e46fd6-c43e-48d7-9cba-f5246c6ec1ae)

**Comment by ncapozzi** [comment]
Buongiorno @steps88,
sembrerebbe che stai facendo i test in pre-produzione invece che in validazione dpval3.........dove avete fatto i test in tutti questi mesi. Puoi verificare per favore?

**Comment by steps88** [comment]
Corretto, pardon. Issue verificata.
![ANPR AR hover stepper fix](https://github.com/user-attachments/assets/1798e39c-28a5-4a58-b130-716094b36ed2)
