### ISSUE TITLE
[AR] Iscrizione cittadino UE a LISTE ELETTORALI: stepper non interattivo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#247]
Lo stepper non risulta interattivo, dal tab riepilogo non posso cliccare al tab **Inserimento dati**

https://github.com/user-attachments/assets/896e0b66-beb8-4d36-89d7-9b35451baa2b

**Comment by ncapozzi** [comment]
@sguerra issue completata

**Comment by steps88** [comment]
Verificata ![Image](https://github.com/user-attachments/assets/b067bbd0-6b5e-4ff5-8d7d-a9ca6b5f9958)
