### ISSUE TITLE
[AR] ASSISTENZA: form e mobile

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#248]
- [x] Manca il titolo di pagina “Assistenza”
- [x] i campi risultano già in errore al primo accesso sul modulo
- [x] i dati personali risultano modificabili, perchè? dovrebbero essere letti dalla sezione Contatti ma non modificati @ncapozzi 
- [x] nel dropdown Ambito manca una sezione Altro e la voce “I miei dati” dovrebbe essere “I tuoi dati”, per coerenza con le voci di menu
- [x] quando presente, tenere l'opzione Altro come ultima della lista

MOBILE:

- [x] il layout non è responsive (vedi l'ampio margine destro)

![image](https://github.com/user-attachments/assets/ea31e95b-4912-417b-9b00-69175598d807)
![image](https://github.com/user-attachments/assets/470603b9-ef29-4f4a-a6db-acffcbb35b9e)

![image](https://github.com/user-attachments/assets/b0fb6551-0758-4741-b2d0-b1ad97b6dee2)

**Comment by ncapozzi** [comment]
i dati personali risultano modificabili, perchè? dovrebbero essere letti dalla sezione Contatti ma non modificati -in coerenza con gli altri servizi che prevedono una sezione contatti nella pratica dove vengono mostrati gli stessi dati del profilo utente, quando presenti, ma sempre modificabili.

**Comment by ncapozzi** [comment]
@steps88 nel dropdown Ambito manca una sezione Altro e la voce “I miei dati” dovrebbe essere “I tuoi dati”, per coerenza con le voci di menu -> La lista Ambito è stata di proposito caricata con i servizi disponibili per circoscrivere l'ambito appunto. Altro è previsto nella lista argomento per ogni ambito.

**Comment by steps88** [comment]
> i dati personali risultano modificabili, perchè? dovrebbero essere letti dalla sezione Contatti ma non modificati -in coerenza con gli altri servizi che prevedono una sezione contatti nella pratica dove vengono mostrati gli stessi dati del profilo utente, quando presenti, ma sempre modificabili.

La sezione Contatti permette di avere dei contatti **verificati**: se si dà all'utente la possibilità di modificarli _durante_ il flusso di servizio o l'assistenza, si perde questa verifica.
Per questo riteniamo sia meglio sì mostrarli per controllare la correttezza, ma di poterli modificare solo dalla sezione Contatti @ncapozzi

**Comment by ncapozzi** [comment]
@steps88 la decisione di renderli modificabili rispetto ai contatti era stata presa durante l'analisi dei requisiti del cambio di residenza e pertanto l'abbiamo sempre applicata anche ai servizi sviluppati successivamente.
Se ritenete che invece non debba più essere così, dobbiamo proteggere i contatti in tutti i servizi in cui vengono riportati a partire dal profilo utente corretto?

**Comment by steps88** [comment]
corretto

**Comment by anpr-opendata-team** [comment]
@sguerra issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Verificato 
![Image](https://github.com/user-attachments/assets/e8e43255-c97d-4156-96ae-a8a382415b13)
![Image](https://github.com/user-attachments/assets/ac1d0f83-bb25-4456-a251-7c22b458c510)
![Image](https://github.com/user-attachments/assets/f7127640-ddc2-4037-8e64-c9ace5ddcef1)
