### ISSUE TITLE
[AR] ASSISTENZA: allegati

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#249]
### Il caricamento degli allegati nn rispecchia il componente previsto del [design system (variante Trascina e rilascia](https://designers.italia.it/design-system/componenti/upload/)) 
che mostra il tipo di file e il peso (elementi da mostrare per accessibilità), e quindi porta a vari problemi:

- testo placeholder dentro il campo input > Seleziona il file
- una volta caricato il file il campo Descrizione è uguale al nome del file e se molto lungo porta la tabella a scrollare in orizzontale e nascondere la CTA di eliminazione
- [x] Se carico più di 3 file dovrebbe essere **nascosto**/disabilitato l'input per selezionare file successivi invece che lasciar selezionare il 4 file e poi mandare in errore

La richiesta è di implementare il corretto componente da design system

![image](https://github.com/user-attachments/assets/f39c6fc9-f3c3-4b93-9320-d78578f9c99d)

**Comment by steps88** [comment]
Sarebbe coerente mantenere lo stesso approccio ogni qual volta ci siano allegati da caricare, vedi #240 e #229

**Comment by anpr-opendata-team** [comment]
@sguerra issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Chiudo la issue ma la questione sul design system rimane aperta.
