### ISSUE TITLE
[AR] Le tue richieste: dettaglio

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#251]
Il breadcrumb della pagina non considera lo step **Le tue richieste**

Homepage > Le tue richieste > Dettaglio
![image](https://github.com/user-attachments/assets/ca43757b-0865-42e5-bae4-cbdff586f24f)

**Comment by anpr-opendata-team** [comment]
@steps88 issue completata, non posso cambiare lo stato "In stage" con questo utente
ncapozzi

**Comment by steps88** [comment]
Verificato ![Image](https://github.com/user-attachments/assets/9f9b61a2-c96c-4d45-892f-9f953ed9eade)
