### ISSUE TITLE
[v1] NUMERI: commenti generali stile di pagina - header footer floating button

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#26]
Allineare la grandezza dei **font**, il loro colore e le spaziature alle altre pagine del sito ANPR, rispettando la corretta gerarchia.

Ad esempio, "Distribuzione dell'utilizzo dei servizi*" dovrebbe essere gerarchicamente inferiore al titolo di pagina "I numeri"; così come i titoli dei grafici nelle card a partire da Certificati devono essere inferiori rispetto al titolo di sezione.

Per quanto riguarda le **spaziature** rendere omogenee le distanze tra una sezione di dati e l'altra, ad es. tra la fascia Certificati e Visura che ci siano almeno 48px.

**Colore di sfondo**: all'intro manca lo sfondino e lo sfondo nelle fasce non va bene grigio, vedere il Design system.

**Comment by steps88** [comment]
Vi chiedo di fare un passaggio coi vostri designer A.Palombi e F. Marini per allineare le grandezze dei font, colori e spaziature  a quelle delle altre pagine del sito.

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Rispetto al colore i titoli di pagina sono in #17324D e i sottotitoli in #5c6f82

Esempio pagina **Certificati** in validazione
![Image](https://user-images.githubusercontent.com/91465481/194623426-54f76ce6-ba2f-4005-900a-d0955742cc87.png)

e la pagina Numeri [da prototipo](https://xd.adobe.com/view/795688ab-94d7-4aec-a773-22f334023a67-2c05/) partiva da questa base, che dovrà essere resa stilisticamente coerente con quello nell'immagine sopra, Menu laterale compreso

![Image](https://user-images.githubusercontent.com/91465481/194623184-05ddec8b-e41c-4d53-999e-b18c49ea713d.png)

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
Verificato tutto il resto. 

### Mancano Header, footer e floating button:
Header deve diventare **sticky** quando scrolla la pagina, sia desktop che mobile
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/91465481/199957414-7c5da1c4-f206-4f8c-9459-c067a9911fe8.png">

Footer va impostato su 4 colonne, non 2. Da mobile si incolonna su 1 colonna sola.
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/91465481/199957529-62fa7efd-f0c8-40c4-9f4a-f6b28d98a035.png">

Va inserito il Floating button per tornare a top di pagina
<img width="74" alt="image" src="https://user-images.githubusercontent.com/91465481/199957960-ffb36983-9fcd-4fe4-80ad-22c86af2ab5f.png">

Da mobile sulla pagina numeri **NON** usare il fixed button "Accedi ai servizi" 
<img width="283" alt="image" src="https://user-images.githubusercontent.com/91465481/199958166-b368d419-c08c-43ec-8121-830b3670baea.png">
