### ISSUE TITLE
[v1] NUMERI: testo introduttivo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#27]
Di seguito il testo aggiornato:

### Conosci l'Anagrafe Nazionale attraverso la rappresentazione dei dati principali sull'utilizzo del portale e dei servizi anagrafici.

Da sapere: il conteggio della popolazione include i cittadini residenti in Italia e gli iscritti all’AIRE (residenti all'estero), in vita al momento della raccolta dati o della richiesta del servizio.

I [dati](url) sono disponibili in formato CSV e JSON su GitHub.
Ultimo aggiornamento: **gg/mm/aaaa**

**Comment by steps88** [comment]
Per chiarificare che si tratta solo di servizi offerti dal portale, modificare la frase:

Conosci l'Anagrafe Nazionale attraverso la rappresentazione dei dati principali sull'utilizzo **dei servizi anagrafici offerti dal portale.**

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Verificato
<img width="923" alt="image" src="https://user-images.githubusercontent.com/91465481/194635559-a8b9634d-ec87-493e-9683-e71097894b81.png">

Saranno da aggiornare i link a Github ora che abbiamo la repo degli open data

**Comment by steps88** [comment]
Il link a github è meglio si apra in nuova scheda, ora si apre nella stessa.

**Comment by steps88** [comment]
Ho fatto un passaggio tramite html usando come base la pagina Certificati e modificando solo i testi, così forse è più chiaro quello che intendo: 
<img width="996" alt="image" src="https://user-images.githubusercontent.com/91465481/198061465-f8f57d1d-b62c-4200-bf44-747c2cd95c59.png">

Dopo la riunione del 24/10 dobbiamo modificare leggermente il testo, vi daremo a breve specifiche cc @gabripoggioli

**Comment by cmigliardi** [comment]
che aggrega le richieste effettuate sul portale con quelle presentate direttamente ai Comuni.”    questa  la frase che Filippo ha concordato con Fabio

**Comment by steps88** [comment]
va bene, comuni con la C minuscola però

**Comment by steps88** [comment]
Quindi in totale così:

> 
> Ultimo aggiornamento: ####
> I dati sono disponibili in formato CSV e JSON su Github
>
> Da sapere:
> 
> - il conteggio della popolazione include i cittadini residenti in Italia e gli iscritti all'AIRE (residenti all'estero), in vita al momento della raccolta dati o della richiesta del servizio;
> - i dati riguardano le richieste effettuate sul portale, eccetto il servizio di cambio residenza, che aggrega le richieste effettuate sul portale con quelle presentate direttamente ai comuni.

**Comment by rfamiglini** [comment]
ciao @steps88, nel documento dei contenuti la C è maiuscola. Come procediamo?

**Comment by rfamiglini** [comment]
il documento dei contenuti dell'intero portale

**Comment by steps88** [comment]
Forse stai facendo riferimento ad un file non aggiornato, il più aggiornato è su Teams e prevede "comuni" con la c minuscola sempre, se ci sono errori vanno corretti.

**Comment by rfamiglini** [comment]
Sì, ci siamo chiariti. Grazie
