### ISSUE TITLE
[v1] NUMERI: persone in Anagrafe Nazionale

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#28]
- [x] Prima del grafico aggiungere la dicitura:

"I dati di seguito si intendono dall'avvio del servizio, salvo diversamente specificato"

- [x] modificare gli AIRE in: **di cui** 5.645.223 residenti all'estero (AIRE)
- [x] eliminare INFO

GRAFICO:
- [x] è possibile fare un test con ciambella come [qui](https://echarts.apache.org/examples/en/editor.html?c=pie-doughnut) MA senza tooltip E con i segmenti delimitati da spazi bianchi come [qui](https://echarts.apache.org/examples/en/editor.html?c=pie-borderRadius)? 
- [x] distanziare legenda dal grafico

<img width="550" alt="image" src="https://user-images.githubusercontent.com/91465481/184382866-4ceaf32e-8749-49b7-9030-d9ec52927736.png">

**Comment by anbatistini** [comment]
Quale di questi 2 grafici inserisco?
![test1](https://user-images.githubusercontent.com/51232022/187385918-144f47cb-5316-4200-998b-e51c50e73251.PNG)
![test2](https://user-images.githubusercontent.com/51232022/187385944-55b0ccb3-86e9-4b65-ac58-2bef85d2de6a.PNG)

**Comment by anbatistini** [comment]
considera l'animazione, passando il mouse, è la seguente in entrambi i tipi di grafico
![Immagine_animazione](https://user-images.githubusercontent.com/51232022/187388406-cb4fa9d3-3d18-4a32-ad05-841f1990627f.png)

**Comment by steps88** [comment]
la 2, che ha la linea bianca tra i segmenti e i bordi arrotondati 
![image](https://user-images.githubusercontent.com/91465481/187388894-aa58661c-1673-4ee7-9fb7-d3a305f2c60e.png)

**Comment by anbatistini** [comment]
potrebbe andare bene così?
![fix-grafico-torta](https://user-images.githubusercontent.com/51232022/190363989-f49e5d1c-4d4b-4fda-b049-758a58f76e2a.JPG)

**Comment by steps88** [comment]
Sì molto meglio!
questo aspetto è collegato alla grandezza dei font (#26) che ora sono molto grandi rispetto alle altre grandezze. Vi chiedo di allinearvi con i designer (A.Palombi e F. Marini) per avere indicazioni a riguardo.

**Comment by steps88** [comment]
Manca distanziare legenda dal grafico

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
lo vedo ancora uguale a prima: testo che si sovrappone al grafico e legenda molto vicina al grafico. 
la dimensione del testo in entrambe le card è ancora molto elevata (meglio averlo a 1.5 rem, come nelle altre card) <img width="574" alt="image" src="https://user-images.githubusercontent.com/91465481/194604421-9f8d0f70-8ba3-40bb-b341-84a091a57dab.png">

**Comment by steps88** [comment]
sia da **Firefox** che **Chrome**, la font Roboto si carica molto lentamente (potete fare una verifica?) e quando caricata gli elementi in legenda si sovrappongono. Per fugare ogni caso, è possibile spostarli uno sotto l'altro? Anche nelle risoluzioni intermedie prima di passare al mobile la legenda viene troncata (vedi 2 screen)
<img width="494" alt="image" src="https://user-images.githubusercontent.com/91465481/197511597-6260c31b-b186-4a87-b186-a2ede1c6973a.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/91465481/197512047-3a379878-5207-4255-b82c-6446eaa9d489.png">

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
Non vedo il fix da mobile, ne chrome ne firefox, la legenda manca 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/91465481/199956006-4626226c-5075-4db3-867d-7f2731c28990.png">

da destop sembra fixato 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/91465481/199956271-4e7414a9-e125-41ba-aaa7-6f58075383a5.png">
<img width="224" alt="image" src="https://user-images.githubusercontent.com/91465481/199956342-fc4f0d6c-744b-4a94-af17-11f053c481e0.png">

**Comment by steps88** [comment]
Verificata la versione mobile 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/201675478-02b6ef5d-7d87-4721-8909-9da8b0350f75.png">
