### ISSUE TITLE
[v1] NUMERI: persone che hanno usato almeno un servizio anagrafico

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#29]
- [x] Invertire l'ordine dei dati:    **15.112.879** | 24%
<img width="562" alt="image" src="https://user-images.githubusercontent.com/91465481/184383168-7c2494b6-fdfd-4722-9076-72290b204974.png">

- [x] eliminare l'info (i)

**Comment by steps88** [comment]
Dopo una consultazione interna , chiediamo di **rimuovere la %** in quanto non rappresentativa delle persone che possono effettivamente accedere ai servizi (considera anche persone che non possono effettivamente accedere come minorenni, disabili, carcerati, ecc)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Come per #28 la dimensione del titolo è meglio sia come nelle altre card, 1.5rem

**Comment by steps88** [comment]
Verificato desktop, mobile 
<img width="482" alt="image" src="https://user-images.githubusercontent.com/91465481/197512430-8fc589da-d6e6-438f-9059-459eb46f5b7d.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/91465481/197512616-096e9b11-2799-4a2a-9c3d-ecf04bfdfaa2.png">
