### ISSUE TITLE
[v1] HOMEPAGE: Header sticky-allienamento cta "accedi ai servizi"

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#3]
Nell'header sticky la cta "accedi ai servizi" è disallineata rispetto agli altri elementi. Rispetto al prototipo la dimensione è piccola, anche se mi sembra più elegante. Il problema si ripropone su tutte le pagine.
<img width="1423" alt="Schermata 2022-07-27 alle 09 13 48" src="https://user-images.githubusercontent.com/108679095/181184920-599c092e-934d-487d-8789-0f3cfcda76fe.png">
.

**Comment by fcassandra** [comment]
Avevamo già riscontrato il problema. A breve rilasciamo la fix.

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato 
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/91465481/185110443-492c0d6a-deb4-4d45-b37d-429850c0ad3f.png">
