### ISSUE TITLE
[v1] NUMERI: commenti generali stile dei grafici, filtro e incremento %

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#30]
- [x] usare Roboto Mono per i testi dei grafici (assi, legenda, etichette) 
- [x] usare delle **linee bianche** per separare gli elementi colorati (favorisce l' accessibilità)

- [x] spostare la **legenda** in basso e distanziata dal grafico (per non interferire con le tab in alto) 
- [ ] allontanare le etichette dell'asse x dall'asse stesso
- ~aumentare i **margini** sx-dx-top delle card dai testi, allineandoli all'ingombro del grafico~
- [ ] verificare le dimensioni dell'**icona ( i )** sia desktop che mobile (tappabilità) e il suo allineamento al titolo

- [x] spostare il **filtro temporale** sotto al titolo di sezione, ridurne la larghezza e aggiungere prima il testo "Visualizza:"
- [x] il filtro deve agire sul numerone, il grafico e l'incremento %
- [x] aggiungere un **testo dinamico** dopo il titolo del grafico, che riporta la selezione temporale con font più piccolo, in questo modo:  **Richieste totali certificati** | Ultimi 3 mesi
- [x] L'**incremento percentuale**: è calcolato come incremento mensile medio nel periodo di tempo selezionato; manca "%"; possibile aggiungere un tooltip che dice "incremento mensile medio nel periodo di tempo selezionato" ?

**Comment by anbatistini** [comment]
in relazione all'incremento se i dati fossero ad oggi il calcolo sarebbe: ((numero di certificati di agosto)-(numero di certificati di luglio))/(numero di certificati di luglio) , in tal caso il rischio è di avere un decremento in quanto il mese non è completo rispetto al precedente. Quindi come ci comportiamo?

**Comment by steps88** [comment]
> in relazione all'incremento se i dati fossero ad oggi il calcolo sarebbe: ((numero di certificati di agosto)-(numero di certificati di luglio))/(numero di certificati di luglio) , in tal caso il rischio è di avere un decremento in quanto il mese non è completo rispetto al precedente. Quindi come ci comportiamo?

Facciamo l'esempio di selezione temporale "**Ultimi 3 mesi**" con i dati aggiornati a ieri **21 agosto**. Il calcolo dell'incremento **medio** mensile sarebbe:
**incremento giugno:** (valore al primo del mese - valore all'ultimo del mese) / valore al primo del mese
**incremento luglio:** (valore al primo del mese - valore all'ultimo del mese) / valore al primo del mese
**incremento agosto:** (valore al primo del mese - **valore ad oggi**) / valore al primo del mese)

Sui 3 mesi quindi dovrò calcolare l'**incremento medio** dei 3 mesi: 
(incremento Giu + incremento Lug + incremento Ago) /3

Anche se parziale o negativo non ci si può fare molto, è la natura del dato, ma la media dovrebbe mitigare le situazioni in cui il dato è all'inizio del mese.

Torna @anbatistini ?

**Comment by anbatistini** [comment]
A questo punto però l'incremento non sarà più una percentuale ma bensì una media, e nel caso in cui mi trovassi a inizio del mese ( ad esempio al primo di agosto) l'incremento di agosto verrebbe 0 falsando la media seguente. Inoltre secondo me è un po' distorto come indicatore in quanto considera l'inizio a la fine dei mesi e non tutti i dati del mese.

**Comment by steps88** [comment]
Mmh, hai ragione. Credo che si possa risolvere considerando non il mese in senso stretto (1 agosto - 31 agosto) ma considerando i 30 giorni precedenti la data di consultazione del grafico. Perciò se oggi 23/8 scelgo di visualizzare gli "Ultimi 3 mesi" dei certificati emessi vedrò il totale dei certificati emessi riferiti ai 90 giorni precedenti.

Ho provato a simulare i dati, che è più facile spiegarsi. Prova a guardare [questo foglio](https://docs.google.com/spreadsheets/d/1VVKHKNCI_1tJnxjF66RqTucEzXFhh1o7/edit?usp=sharing&ouid=106638409466613095010&rtpof=true&sd=true) e vedere se ti torna il ragionamento. L'ipotesi è prendere in considerazioni dati ad inizio mese. 

Possiamo anche sentirci a voce che si fa prima a spiegarsi e ragionare insieme.

**Comment by anbatistini** [comment]
va benissimo, sono abbastanza libero nel pomeriggio, stabiliamo un orario e mando l'invito su teams

**Comment by steps88** [comment]
> va benissimo, sono abbastanza libero nel pomeriggio, stabiliamo un orario e mando l'invito su teams

Domani sono più libera, manda pure un invito all'orario che preferisci dopo le 11

**Comment by rfamiglini** [comment]
Per quanto riguarda la richiesta di portare i titoli dei grafici su una sola riga:
le dimensioni delle card sono standard su tutta la pagina, di conseguenza, l'unica soluzione è quella di diminuire il carattere dei titoli laddove vanno a capo. Questo comporterebbe però un disallineamento di carattere tra i vari titoli delle card.
Come procediamo?

**Comment by steps88** [comment]
I titoli delle card sono molto grandi ora, vi chiedo di fare un passaggio coi vostri designer (A. Palombi e F.Marini) per allineare le dimensioni, colori ecc a quelle utilizzate nelle altre pagine del sito (#26 )

Mentre per questa 

> aggiungere un testo dinamico dopo il titolo del grafico, che riporta la selezione temporale con font più piccolo, in questo modo: **Richieste totali certificati** | Ultimi 3 mesi

intendo proprio di accorparlo al testo del titolo, così che il titolo abbia più spazio e la posizione dell'elemento segua una logica di leggibilità. Ora sembra galleggiare.
Così per esempio:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/91465481/191433648-c7d5f2a7-f742-46fe-a4af-b948a10b6fe3.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/91465481/191434132-eb41b7bb-1f01-4071-8856-bb662e9561f0.png">

quest'ultima immagine spiega bene il concetto, manca però il cambio di colore (e dimensione possibilmente) sul testo, che è presente nella prima immagine

**Comment by rfamiglini** [comment]
@steps88 rilavoriamo i titoli di tutti i grafici

**Comment by steps88** [comment]
Avete un riscontro anche per 
- allontanare le etichette dell'asse x dall'asse stesso
- verificare le dimensioni dell'icona ( i ) sia desktop (15x21) che mobile (18x21 mi sembra davvero poco x essere tappabile) e il suo allineamento alla prima riga del titolo 
?

![Image](https://user-images.githubusercontent.com/91465481/194621501-b330782e-2e45-4e7d-bacd-3f941b8df8bd.png)

**Comment by steps88** [comment]
Aggiungo da SAL:

- [ ] togliere i tick dall'asse x
- [ ] arrotondare i numeri dentro il tooltip che si mostra all'hover sugli area chart e aggiungere il separatore delle migliaia

![Image](https://user-images.githubusercontent.com/91465481/194623914-1fa1ef1b-74c4-4ebf-bf59-c69a28cf9a93.png)

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
arrotondamenti effettuati 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/91465481/199954155-64639c3c-3cb6-42f0-b6fb-6c54ec7aae5f.png">
