### ISSUE TITLE
[v1] NUMERI: servizio più utilizzato

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#32]
- [x] nel titolo differenziare il colore della parola dopo i : 
- [x] 3 frase: Dall’avvio del servizio il 15/11/2021 
- [x] INFO: vedi documento [Content](https://docs.google.com/document/d/1yQf8jVmefMhAvUZ5v8QXDTGF1nuZ68GXrGl1fbQsTI8/edit#heading=h.mrs9tgd4eagu)

<img width="338" alt="image" src="https://user-images.githubusercontent.com/91465481/184392292-c76d617e-aac8-4184-b3b2-e2e98dff5694.png">

**Comment by cmigliardi** [comment]
io scriverei avvio e non lancio per uniformità e perché è un sito istituzionale

**Comment by steps88** [comment]
Il colore è singolo, da definire coi designer A.Palombi e F.Marini in coerenza con la revisione dello stile della pagina

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Non vedo differenze di colore

![Image](https://user-images.githubusercontent.com/91465481/194610687-46b1454e-6888-458e-bfe4-597ce7ec0393.png)

**Comment by steps88** [comment]
Verificato 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/91465481/198057691-2d707122-2a57-4ce1-b842-ed261fc98ca2.png"> <img width="334" alt="image" src="https://user-images.githubusercontent.com/91465481/198057842-cfeba3bc-7147-4949-869a-3a02acebd9ad.png">
