### ISSUE TITLE
[v1] NUMERI: Accessi totali ai servizi anagrafici

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#33]
- [ ] TITOLO: Accessi totali all’area Servizi anagrafici
- [x] INFO: Numero di persone che hanno effettuato l'accesso all'area
<img width="466" alt="image" src="https://user-images.githubusercontent.com/91465481/184397139-6ada90aa-39dd-4063-af93-efb212c0ff7e.png">

**Comment by steps88** [comment]
manca il primo punto

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Vedo il titolo ancora uguale, senza la parola ["all'area:"](https://docs.google.com/document/d/1yQf8jVmefMhAvUZ5v8QXDTGF1nuZ68GXrGl1fbQsTI8/edit#heading=h.x227px4xqq5s)
- Accessi totali ai Servizi anagrafici
- Accessi totali **all’area** Servizi anagrafici


![Image](https://user-images.githubusercontent.com/91465481/194611314-94bc2638-6ecb-464a-a7bc-31fd291a329f.png)

**Comment by steps88** [comment]
Verificato 
<img width="474" alt="image" src="https://user-images.githubusercontent.com/91465481/198062391-b0da4523-f904-408c-9869-e3606b508280.png">
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/198062224-a46017e9-4233-429e-bc9c-eec84e161c33.png">
