### ISSUE TITLE
[v1] NUMERI: Modalità di accesso ai servizi anagrafici

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#34]
- [x] Titolo: Modalità di accesso all’area Servizi anagrafici
- [x] mancano i : dopo il nome del provider > **SPID: 75%**
- [x] aggiungere "accessi" dopo il valore assoluto
- [x] INFO: Numero di accessi unici per tipologia

- [x] aggiungere i loghi se possibile 

<img width="522" alt="image" src="https://user-images.githubusercontent.com/91465481/184397455-b06faaa4-632a-49c8-8165-94fe7795e755.png">

**Comment by cmigliardi** [comment]
se fosse possibile,  dove posizioneresti i loghi?

**Comment by steps88** [comment]
Alla destra delle due righe di testo, allineato al centro e di conseguenza avere il testo con bandiera a sinistra. 
Per CNS non esiste un logo, ma potrebbe esserci l'icona di una tessera simile a questo: 

<img width="1168" alt="Screenshot 2022-08-22 at 11 46 24" src="https://user-images.githubusercontent.com/91465481/185897965-778aa4f6-6e6a-40de-ab2d-5dab8f5d32d0.png">

**Comment by cmigliardi** [comment]
ok logo a sinistra - attualmente nel portale esposto ci sono già i loghi, concordati con il DTD,  quando si accede ai servizi al cittadino - propongo di utilizzare gli stessi per agevolare i cittadini che già li conoscono

**Comment by steps88** [comment]
Ok per CNS usare lo stesso logo, ma aggiornerei quelli di SPID e CIE

**Comment by cmigliardi** [comment]
prima di fare l'intervento ti chiedo di consultarti al tuo interno perché  se ci chiedi questa modifica poi avrà  impatto anche sull'area pubblica al momento dell'accesso all'area riservata  che coinvolge altra UO di Sogei  -

**Comment by anbatistini** [comment]
Se una persona accede una volta con SPID e una con CIE in quale delle 2 va contata?

**Comment by steps88** [comment]
> Se una persona accede una volta con SPID e una con CIE in quale delle 2 va contata?

in entrambe

**Comment by cmigliardi** [comment]
ma l'utente è sempre lo stesso - poi rischiamo che se una persona usa 2 diverse modalità per usare 2 servizi la contiamo  volte - se una persona usa la stessa modalità per 2 diversi servizi la contiamo 1 sola volta. per questo obiettavo il fatto che all'inizio si era detto di conteggiare la fruizione ma poi ci hai chiesto  gli utenti UNICI -

**Comment by steps88** [comment]
Gli utenti unici sono da conteggiare rispetto alla modalità di accesso: se accedo una volta con SPID, una volta con CIE e una volta con CNS comunque è corretto essere contato 3 volte. 

L'obiettivo del contatore è vedere la differenziazione tra modalità di accesso, non la quantità di utenti che accedono..

**Comment by steps88** [comment]
Spaziare Allego anche qui i loghi da utilizzare 
![logo-CieID cerchio blu](https://user-images.githubusercontent.com/91465481/190377972-47182060-1156-46d3-9cc8-477eb7411b57.svg)
![logo-CNS cerchio blu](https://user-images.githubusercontent.com/91465481/190377990-ce8155e5-c655-436d-9510-1144c3270d3a.svg)
![logo-SPID cerchio blu](https://user-images.githubusercontent.com/91465481/190378014-694839eb-0951-41ea-95f6-1f980018855d.svg)

**Comment by steps88** [comment]
Verificato 

![Image](https://user-images.githubusercontent.com/91465481/192116406-0bf795d9-7b55-4489-bd0d-a52a20f29e45.png)
