### ISSUE TITLE
[v1] NUMERI: Certificati - richieste totali

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#35]
- [x] il titolo: Richieste totali di certificati 
- [x] INFO: Numero di richieste totali di certificati
- [x] vedi #30 

<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/184404160-bd96a3bc-a0fc-47a2-b9b6-81d77665ca7d.png">

**Comment by steps88** [comment]
- [ ] Utilizzare meglio lo spazio verticale del grafico

<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/190374360-4c83fdf5-1f52-42ab-8928-eac476b3cd02.png">

**Comment by steps88** [comment]
I pallini che sono stati aggiunti su questo grafico non rendono chiara l'informazione (la richiesta era di inserirli sui linechart con più di 2 aree)
Inoltre sull'asse y le migliaia sono trattate con la , invece che il punto (da controllare ovunque)
Vorremmo inserire il valore totale residenti+aire nel tooltip


![Image](https://user-images.githubusercontent.com/91465481/192116785-99d856b0-24e1-4152-af17-3b8cbfadedd9.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Non vedo smarcato questo punto 
- [Utilizzare meglio lo spazio verticale del grafico](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/issues/35#issuecomment-1247868519)


![Image](https://user-images.githubusercontent.com/91465481/194612417-565b263d-11be-4ef7-83cd-b7ad04bb4661.png)

**Comment by steps88** [comment]
Noto poi che l'area dei dati incompleti va oltre l'asse del grafico, mentre in riunione abbiamo visto che prendeva in considerazione il periodo da penultimo mese a ultimo mese.. corretto?

![Image](https://user-images.githubusercontent.com/91465481/194612973-058e078d-31b4-465a-b0c4-59ed5c16d9b2.png)

**Comment by steps88** [comment]
Come da riunione 24/10 aggiornare il titolo in **Totale certificati emessi** e usare l'intero ingombro della colonna, e non più affiancato a **Certificati emessi per tipologia di rilascio**

**Comment by steps88** [comment]
A questo punto direi di si, grazie del suggerimento

**Comment by rfamiglini** [comment]
Fix effettuate

**Comment by steps88** [comment]
Verificato 
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/91465481/199944202-6ba7961a-a57b-4a58-9b31-1757a0668fdc.png">
