### ISSUE TITLE
[v1] NUMERI: Certificati - Tipologia di rilascio

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#36]
- [x] Titolo: Certificati emessi per tipologia di rilascio
- [x] eliminare il numerone e il relativo incremento
-  ~aggiungere "in carta libera" dopo il numero~
-  ~manca il numero per i certificati con bollo + "con bollo"~
- [x] INFO: Numero di certificati emessi per rilascio in carta libera o con bollo
- [x] Legenda: **In** carta libera
- [x] vedi #30 

<img width="334" alt="image" src="https://user-images.githubusercontent.com/91465481/184405514-dbbe8327-ae83-405d-b37d-593b517a57d8.png">

**Comment by cmigliardi** [comment]
il totale è la somma di quelli emessi in carta libera e in bollo - non è corretto aggiungere "in carta libera" dopo il numero - semmai scriviamo la parola totale e poi un ci cui -  cosa ne pensi?

**Comment by steps88** [comment]
Da mockup il numero si riferiva a quelli "senza bollo" (in carta libera) e avevamo sottolineato la mancanza del numero "con bollo". 
<img width="398" alt="image" src="https://user-images.githubusercontent.com/91465481/185889430-120b7182-8212-4930-b168-e340ec878709.png">

Dovrebbe essere:
123.456 in carta libera     +2,3% 📈    | 123.456 con bollo  -1,5% 📉

**Comment by steps88** [comment]
Se vogliamo seguire l'approccio di grafici che hanno uno "spaccato" aggiuntivo rispetto a residenti/aire non dovremmo proprio esporre un numero nella fascia titolo, come avviene per: 
- Fasi di lavorazione Rettifica dati e Cambio residenza
- Fasi di lavorazione Cambio residenza
- Certificati più emessi [tra poco creo issue apposta – va tolto anche qui]

Non ce ne siamo resi conto fin dai mockup, tranne che per Certificati più emessi dove non era previsto (_vedi img_)

Propongo per evitare di creare differenze d'approccio direi di **levare il numero proprio e il relativo incremento**., andando ad evitare anche la situazione che descrivi sopra. Che dici?

<img width="531" alt="image" src="https://user-images.githubusercontent.com/91465481/185908487-c85a2920-d715-46ca-9395-a3bce829dd16.png">

**Comment by cmigliardi** [comment]
io adotterei una chiave di lettura del dato "uniforme"   è la sempre la miglior scelta verso il pubblico

**Comment by steps88** [comment]
Concordo, allora modifico la issue chiedendo l'eliminazione del numerone e del relativo incremento.

**Comment by anbatistini** [comment]
come colori per la distinzione tra "in carta libera" e "con bollo"  vanno usati gli stessi colori della distinzione tra residenti e AIRE  oppure il grafico va fatto con 4 diverse aree (residenti con bollo, residenti con carta libera, aire con bollo e residenti con carta libera) usando i 4 colori indicati sul mock up?

**Comment by steps88** [comment]
Come segnalato nella palette colori 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/91465481/186667576-a5750f24-0bea-45f9-a909-4e5c8fe012d7.png">

**Comment by steps88** [comment]
Al momento la vista complessiva del grafico è da correggere: mostra lo split nelle 4 categorie, ma dovrebbe esserci solo la divisione in carta libera/ con bollo, senza differenziare residente/aire visto che già presente nei tab
<img width="176" alt="image" src="https://user-images.githubusercontent.com/91465481/190376436-f17b4898-2606-4837-a2ce-bb46edcbb5ca.png">


<img width="382" alt="image" src="https://user-images.githubusercontent.com/91465481/190374959-3899ea18-c0d5-46ed-b6bb-cc7eb0ef24e1.png">

**Comment by anbatistini** [comment]
va bene, quindi le categorie tornano ad essere 2 su tutte e tre i tab?

**Comment by steps88** [comment]
MMH, si nel senso che non ci sarà mai la variabile dove ci sono 4 categorie.

TAB vista complessiva dovrebbe mostrare la divisione in carta libera/ con bollo dei dati sommati, aire+residenti > due colori, blu 1192e8 (tutti i certificati in carta libera aire+residenti) e verdone 005d5d (tutti i certificati con bollo aire+residenti). Non ci interessa in questa vista splittare i due numeri in sottocategoria aire e sottocategoria residenti, vogliamo vedere il dato aggregato per tipologia di rilascio

TAB residenti: divisione in carta libera/ con bollo **solo** dei residenti > colori: due sfumature di blu (06c e 4990d8)

TAB aire: divisione in carta libera/ con bollo **solo** degli aire > colori: due sfumature di rosso (9f1853 e b85a83)

Se non è chiaro, mandatemi una mail o scrivetemi su teams che ne parliamone a voce

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
<img width="573" alt="image" src="https://user-images.githubusercontent.com/91465481/194635370-79b5347f-8bc2-4cd2-902b-ff7c00b472dd.png">
