### ISSUE TITLE
[v1] NUMERI: Certificati - certificati più emessi

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#37]
- [x] titolo: **I cinque** certificati più emessi
- [x] eliminare il numerone e il relativo incremento
- ~dopo il numero: 130.403 "totale certificati" (la somma delle 5 tipologie nel tempo selezionato)~
- [x] INFO: Somma dei certificati più emessi, per frequenza. Per “certificato contestuale” si intende una richiesta che racchiude più di un certificato.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/91465481/184407377-529f1fd5-d739-46b3-8f9d-4ce9ff8feb47.png">

**Comment by steps88** [comment]
Aggiornato la issue: eliminare il numerone e il relativo incremento.

**Comment by steps88** [comment]
Verificato 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/91465481/190379968-ae471ac5-4108-4d3b-8175-55a98467e6e1.png">

**Comment by steps88** [comment]
È possibile togliere il "di" dalla legenda per quei certificati tipo Stato di famiglia e residenza?

**Comment by gabripoggioli** [comment]
@steps88 concordo nel togliere "di" dalla legenda, quindi:
- Contestuale
- Residenza
- Stato di famiglia
- Anagrafico di nascita
- Anagrafico di matrimonio

**Comment by steps88** [comment]
Refuso su Stato **DI** famiglia che è diventato Stato famiglia


![Image](https://user-images.githubusercontent.com/91465481/194613335-4ed7e875-12b4-4ec8-a673-503e8551e5e6.png)

**Comment by steps88** [comment]
Inoltre ora la legenda è molto più distante dal grafico, o il grafico si è avvicinato troppo ai tab. 
Prendere ad esempio le distanze di "Richieste di rettifica per stato di lavorazione"

![Image](https://user-images.githubusercontent.com/91465481/194613903-08e359d6-0d43-4078-aea2-42f9cf22c7b1.png)

**Comment by steps88** [comment]
Da sistemare in legenda: 
Refuso su "Stato **DI** famiglia" che è diventato "Stato famiglia"

**Comment by cmigliardi** [comment]
scusate ma  si chiama  
 
Certificato DI STATO DI FAMIGLIA

**Comment by steps88** [comment]
È rimasto l'errore nel tab AIRE
<img width="676" alt="image" src="https://user-images.githubusercontent.com/91465481/205628524-1421f016-ce37-472b-ac50-32c42a82786d.png">

<img width="591" alt="image" src="https://user-images.githubusercontent.com/91465481/205628424-8a368476-699e-4129-a469-f709435b65a4.png">

**Comment by steps88** [comment]
Correggere Stato **di** famiglia nel tab Aire

**Comment by steps88** [comment]
Corretto 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/91465481/207636651-1862eff1-5868-4ca9-a382-f6313fd5d847.png">
