### ISSUE TITLE
[v1] NUMERI: visura e autocertificazioni - fruitori del servizio 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#38]
- [x] titolo: Fruitori del servizio di visura
- [x] INFO: Numero di utenti unici che hanno consultato la visura dei propri dati anagrafici nel periodo selezionato
- [x] vedi #30 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/91465481/184839797-62eca046-afa1-4629-af9f-91ae4601ad43.png">

**Comment by cmigliardi** [comment]
cosa vuol dire numero di utenti unici?

**Comment by steps88** [comment]
che un utente viene contato una sola volta, anche se fa più accessi alla pagina

**Comment by cmigliardi** [comment]
perché contarlo una sola volta?  se accede più volte nel periodo vuol dire che è interessato

**Comment by steps88** [comment]
Se lo scopo è sapere quante persone usano il servizio è più corretto contare l'accesso unico

**Comment by cmigliardi** [comment]
ok

**Comment by steps88** [comment]
Meglio se l'etichetta per AIRE sia in testo rosso (e non bianco con contorno rosso). Se non è possibile, eliminiamo le etichette dal grafico, sono comunque presenti nel tooltip.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/91465481/190380894-87326149-1fc5-41a7-b4d0-af5f63374ae3.png">

**Comment by steps88** [comment]
Rettifico: **eliminare le etichette dalle barre,** in quanto in presenza di più elementi diventa tutto illeggibile

**Comment by steps88** [comment]
Test con utenti interni hanno sottolineato la difficoltà di lettura del grafico, chiedendo di **inserire il totale** invece che lo spaccato tra i due numeri


![Image](https://user-images.githubusercontent.com/91465481/192135063-10e46600-1208-40ce-81cc-cd3603395985.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato, Si è deciso di inserire il totale solo nel tooltip

**Comment by steps88** [comment]
Quando filtro tramite legenda però continuano ad esserci le etichette sulle barre
+ c'è un problema di disallineamento dell'area grigia


![Image](https://user-images.githubusercontent.com/91465481/194615144-6a417a52-6b73-44f9-ac93-217d53baa139.gif)

**Comment by steps88** [comment]
Su che base viene stabilita la scala dell'asse y? Se imposto dati dall'inizio del servizio, nessuno di questi arriva a 300.000, ultimo valore della scala. Dovrebbe adattarsi al valore max nel set di dati che si sta visualizzando, altrimenti viene compromessa la leggibilità dei valori più piccoli. Idem se filtro i residenti per vedere solo gli AIRE. 
Nel caso in cui filtro inoltre il tooltip mi mostra anche il totale dei due valori anche se ne sto vedendo solo uno.

https://user-images.githubusercontent.com/91465481/198076181-52a082e9-89d8-47f1-8627-d9fb173005d4.mp4

Etichette sulle barre tolte, verificato.

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
Verificato 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/91465481/199943596-56f19cb4-66cc-452f-97a5-a9fff28e596b.png">
