### ISSUE TITLE
[v1] NUMERI: visura e autocertificazioni - autocertificazioni richieste

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#39]
- [x] INFO: Numero di autocertificazioni richieste nel periodo selezionato
- [x] vedi #30 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/91465481/184841577-48b254a3-e5f8-42ae-afcc-bd66942d167e.png">

**Comment by steps88** [comment]
Anche per questo, vorremmo inserire l'etichetta del totale della barra invece che lo spaccato. Se non è possibile sulla barra, inserirlo come valore nel tooltip.

![Image](https://user-images.githubusercontent.com/91465481/192135108-f8f4b880-47c8-4960-b203-ce82504e6559.png)

**Comment by rfamiglini** [comment]
Ciao @steps88, per essere sicuri di aver capito:
nella vista complessiva, su ogni istogramma si vorrebbe il totale di aire+residenti piuttosto che la divisione dei due dati; il numero apparirebbe nella parte blu dedicata ai residenti per ragioni di spazio, va bene colorato sempre di bianco con contorni blu?
Nel caso questo non fosse possibile, aggiungiamo la dicitura "Totale:.." nel tooltip.
E' corretto?

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Come per #38 filtrando con la legenda le etichette rimangono visibili


![Image](https://user-images.githubusercontent.com/91465481/194615499-9b77fd72-447f-4381-bde1-73a521aff334.png)

**Comment by steps88** [comment]
Stesso problema di scala del grafico #38

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
verificato 

<img width="957" alt="image" src="https://user-images.githubusercontent.com/91465481/199942892-1ebca348-5d3a-47be-b619-d32dbb602ddc.png">
