### ISSUE TITLE
[v1] Homepage: icona sezioni numeri piccola

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#4]
L'icona di fianco al titolo "numeri" è leggermente più piccola rispetto alle icone delle altre due sezioni "Notizie" e "area tecnica".
Verificare la grandezza
<img width="489" alt="Schermata 2022-07-27 alle 09 20 24" src="https://user-images.githubusercontent.com/108679095/181186757-b4a756b3-23f6-4021-aa5c-e57e3155ff52.png">
.

**Comment by fcassandra** [comment]
Rilasciata versione con icona numeri di stessa dimensione delle altre icone

**Comment by steps88** [comment]
Verificato 
<img width="583" alt="image" src="https://user-images.githubusercontent.com/91465481/185111281-1358a2c0-5781-49b0-b2c2-930250526db0.png">
