### ISSUE TITLE
[v1] NUMERI: rettifica dati - richieste inviate

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#40]
- [x] Titolo: Richieste di rettifica dati in lavorazione
- [x] eliminare INFO
- [x] vedi #30 

Come da allineamento del 06/9 le richieste raggruppano tutte gli stati tranne _rifiutate_ e _irricevibili_

<img width="615" alt="image" src="https://user-images.githubusercontent.com/91465481/184842489-8d4f7d73-8395-4289-88c7-bd5487d53a99.png">

**Comment by cmigliardi** [comment]
le aperte o in verifica non sono ancora in lavorazione - l'ufficiale di anagrafe le potrebbe  rendere irricevibili e non mandarle mai in lavorazione

**Comment by steps88** [comment]
Avevamo concordato che tenevamo sotto il cappello "in lavorazione" tutto ciò che non è accolto, respinto o irricevibile. La parola giusta forse non è IN LAVORAZIONE, lascio a @gabripoggioli la palla per trovare la più corretta
<img width="734" alt="image" src="https://user-images.githubusercontent.com/91465481/184887770-4117a23f-db98-467f-8795-5908b0dbf85c.png">

**Comment by cmigliardi** [comment]
In lavorazione è lo stato specifico previsto dalla norma per individuare quelle che gli ufficiali di anagrafe stanno lavorando (possiamo allargare a quelle in lavorazione + le sospese + le integrate) - le aperte e quelle in verifica non sappiamo se  andranno in lavorazione.

**Comment by cmigliardi** [comment]
avevamo concordato che il titolo sarebbe stato:  Richieste di rettifica dati - senza specificare -

**Comment by steps88** [comment]
Forse potrebbe essere "Richieste di rettifica **ricevute**"? 
Ad ogni modo chiedo a @gabripoggioli se c'è un modo più consono di chiamarle (tenendo a mente che il cittadino non è a conoscenza degli stati previsti dalla norma) altrimenti lo lasceremo generico "Richieste di rettifica dati"

**Comment by cmigliardi** [comment]
il punto non è se cambiare il titolo,   il punto è dare un titolo coerente con la normativa e poi esporre un dato corrispondente a quel titolo

**Comment by cmigliardi** [comment]
per i titoli  e i testi in generale - come concordato siamo in attesa di  ricevere una convocazione da parte di Gabriella - grazie

**Comment by steps88** [comment]
![Image](https://user-images.githubusercontent.com/91465481/192117715-02da26a0-ebab-49d2-9fab-6f9c79d6f175.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Come in altri grafici, per **Ultimo anno** l'area grigia si disallinea 

![Image](https://user-images.githubusercontent.com/91465481/194615892-7320bf46-4ac0-4678-9dc8-95f23d751bf4.png)

**Comment by rfamiglini** [comment]
Fixato versione desktop

**Comment by steps88** [comment]
La fascia grigia sembra essere stata sistemata sia desktop che mobile
<img width="350" alt="image" src="https://user-images.githubusercontent.com/91465481/200886381-f7b03445-5234-4c17-b6a3-19f28cf351a6.png">
<img width="991" alt="image" src="https://user-images.githubusercontent.com/91465481/200887521-0de32c58-db18-4763-a402-16ec4ba77eb2.png">
