### ISSUE TITLE
[v1] NUMERI: rettifica dati - richieste di rettifica più frequenti

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#41]
- [x] sono da considerare le prime 10 voci, non 5
- [x] ordine decrescente
- [x] Trasformare la tabella in grafico, come [questo](https://echarts.apache.org/examples/en/editor.html?c=bar-negative2)  per ottenere un risultato simile a [questo](http://infogr8.com/wp-content/uploads/2015/09/The-Scale-of-Volkswagen-Crisis.png) 
- [x] TITOLO: Richieste di rettifica **dati** più frequenti
- [x] INFO: Tipologie di rettifica più richieste in ordine decrescente
- [x] vedi #30 
- [x] usare #0066cc come colore primario per le barre _(update)_
- [ ] allineare se possibile l'etichetta col numero in fondo a dx, sopra la barra _(update)_
- [x] aggiungere spazio dopo i ":" in alcune etichette (es. Residenza:Civico) _(update)_

<img width="523" alt="image" src="https://user-images.githubusercontent.com/91465481/184844292-00924501-0f40-4513-8e94-3f23ffb610f0.png">

**Comment by anbatistini** [comment]
Potrebbe andare come stile di grafico così? In caso quale colore posso usare?
![image](https://user-images.githubusercontent.com/51232022/186904125-eebc2ebe-889b-4d5c-b7a9-308e4208e93e.png)

**Comment by steps88** [comment]
Suggerivo l'uso di [questo con le etichette che si sovrappongono alla barra](https://echarts.apache.org/examples/en/editor.html?c=bar-negative2) per mantenere una buona leggibilità nel caso in cui siano molto lunghe. 
In alternativa suggerirei di spostare le etichette sopra la barra, [come nel secondo esempio.](http://infogr8.com/wp-content/uploads/2015/09/The-Scale-of-Volkswagen-Crisis.png)

**Comment by steps88** [comment]
Per quanto riguarda il colore, lo #06c dovrebbe andare bene

**Comment by steps88** [comment]
manca:
- TITOLO: Richieste di rettifica dati più frequenti
- INFO: Tipologie di rettifica più richieste in ordine decrescente
- usare #0066cc come colore primario per le barre

Aggiungo se possibile di allineare l'etichetta col numero in fondo a dx, sopra la barra

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Manca allineare l'etichetta del numero in fondo a dx, sopra la barra, in modo che siano tutte incolonnate. È possibile?

![Image](https://user-images.githubusercontent.com/91465481/194616442-560e5a87-6bdc-439b-8468-d6dab769785d.png)

**Comment by steps88** [comment]
La lunghezza della prima barra (il max value) dovrebbe coprire l'intera riga e non fermarsi prima. Da mobile le etichette vengono troncate.
<img width="436" alt="image" src="https://user-images.githubusercontent.com/91465481/198079553-989492fc-f5c9-4779-9edd-cb7dc317c41d.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/91465481/198079034-b92b1b56-b5cb-4306-b03f-e1eeb6d48d3d.png">

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
Non vedo la fix effettuata, la prima barra non prende l'intero 100% nè desktop nè mobile, inoltre il grafico scrolla orizzontalmente da mobile, così come i tab

<img width="981" alt="image" src="https://user-images.githubusercontent.com/91465481/199940862-6b0eab3f-b921-4d7b-9bb3-2dc09da05646.png">

![ANPR tab scroll bar](https://user-images.githubusercontent.com/91465481/199941066-13389e58-1826-4dd0-afb2-d487b5862859.gif)

**Comment by rfamiglini** [comment]
ciao @steps88 , provvediamo a riproporzionare le barre in modo che la prima prenda il 100% e le altre a seguire. Non mi è chiaro però in che modo deve essere visto il grafico in modalità mobile. Le barre devono necessariamente essere scrollate orizzontalmente altrimenti si troncano i numeri. Invece per i tab totale, residenti e aire come dobbiamo procedere?

**Comment by steps88** [comment]
Per i tab mi sembra che il container si fermi molto prima della larghezza della card, e che ci sia lo spazio adeguato per accomodare AIRE.. sbaglio? per cui non sarebbe necessario lo scroll orizzontale


<img width="367" alt="image" src="https://user-images.githubusercontent.com/91465481/199945391-a0aa5bc3-4e35-4dc7-a065-35806f4fd3f7.png">

Inoltre da mobile non possiamo pensare di mantenere gli stessi margini che usiamo su dektop, devono essere variabili. Ora vedo 2rem di padding quando ne basta 1

<img width="939" alt="image" src="https://user-images.githubusercontent.com/91465481/199947773-d5ca2b03-1fa4-4887-86e8-a2aafcc65829.png">

ottimizzando i margini laterali, anche i tab ottengono più spazio "usabile", e di conseguenza lo stesso grafico può avere una larghezza maggiore.

Se preferite lo vediamo insieme

**Comment by steps88** [comment]
Per il grafico: dovrebbe vedersi tutto all'interno della viewport e non scrollare. Mi vengono in mente 3 soluzioni per visualizzare le etichette-numeri:
- mandarle a capo, sotto l'etichetta-testo

> Permesso di soggiorno: numero di soggiorno 
> 1.842
> ▭▭▭▭▭▭▭▭▭▭▭

- tenerle vicine all'etichetta testo (più vicine di ora), e differenziare la prima in grassetto

> **Permesso di soggiorno: numero di soggiorno** - 1.842
> ▭▭▭▭▭▭▭▭▭▭▭

Così in presenza di etichette molto lunghe potrebbe comportarsi così:

> **Permesso di soggiorno: numero di**
> **soggiorno** - 1.842
> ▭▭▭▭▭▭▭▭▭▭▭

È perseguibile una di queste strade?

**Comment by rfamiglini** [comment]
ciao @steps88, siamo riusciti ad allineare i tab in modalità mobile, levando così lo scroll orizzontale.


Purtroppo non è possibile riproporzionare le barre in modo che la prima prenda il 100% e le altre a seguire: la libreria si gestisce automaticamente a seconda di una scala; nella foto in allegato abbiamo aggiunto la scala di riferimento per rendere di più l'idea. In particolare non appena il valore utilizzato supera la cifra tonda, la scala aumenta (es. da 17.239, la scala va automaticamente a 18.000).
![lunghezza-barre](https://user-images.githubusercontent.com/88545256/200009922-ec57b229-2144-49c1-b3b4-a10a855977ef.JPG)


Il fatto di accorciare la distanza tra nome e numero non risolve il problema. In modalità mobile, come puoi vedere dalla foto, il dettaglio rimane troncato, in alcuni casi la stringa in altri il numero. Proponiamo di lasciare lo scroll orizzontale.
![stringa-barre](https://user-images.githubusercontent.com/88545256/200010200-39f5a746-27f0-4426-bb4f-0aa43f7cf1f5.JPG)

**Comment by steps88** [comment]
Inserito la griglia con etichette alla base del grafico 
<img width="968" alt="image" src="https://user-images.githubusercontent.com/91465481/201682051-e6732626-b17c-463f-96cc-516474b2419c.png">

Inserito la troncatura delle etichette quando in versione mobile, ed etichetta completa al tap
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/201682311-f6949336-ce79-4811-9b48-7b78e800bb0b.png">
