### ISSUE TITLE
[v1] NUMERI: rettifica dati - Fasi di lavorazione delle richieste di rettifica

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#42]
- [x] Titolo: Richieste di rettifica per stato di lavorazione
- [x] INFO: Numero di richieste di rettifica per stato di lavorazione nel periodo selezionato
- [x] vedi #30 
- [x] [palette colori:](https://miro.com/app/board/uXjVONM87r0=/?moveToWidget=3458764531178122130&cot=14) categorica

<img width="660" alt="image" src="https://user-images.githubusercontent.com/91465481/184845487-648021f1-75fc-4bc6-9342-a9a8c0e70cbf.png">

**Comment by cmigliardi** [comment]
io metterei per stato di lavorazione nel titolo è più immediato per un profano

**Comment by steps88** [comment]
![Image](https://user-images.githubusercontent.com/91465481/192134911-410c7fdf-c77d-41aa-a53d-7beaa433aae3.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Disallineamento area grigia quando vedo Ultimo anno
![Image](https://user-images.githubusercontent.com/91465481/194616894-d2654906-7792-4327-bc90-d4437cd4185b.png)
