### ISSUE TITLE
[v1] NUMERI: residenza

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#43]
- [x] Titolo sezione: ~Cambio di residenza~ Cambio di residenza
- [x] vedi #30 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/91465481/184846806-8d2178e5-7d9c-45a4-81b0-d77c8bfa8a3a.png">

**Comment by cmigliardi** [comment]
si era deciso Titolo: Dichiarazioni di cambio di residenza - (vedi resoconto)

**Comment by steps88** [comment]
![Image](https://user-images.githubusercontent.com/91465481/192134365-3484f31b-445b-403e-89cb-247947ac3b63.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Verificato

![Image](https://user-images.githubusercontent.com/91465481/194617133-4ee6c1a7-5277-4050-950d-06ae3eab0826.png)
