### ISSUE TITLE
[v1] NUMERI: residenza - dichiarazioni di cambio residenza

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#44]
- [x] titolo: Dichiarazioni di cambio di residenza
- [x] eliminare INFO
- [x] vedi #30 

<img width="285" alt="image" src="https://user-images.githubusercontent.com/91465481/184847604-5dc053da-6f7f-4f6c-82dd-6624e0101b2d.png">

**Comment by steps88** [comment]
![Image](https://user-images.githubusercontent.com/91465481/192134237-967ee184-206d-4228-be20-bc5ccb1e587e.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
L'ingombro totale della card è sproporzionato rispetto al grafico stesso: c'è molto bianco sopra al grafico, tra il testo Legenda interattiva e il margine della card. Può essere ridotto

![Image](https://user-images.githubusercontent.com/91465481/194617357-0d9ae029-7973-406b-be72-b5f4f0a03c75.png)

**Comment by steps88** [comment]
da mobile la legenda si appiccica al grafico, tab in scroll orizzontale non uno sotto l'altro, dati incompleti oltre l'asse x
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/198080178-6b666d9e-b2fb-4b4a-b5d7-9594e5c9bd6d.png">
<img width="916" alt="image" src="https://user-images.githubusercontent.com/91465481/198080119-5eb0e56a-7d4b-4913-afcf-4298ecdcf44b.png">

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/91465481/199939946-d50fa558-2ddf-468f-a6e3-68dc15297ba5.png">
<img width="335" alt="image" src="https://user-images.githubusercontent.com/91465481/199939974-04682803-b6b3-410c-b5f1-95a280497da8.png">
