### ISSUE TITLE
[v1] NUMERI: residenza - Fasi di lavorazione di cambio residenza

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#45]
- [x] dargli più spazio: fare in modo che stia da solo e non affiancato ad un altro
- [x] Titolo: Dichiarazioni di cambio residenza per stato di lavorazione
- [x] eliminare INFO
- [x] vedi #30 

<img width="282" alt="image" src="https://user-images.githubusercontent.com/91465481/184847790-f21f8632-389d-4303-973b-69cdf206d986.png">

**Comment by anbatistini** [comment]
dalla pallette dei colori  ci sono 5 colori per 4 fasi di lavorazione posso usare i primi 4 colori?

**Comment by steps88** [comment]
Sì, l'importante è che tra i due grafici dove ci sono le fasi corrispondano

**Comment by steps88** [comment]
![Image](https://user-images.githubusercontent.com/91465481/192134824-0dd4fbf4-3735-49ee-8fc8-38cf538e67cb.png)

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Anche qui lo spazio sotto alla scritta Legenda interattiva può essere ridotto 

![Image](https://user-images.githubusercontent.com/91465481/194617859-a6411b89-7dc3-4ee1-af03-f16337237302.png)

**Comment by steps88** [comment]
Da mobile la legenda è appiccicata al grafico
<img width="373" alt="image" src="https://user-images.githubusercontent.com/91465481/198081984-bfe7bde8-33fe-43c7-a1e3-a19deb947f30.png">

**Comment by rfamiglini** [comment]
Fix effettuata

**Comment by steps88** [comment]
Verificato 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/91465481/199933741-3c615483-e0c3-450a-aee6-f7068b416018.png">
<img width="279" alt="image" src="https://user-images.githubusercontent.com/91465481/199934102-c517f54d-7257-4311-ab50-66a12efbd741.png">
