### ISSUE TITLE
[v1] NUMERI: residenza - tipologie di cambio residenza

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#46]
- [x] I tab non servono, è un grafico unico
- [x] dargli più spazio: fare in modo che sia singolo e non affiancato ad un altro grafico
-  ~si può inserire anche il dato sugli espatri Italia > estero @cmigliardi ?~ Non è previsto dal servizio
- [x] titolo: Tipologie di cambio di residenza
- [x] INFO: Numero di dichiarazioni di cambio di residenza ricevute nel periodo selezionato per tipologia: all’interno dello stesso comune, all’interno della stessa regione, tra regioni diverse e rientri in Italia dall’estero (AIRE).

<img width="610" alt="image" src="https://user-images.githubusercontent.com/91465481/184852763-85110365-d28d-4f7b-af97-957602d1461f.png">

**Comment by cmigliardi** [comment]
perché adesso i tab non servono? come facciamo a dare una corretta rappresentazione in un unico grafico?   il servizio esposto non prevede  il caso di espatrio.

**Comment by steps88** [comment]
i tab non servono perchè i cittadini AIRE sono mappati all'interno della categoria "rientri in Italia" presente nella vista complessiva

**Comment by cmigliardi** [comment]
OK

**Comment by anbatistini** [comment]
Il grafico va bene questo oppure occorre usare quello a cui si fa riferimento sul mock up su miro(https://echarts.apache.org/examples/en/editor.html?c=themeRiver-basic) ? A mio parere la tipologia di grafico usata adesso permette all'utente di confrontare i numeri delle varie tipologie di cambio di residenza più facilmente.

**Comment by steps88** [comment]
va bene quello usato

**Comment by steps88** [comment]
Verificato 
![Uploading image.png…]()
