### ISSUE TITLE
[v1] NUMERI: residenza - flussi di persone nel cambio di residenza

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#47]
**vorremmo provare a percorrere la strada dove anche a destra ci sono le regioni. Più spazio e l'interattività nativa della libreria dovrebbero agevolarne la leggibilità. È possibile?** 

- [x] dargli piu spazio: fare in modo che sia singolo e non affiancato ad un altro grafico, aumentare l'altezza
- [x] Non sono necessari i tab (AIRE sono già inclusi in flusso "Estero")
- [x] Titolo: Spostamenti di residenza
- [x] INFO: Numero di dichiarazioni di cambio di residenza aggregate per regione di partenza e area di arrivo. La regione di partenza degli AIRE è identificata come “Estero”. 
- [x] [palette colori continua ](https://miro.com/app/board/uXjVONM87r0=/?moveToWidget=3458764531178122130&cot=14)per le regioni, tranne AIRE / Estero, segnalati con colore specifico (vedi Miro)

<img width="617" alt="image" src="https://user-images.githubusercontent.com/91465481/184852985-67d8f63b-8f58-4a14-bdac-d2ca02f57b2a.png">

**Comment by steps88** [comment]
Per vedere solo i rientri AIRE si può andare in hover sul flusso "Estero", per questo non è necessario il tab.

Visto che il grafico a queste dimensioni non sembra nè leggibile nè usabile – perciò la richiesta di dargli più spazio – ci chiedevamo se a dimensioni maggiori non valga la pena vedere le regioni a destra. 
Capisco che si rimetta in discussione una fascia già stabilita "su carta", ma alcune cose non si possono sapere fino a che nn si testano, e i dati li avremmo a disposizione, è un peccato non valorizzarli.

**Comment by cmigliardi** [comment]
Il tab lo lascerei per uniformità di lettura/approccio con gli altri grafici.  che il grafico non fosse nè leggibile nè usabile lo sapevamo già. a tale scopo avevamo concordato di alleggerirlo sulla destra raggruppando per nord/centro/sud questo comporta:  una maggiore chiarezza -  da ogni settore di sinistra escono al massimo 3 linee  -  si vede chiaro lo spostamento e il rientro in Italia suddivisa in zone. I  dati di produzione erano noti, li avevamo già estratti proprio allo  scopo di valorizzarli e di trovare la soluzione più  idonea -  erano  disponibili già in sede di ragionamento nei mesi scorsi

**Comment by steps88** [comment]
L'approccio dei tab non è necessario dal momento che abbiamo il flusso ESTERO _incluso_ nella colonna di sinistra, ovvero dei luoghi di partenza. 
Per mantenere coerenza con l'uso e l'approccio dei tab negli altri grafici, la vista tab-AIRE dovrebbe avere come luoghi di partenza gli **Stati** di residenza. Se vogliamo fare così per me va più che bene, stiamo però dicendo due cose diverse.

Mi sembra una buona semplificazione eliminare i tab e vedere AIRE nella vista complessiva come un unico flusso (senza perciò sapere gli Stati di partenza) come è stato realizzato infatti nel mockup, considerato che il tipo di visualizzazione è già ricca.

----
Per quanto riguarda i dati non abbiamo ragionato sulle estrazioni effettive, ma non importa, la issue è stata creata per capire se c'è margine per fare test stando nelle tempistiche definite.

**Comment by cmigliardi** [comment]
probabilmente non mi sono spiegata. dicevo solo che poter cliccare AIRE avrebbe agevolato nel vedere in evidenza il rettangolo ESTERO. tutto qui. chiaro che non voglio esplodere gli stati. ok togliamo i tab.  resta da capire perché adesso si cambia da quanto  concordato sulla  destra Nord-centro-sud proprio per dare leggibilità e tipo di spostamenti -

**Comment by steps88** [comment]
La modifica richiesta è di dare più spazio al grafico realizzato regioni-aree [v1], dandogli l'ingombro di tutta la colonna. E questa è l'opzione concordata. 

La richiesta secondaria – se vogliamo considerarla CR (change request/cambio requisiti) –  è di fare una v2, sempre usando l'ingombro di tutta la colonna, dove anche a destra si esplodono le regioni. 

Per la prima non dovrebbero esserci impatti sulle tempistiche; valutate invece quanto servirebbe per la 2 versione.

**Comment by steps88** [comment]
![Image](https://user-images.githubusercontent.com/91465481/192134509-e6f2503a-0f1f-4774-af76-f6d9c72c558b.png)

**Comment by steps88** [comment]
Accorgimenti:
- è possibile fare in modo che l'ordine degli elementi sia per valore decrescente? sia sulla colonna destra che sinistra
- è possibile evitare che si possano spostare i flussi?
- è possibile inserire un'etichetta sopra ogni colonna "Partenza" e "Arrivo"?

NEL TOOLTIP:
- sostituire "area" di arrivo con "regione" di arrivo

**Comment by steps88** [comment]
- Le etichette di colonna sono ancora molto grandi, ed entrambe disallineate. 
- Dopo il sal del 24/10 nel tooltip **l'ultima frase** va aggiornata così:
_"Gli AIRE sono identificati con l'etichetta "Estero", sia come espatri che rimpatri."_
<img width="895" alt="image" src="https://user-images.githubusercontent.com/91465481/198083149-0667c0fc-1973-4b6f-8b54-4567eeb082b2.png">

**Comment by rfamiglini** [comment]
@steps88, per essere sicuri di aver capito: la prima vista che intendi è quella che allego, è corretto? Si vuole mantenere comunque lo scroll orizzontale per leggere i nomi delle regioni?

[spostamenti_residenza.pdf](https://github.com/teamdigitale/anagrafenazionale.interno.it-site/files/9878283/spostamenti_residenza.pdf)

**Comment by steps88** [comment]
sì intendo quella vista, correggendo però la visualizzazione delle etichette a dx che vengono troncate

**Comment by rfamiglini** [comment]
Dopo varie prove, abbiamo dedotto che: il testo troncato è un problema della libreria, se si vuole leggerlo tutto non può entrare nella viewport in modalità smartphone,  per cui l'unica possibilità è quello di tenere il testo scorrevole

**Comment by Clou-dia** [comment]
inserisco anche qui soluzione per legenda 

Scala valori
min = 1     max = 97.047

@steps88

**Comment by cmigliardi** [comment]
ok modifica apportata

**Comment by steps88** [comment]
@cmigliardi non vediamo le modifiche specificate su Teams. Le riporto anche qui: preferiamo cambiare il titolo della legenda da "N° spostamenti" a "**Scala valori**" (in grassetto), evitare i riferimenti grafici (le due lineette a sx) e lasciare scritto min e max, come sotto:
 
**Scala valori** 
min = ###
max = ###

**Comment by steps88** [comment]
Verificato 
Il valore minimo del flusso è davvero 1? o l'avete hardcodato?
<img width="839" alt="image" src="https://user-images.githubusercontent.com/91465481/205627953-78ead364-e30c-4d68-8eb5-4bdccac8479a.png">

**Comment by steps88** [comment]
*min* deve essere un valore dinamico, ovvero il minimo valore presente nei dati
