### ISSUE TITLE
[v2] CERTIFICATI: tabelle - formattazione e ordinamento colonne 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#48]
- [x] Il titolo del file va in bold e manca l'icona come da [prototipo](https://xd.adobe.com/view/d9f96475-2b59-4a60-b3ad-aa3aa9a406b2-8caa/screen/1a202033-84d0-49dd-8e0c-c0f9937127e8)
- [ ] rendere le colonne (tranne Note) ordinabili 0-9 o A-Z, a seconda del contenuto 
- [x] nella versione mobile della tabella ottimizzata, usare il blu #06c solo per i link

<img width="941" alt="image" src="https://user-images.githubusercontent.com/91465481/185140588-0ed63b36-f51e-49a8-b99c-fe2e2f4b106c.png">

Prototipo
<img width="834" alt="image" src="https://user-images.githubusercontent.com/91465481/185140947-4b819765-7b8b-4efe-9058-1ff384a0f428.png">

Mobile
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/185142078-937842d5-bed1-4665-b4fd-472f3ae9a562.png">

**Comment by fmilla74** [comment]
Vorremmo sapere quale delle 2 tabelle volete adottare nel sito, potreste darci questa indicazione?

Ok per il bold al nome del file e il blu solo per i link nella versione mobile

Per quanto riguarda queste segnalazioni:

- rendere le colonne (tranne Note) ordinabili 0-9 o A-Z, a seconda del contenuto

Nel corso dell’analisi era emerso che altre tipologie di ordinamento non sarebbero state utili per rintracciare il file di interesse visto che è l’id che lo identifica. Al momento non abbiamo previsto lo sviluppo di questa funzionalità. 
Se ritenete debba essere prevista analizziamo l’impatto per introdurla.

- manca l'icona come da [prototipo](https://xd.adobe.com/view/d9f96475-2b59-4a60-b3ad-aa3aa9a406b2-8caa/screen/1a202033-84d0-49dd-8e0c-c0f9937127e8)

Nella revisione del prototipo per lo sviluppo abbiamo optato per una tabella più semplice, senza icone vista già la presenza dell’estensione del file.

**Comment by steps88** [comment]
> Vorremmo sapere quale delle 2 tabelle volete adottare nel sito, potreste darci questa indicazione? 

userei "Tabella ottimizzata per smartphone" per il mobile e "Tabella" per il desktop A MENO CHE si riesca ad  allineare lo stile di "Tabella ottimizzata per smartphone" nella vista desktop a quello di "Tabella"

Noto ora però che nel mobile di "Tabella ottimizzata per smartphone" manca il nome della colonna "codice" alle prime righe, mentre per "Tabella" non si vedono i nomi delle colonne.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/186425529-73cf729c-39df-484b-8dac-34fe1a7ab016.png">

Per le **colonne ordinabili** se ci fate sapere che impatto avrebbe introdurre questa feature, valutiamo se confermarla o meno, grazie

**Comment by fmilla74** [comment]
si può  allineare lo stile di "Tabella ottimizzata per smartphone" nella vista desktop a quello di "Tabella".

**Comment by steps88** [comment]
Non vedo modifiche lato desktop, mentre da mobile vedo il contrario di
> si può allineare lo stile di "Tabella ottimizzata per smartphone" nella vista desktop a quello di "Tabella".

Per chiarezza, il risultato dovrebbe essere:
DESKTOP: stile di _Tabella_
MOBILE: stile di _Tabella ottimizzata per smartphone_

Il fatto che siano presenti due tabelle nella vista dekstop non aiuta: è possibile mantenerne una che varia in base alla risoluzione?

Nella vista ottimizzata è sparita la linea scura più spessa sopra ad ogni riga
<img width="363" alt="image" src="https://user-images.githubusercontent.com/91465481/188124949-bf1da992-f965-453d-902e-22638b217987.png">

**Comment by fmilla74** [comment]
La tabella a cui fare riferimento è "Tabella" e su "Tabella" versione mobile è presente la tua richiesta a meno della riga. Puoi confermarmelo?
Nel prossimo rilascio troverai solo "Tabella"

**Comment by steps88** [comment]
Confermo

**Comment by fmilla74** [comment]
rilasciato nella versione 2.3 a breve disponibile su github

**Comment by steps88** [comment]
Verificato 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/91465481/188646668-8c388ca8-fa44-40fb-9957-81754e0e77d4.png">
