### ISSUE TITLE
[v2] TUTTE LE PAGINE: dimensioni header, navbar, cerca, footer, link

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#49]
- [ ] Ridurre l'ingombro dell'**header** per far in modo che si veda più contenuto di pagina, ad esempio [vedi modello Comuni](https://italia.github.io/bootstrap-italia/docs/esempi/comuni/template-homepage/), se necessario ridurre anche la grandezza di logo+logotipo 
- [x] ridurre l'altezza anche dello **sticky header** 
- [x] la dimensione del **testo dentro l'input di ricerca** va ridotta (1rem o 16px)
- [x] la **linea di separazione** tra mini header ed header è del colore errato, vedi [qui](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/#versione-chiara-2)
- [x] allineare il kerning (distanza tra le lettere) delle CTA in maiuscoletto (es. link scopri di più, vai a...) al mockup, dove è più leggibile
- [x] **footer**: ridurre le dimensioni, c'è troppo margine sia top che bottom, così come la fascia dei crediti è alta più del necessario

`Header + linea di separazione` <img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/185578325-316c610f-3d38-4c3c-8fd3-7b62cb375210.png">

`Sticky header`
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/91465481/185580781-c9880ee9-9d48-45f1-a589-e83d384de39c.png">

`Kerning maiuscoletti: sviluppo vs prototipo`
<img width="176" alt="image" src="https://user-images.githubusercontent.com/91465481/185581086-e2e20838-4a16-48d3-936a-2c1f6c1c373e.png"> <img width="187" alt="image" src="https://user-images.githubusercontent.com/91465481/185581140-c77d5129-7fef-4773-929c-ebfaae8248a0.png">

`footer`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/185582007-e83e580e-e4d9-4ac0-92a1-cd13e8014472.png">

**Comment by fmilla74** [comment]
-  Ridurre l'ingombro dell'header per far in modo che si veda più contenuto di pagina, ad esempio [vedi modello Comuni](https://italia.github.io/bootstrap-italia/docs/esempi/comuni/template-homepage/), se necessario ridurre anche la grandezza di logo+logotipo


Si tratta di variazioni al mockup condiviso e realizzato sul prototipo HTML
A questo punto del progetto, vista la scadenza del 30 ottobre., queste modifiche potrebbero determinare un ritardo sulla pianificazione condivisa. Riteniamo che per metterle in campo sia necessario rivedere le proporzioni degli elementi ripartendo dal mockup. 

-  ridurre l'altezza anche dello sticky header

     Ok correggiamo 

-   la dimensione del testo dentro l'input di ricerca va ridotta (1rem o 16px)

     Ok, cambiamo la grandezza del testo (sul mockup è 18px)

-   la linea di separazione tra mini header ed header è del colore errato, vedi [qui](https://italia.github.io/bootstrap-italia/docs/menu-di-navigazione/header/#versione-chiara-2)
        Ok, cambiamo il colore presente nel mockup. Puoi indicarci quale colore inserire?

-  allineare il kerning (distanza tra le lettere) delle CTA in maiuscoletto (es. link scopri di più, vai a...) al mockup, dove è più leggibile

    Ok allineiamo al mockup

-  footer: ridurre le dimensioni, c'è troppo margine sia top che bottom, così come la fascia dei crediti è alta più del necessario
    Ok correggiamo lo spazio sopra e sotto il footer. La fascia dei crediti di quanto dovremmo ridurla? Adesso è come sul mockup

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato tutto tranne le dimensioni dell'header. Valutiamo il vostro suggerimento, e spostiamo a parte in un'altra issue.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/188122006-8744a5f2-67e7-42e3-bf4c-140620409e39.png">
<img width="297" alt="image" src="https://user-images.githubusercontent.com/91465481/188122314-d6208bf2-c9fd-4b2e-a74a-45adb9482880.png">
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/91465481/188122379-17e22db6-ae2b-402a-97dc-f13674d61ed9.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91465481/188122062-3f3ab127-0a9b-407a-9e02-4f8a392d6362.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/188122174-2e19a786-7e22-44e2-a6d1-6293d70ff1af.png">
