### ISSUE TITLE
[v1] Homepage: Hero banner - allineamento componente di navigazione

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#5]
Nel navigatore del carousel Hero banner, I pallini e le frecce sono leggermente decentrati tra loro. 
<img width="174" alt="Schermata 2022-07-27 alle 09 26 37" src="https://user-images.githubusercontent.com/108679095/181188039-a602c64e-46cc-47b8-a37d-b8da5cd53a8f.png">
.

**Comment by fcassandra** [comment]
Abbiamo centrato i pallini rispetto alle frecce. Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato 
<img width="296" alt="image" src="https://user-images.githubusercontent.com/91465481/185111486-419557bb-229f-4b61-9f1c-01940cd2534a.png">
