### ISSUE TITLE
[v2] HOMEPAGE: allineamento titoli-icona fasce orizzontali

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#50]
- [x] I titoli delle fasce orizzontali (Servizi anagrafici, Notizie, Numeri...) non sono allineati all'icona. Allineare al centro.
- [x] il copy dell'immagine ha la P di "per tutti" maiuscola, rendere minuscola
- [x] usare #5c6f82 per i testi che accompagnano dei titoli di fascia (es. Le ultime novità sui servizi...)

`allineamento`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/185583031-c9968342-c7ee-4cbd-b118-1745a1164797.png">

`typo `
<img width="746" alt="image" src="https://user-images.githubusercontent.com/91465481/185583511-84ce7c0d-2221-4a2c-b015-1dcc522573ef.png">

`Colore testi `
<img width="491" alt="image" src="https://user-images.githubusercontent.com/91465481/185587586-6e5d840a-554f-4a74-bf6c-bb150a478fe9.png">

**Comment by fmilla74** [comment]
Per quanto riguarda il primo punto facciamo riferimento alle indicazioni della segnalazione #51 ? 

Come segnalato sul #52, il colore  #5c6f82  non è tra quelli previsti nel mockup https://xd.adobe.com/view/f9fd0853-8e58-4bcf-8eac-59e5a47481a5-acae/screen/747a8e62-27e0-4882-84e5-c4a487286e3e/ 

Vuoi aggiungerlo?

**Comment by steps88** [comment]
punto 1) sì, tranne che per la sezione Servizi anagrafici che non avendo un sottotitolo va centrata sull'icona in maniera diversa

punto 3) colore: vedi la #52, aggiungere il colore

**Comment by fmilla74** [comment]
Verifico se una volta completati gli altri bug fixing e  richieste riusciamo ad aggiungerlo.
Potresti intanto darci indicazioni puntuali su dove utilizzarlo nell'ambito del sito? Non mi è chiaro . 
Grazie

**Comment by steps88** [comment]
nei testi che accompagnano i titoli delle fasce orizzontali (Notizie, Numeri...tranne per Servizi anagrafici che non ne ha):
per NOTIZIE è:

> Le ultime novità sui servizi e sulle funzionalità dell’Anagrafe Nazionale.

per NUMERI è:

> I dati principali sui servizi anagrafici, accessibili e costantemente aggiornati.

per AREA TECNICA è:
> Area dedicata agli operatori istituzionali e ai fornitori coinvolti nell’erogazione dei servizi anagrafici.



Di conseguenza anche i sottotitoli ai titoli delle **pagine interne**. Per esempio nella pagina Certificati è: 
> "Il servizio che rende disponibili online 14 tipologie di certificati anagrafici, in forma singola o contestuale."

**Comment by fmilla74** [comment]
corretto il refuso

**Comment by fmilla74** [comment]
rilasciato nella versione 2.2 "usare #5c6f82 per i testi che accompagnano dei titoli di fascia (es. Le ultime novità sui servizi...)"

**Comment by steps88** [comment]
Verificato refuso e colore.
L'allineamento del testo alle icone cercherei di sistemarlo per Servizi anagrafici dove è lampante.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/91465481/188118684-7fb41c76-728a-4496-954d-cf509f29bc77.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/91465481/188118751-c7f8d8b6-45f8-4423-b108-f8003e55652b.png">
<img width="655" alt="image" src="https://user-images.githubusercontent.com/91465481/188118820-2cfda54b-28d8-4deb-8516-480172d7780a.png">

**Comment by fmilla74** [comment]
Ciao Stefania, non ho chiaro questo punto. Mi potresti fornire un maggior dettaglio? grazie

**Comment by steps88** [comment]
I titoletti in homepage Servizi anagrafici, Notizie, Numeri, Area tecnica sono allineati al top dell'icona alla loro sinistra, che di per sè funziona per tutti i titoletti tranne il primo Servizi Anagrafici in quanto a differenza degli altri non ha un sottotitolo.

La domanda è: si può allineare Servizi anagrafici al centro dell'icona invece che al top?
<img width="491" alt="image" src="https://user-images.githubusercontent.com/91465481/188395729-ad684661-2ea2-49aa-b6c3-8ced1478d2af.png">

**Comment by fmilla74** [comment]
rilasciato nella versione 2.3 a breve disponibile su github

**Comment by steps88** [comment]
Verificato anche il primo punto ✨
<img width="489" alt="image" src="https://user-images.githubusercontent.com/91465481/188640584-aa848a6a-0375-40af-a3a1-9e822efacc66.png">
