### ISSUE TITLE
[v2] HOMEPAGE: layout titoli di sezione

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#51]
Al momento i titoli **Servizi anagrafici, Notizie, Numeri** ecc ingombrano una colonna di griglia molto stretta.
Per migliorare la gerarchia delle informazioni in pagina suggeriamo di allineare l'**ingombro**, la **posizione** e lo **stile** a ai titoli delle pagine interne, tipo Cos'è l'anagrafe nazionale (landing-page.html) o Certificati.

`Posizione ora`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/185596389-20f242fb-5058-4c81-b488-ba62eafe13c3.png">

`Posizione certificati`
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/91465481/185596530-bf5cd855-454b-432d-8ee1-d390d52c1e03.png">

`Posizione Cos'è l'anagrafe nazionale"`
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91465481/185627370-5bbb5091-2e33-4e09-9ca2-eb90c45870b5.png">

### Come vorremmo fosse:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/91465481/185597135-3a623ea0-1fdd-4c2a-8ae5-c40f75b284ff.png">

**Comment by fmilla74** [comment]
ok

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 🔥
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91465481/188117382-e6bc2078-67a5-46ab-b798-0c6d230d08eb.png">
