### ISSUE TITLE
[v2] PAGINE INTERNE: distanza dal breadcrumb

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#53]
Dimezzare la distanza del contenuto di pagina dal breadcrumb, sempre nell'ottica di visualizzare prima il contenuto.

Si applica alle pagine che hanno il menu laterale (Numeri, Notizie ecc) ma anche a quelle che non ce l'hanno (Faq, Crediti ecc)

<img width="960" alt="image" src="https://user-images.githubusercontent.com/91465481/185602461-58b0b990-5032-4cb9-a563-64db182d6850.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/91465481/185602515-b9ddf774-844c-48cf-b71a-169eeaf0012b.png">

**Comment by fmilla74** [comment]
Ok riduciamo la distanza del contenuto di pagina dal breadcrumb

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 🔥
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/91465481/188115430-10f688dd-c0f4-4e19-9811-524539a5ebb3.png">
