### ISSUE TITLE
[v2] NOTIZIE: distanza tra notizie

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#54]
Distanziare maggiormente una notizia dall'altra, e l'ultima dalla paginazione

<img width="945" alt="image" src="https://user-images.githubusercontent.com/91465481/185603756-53f870c5-b3cf-4c94-9275-d34274f567ff.png">

**Comment by fmilla74** [comment]
ok aumentiamo la distanza

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/91465481/188115164-b836bee7-9677-4838-9e05-b9a2019e4ce7.png">
