### ISSUE TITLE
[v2] NOTIZIE / CERCA: paginazione

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#55]
Come si comporta il componente quando ci sono più di 3 pagine? 
Preferibilmente vorremmo si comportasse come la [versione More presente in BSItalia](https://bootstrap-italia-next-git-fe-3cf9f6-dip-trasformazione-digitale.vercel.app/docs/componenti/paginazione/#more)

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/91465481/185604450-ae847729-fa9f-4051-83be-af6632b06795.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/91465481/185604406-92f82b1d-1768-4395-84dd-ef6242179302.png">

**Comment by fmilla74** [comment]
La paginazione è gestita come da prototipo XD
Pesavamo di mostrare 6 pagine e non 3 come da prototipo
la freccia singola scorre di una pagina 

![image](https://user-images.githubusercontent.com/84016913/188648240-7e52e7fe-19c8-4b89-83ec-a28039e08014.png)

**Comment by steps88** [comment]
se mostriamo 6 pagine da mobile andranno su 2 righe però, e sarebbe meglio non succedesse

**Comment by fmilla74** [comment]
Quante vuoi che ne mostriamo?

**Comment by steps88** [comment]
Nel mobile anche va bene la corrente, nel desktop può andare anche 3 o 6

**Comment by fmilla74** [comment]
ok, lo potrai vedere su wordpress

**Comment by steps88** [comment]
Potete verificare questo aspetto?

Se cerco "a" mi restituisce 71 risultati distribuiti su 8 pagine.. da **desktop** vedo tutte le prime 6 pagine (anche se penso si fermi lì il numero)
da **mobile** ne vedo solo 1 e non ho indicazioni che ce ne siano altre

Dicevamo di vederne almeno 3 da mobile 

L'ideale sarebbe inserire l'ellipsis (tipo "<< < 1  2 ... 8 > >>", come abbiamo fatto su Repubblica digitale per le iniziative)
anche su desktop mostrandone un numero non più alto di 6 + l'ellipsis + ultima pagina

> << < 1  2  3  4  5  6 ... 8 > >>

<img width="375" alt="image" src="https://user-images.githubusercontent.com/91465481/198700321-603ea47a-882e-437e-bb42-14ed541b4a29.png">
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/91465481/198700984-ce04bc3d-e79a-4f4d-b464-c3ff0febdf0a.png">

**Comment by fmilla74** [comment]
Correggiamo il numero di pagine mostrate da mobile. dovevano essere 3. La paginazione adesso è come da prototipo XD. Le ricerche con più lettere non dovrebbero restituire un numero elevato di pagine vista la bassa quantità di contenuti previsti sul sito. L'introduzione dell'ellipsis è una modifica che potremo sicuramente valutare al termine delle attività per la realizzazione dell'attuale versione del sito.

**Comment by fmilla74** [comment]
corretta la paginazione da mobile come da prototipo XD

**Comment by steps88** [comment]
Verificato 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/91465481/200288517-a7671383-b302-4d4d-bddd-7bc43f70bdfd.png">
