### ISSUE TITLE
[v2] DETTAGLIO NOTIZIA: torna a notizie

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#56]
allineare la formattazione del testo coerentemente con la formattazione degli altri maiuscoletti del sito 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/91465481/185605201-d1b3ef94-a04e-450a-9f75-a0f908866e5c.png">  <img width="212" alt="image" src="https://user-images.githubusercontent.com/91465481/185606034-fbcc6053-81cd-435e-8a8b-a939f9a5556d.png">

**Comment by fmilla74** [comment]
Ok correggiamo

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato
<img width="850" alt="image" src="https://user-images.githubusercontent.com/91465481/188112981-18ca64ee-8d89-4018-a0ba-e14e43255b7c.png">
