### ISSUE TITLE
[v2] PAGINE INTERNE: layout body text

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#57]
Per aumentare e facilitare la leggibilità del testo sarebbe preferibile stringere la colonna che lo contiene, compatibilmente con la griglia. Da non applicare a contenuti come tabelle o card.

Un esempio di come ridurre l'ingombro nello screenshot
<img width="1437" alt="Screenshot 2022-08-19 at 13 12 21" src="https://user-images.githubusercontent.com/91465481/185606735-d4cac953-f249-4f97-98e7-6f6188c7bfd4.png">

**Comment by fmilla74** [comment]
ok, riusciamo ad inserire questa variazione sui template

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 💣🔥
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/91465481/188112785-e755e0fa-cc62-40e4-a2d8-a80df8b5381c.png">
