### ISSUE TITLE
[v2] PAGINE INTERNE: ingombro vuoi saperne di più, ti è stata utile

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#58]
Entrambe le fasce "Vuoi saperne di più" e "Questa pagina ti è stata utile?" hanno un'altezza non giustificata dal contenuto, e appesantiscono visivamente la pagina. 

- [x] Diminuire l'altezza di ciascuna fascia a **3 rem** per lato
- [x] Diminuire la dimensione della font "Questa pagina ti è stata utile?" a 1.5rem e semibold, per rispettare la gerarchia delle informazioni
- [x] allineare vuoi saperne di più + icona come da screenshot 2

Screenshot esemplificativo del `prima` 
<img width="1440" alt="Screenshot 2022-08-19 at 13 14 53" src="https://user-images.githubusercontent.com/91465481/185608422-a23a2d1a-14e7-4f25-96fd-945510f91be5.png">

e di come dovrebbe essere 
<img width="1439" alt="Screenshot 2022-08-19 at 13 27 29" src="https://user-images.githubusercontent.com/91465481/185609013-cc78561b-88ba-485e-a87e-df7c2a1cd950.png">

**Comment by fmilla74** [comment]
Ok, lo correggiamo

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 💣🔥
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/91465481/188112404-d029d815-cd0c-4e74-8582-f3ca2ba2a25c.png">
