### ISSUE TITLE
[v2] CREDITI: layout

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#59]
Il layout non è coerente con le altre pagine interne, allineare a Certificati o Domande frequenti
<img width="1438" alt="Screenshot 2022-08-19 at 13 34 09" src="https://user-images.githubusercontent.com/91465481/185625794-1f25637f-0119-4b1e-a4e2-92b83d5bc09c.png">

**Comment by fmilla74** [comment]
Abbiamo rivisto il layout, così va bene?

![image](https://user-images.githubusercontent.com/84016913/186390900-99d87163-b2e6-4dc2-8391-744627ea0c47.png)

**Comment by steps88** [comment]
Anche il body text dovrà seguire la stessa larghezza di colonna della pagina Certificati o Domande frequenti. Verificheremo nel dettaglio una volta in sviluppo.

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/91465481/188111979-e1700997-10d2-4419-8cc1-da949118aefa.png">
