### ISSUE TITLE
[v1] Homepage: footer - logo

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#6]
Nel footer mobile il logo "anagrafe nazionale" perde il claim sottostante. Non ricordo se abbiamo richiesto noi questa modifica oppure è un disallineamento rispetto al desktop
<img width="396" alt="Schermata 2022-07-27 alle 09 36 39" src="https://user-images.githubusercontent.com/108679095/181189871-32b2fbf1-822f-4079-8f2c-4b6975dcdb85.png">
.

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
@FraCrea era stata una mia indicazione di non riportare il claim nel footer, per tenere più stringato il footer stesso.

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by fmilla74** [comment]
@Stefania: questo punto posso ritenerlo risolto? Devo fare un nuovo rilascio e vorrei includere eventuale altri fix se serve. Grazie

**Comment by steps88** [comment]
@fmilla74 abbiamo fatto un punto interno e per noi è addirittura meglio togliere il logo dal footer, risparmiando spazio. Lo abbiamo Comunque presente nello sticky header.. quanto impatta?

**Comment by fmilla74** [comment]
@steps88: vorreste togliere anche il logotipo? 

Non mi è chiaro il motivo visto che dopo il logo nel footer non mi sembra ci siano informazioni strategiche, di fatto è una ripetizione dei link in testata con l'aggiunta della privacy e dichiarazione di accessibilità

**Comment by steps88** [comment]
Dal footer, togliere logo e logotipo dal footer

**Comment by fmilla74** [comment]
Così?
![image](https://user-images.githubusercontent.com/84016913/188470670-ae04f2a2-7f42-4821-8aea-a75c20a4fbb8.png)

**Comment by steps88** [comment]
esatto

**Comment by fmilla74** [comment]
cerco di inserirlo nel prossimo rilascio che dovrebbe chiudere l'attività sul prototipo (la chiusura è prevista per domani)

**Comment by fmilla74** [comment]
rilasciato questa CR nella versione 2.3

**Comment by steps88** [comment]
Verificato su tutti i template 
<img width="963" alt="image" src="https://user-images.githubusercontent.com/91465481/188645905-039967b6-7deb-4aaf-b9ff-cf170af204cb.png">

**Comment by steps88** [comment]
Da mobile il primo testo risulta un po' troppo vicino al margine, lascerei il doppio dello spazio
