### ISSUE TITLE
[v2] COS'È L'ANAGRAFE: dimensione font Accedi, CNS

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#60]
Allineare la dimensione del titolo "Accedi in tutta sicurezza" coerentemente con i titoli suoi simili (es. Conosci l'Anagrafe, Notizie, Numeri ecc in homepage) > 1.25 rem e non 1.5

Allineare la dimensione di CNS a quella di CIE e SPID, e allineare il testo dentro la card coerentemente alle altre card.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91465481/185628331-026e5690-fb8e-4bb7-be9d-6d4f5459a12b.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91465481/185629145-e91fadd9-3bcc-498b-a6cc-960a0fb7d32c.png">
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/91465481/185629207-f3e35388-0d45-4b17-a1aa-c280008dad41.png">

**Comment by fmilla74** [comment]
Ok lo correggiamo

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato dimensioni e allineamenti
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/91465481/188111755-211a6905-37d2-4a06-a424-60f2b0907798.png">
