### ISSUE TITLE
[v2] TUTTE LE PAGINE: grassetto in mezzo al testo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#61]
Se non sono titoli, ovvero se sono sottotitoli o sono nel mezzo di body text, i grassetti è meglio averli in **semibold**  piuttostoc che bold, per equilibrio visivo. Un po' di esempi qui sotto, nelle card.

<img width="459" alt="image" src="https://user-images.githubusercontent.com/91465481/185630319-169c5e3c-e56a-4718-a2aa-9214ac7f2513.png"><img width="448" alt="image" src="https://user-images.githubusercontent.com/91465481/185630341-f765ed9a-b66b-4f51-b3be-b2ca63d02196.png"><img width="438" alt="image" src="https://user-images.githubusercontent.com/91465481/185630376-668d9daf-3d94-4279-be3e-8d9fb8ff1523.png">
<img width="747" alt="image" src="https://user-images.githubusercontent.com/91465481/185630477-9c591266-d691-4399-9fcc-f5692b265e1c.png">

**Comment by fmilla74** [comment]
Ok, adeguiamo il prototipo in tal senso.
 
Queste parti del sito saranno gestite redazionalmente e,per questo penso sia utile evidenziare nel documento dei contenuti  questa nuova regola così da avere indicazioni chiare per la redazione su quando adottare iI semibold.

**Comment by steps88** [comment]
Non va impostato nel css il semibold invece del bold?

**Comment by fmilla74** [comment]
Si, ma non basta. Va creata una classe per il semibold e poi il redattore l'applicherà solo alle parti di testo ove previsto il semibold utilizzando il tag <span>.

**Comment by steps88** [comment]
Ok, chiedo a @gabripoggioli dove sia meglio riportare questa regola

**Comment by gabripoggioli** [comment]
@steps88 Direi nel file da cui il redattore prenderà i contenuti definitivi da inserire nel CMS. Siamo ancora in attesa dal Ministero dell'Interno del file con i contenuti approvati e, quindi definitivi. Comincio ad appuntare la questione all'interno del file inviato da noi per la loro approvazione, avrò cura di riportarla su quello definitivo quando sarà il momento. Grazie!

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato
<img width="323" alt="image" src="https://user-images.githubusercontent.com/91465481/188111014-7d898b70-bfc0-4d4c-a7f3-a3e25cd37f79.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/91465481/188111056-5ffb37ae-fdf0-4f2a-8a4c-a1107e1effb8.png">
<img width="430" alt="image" src="https://user-images.githubusercontent.com/91465481/188111157-bed1f4a8-7d6b-4fb5-b6ba-a0b08f1b1307.png">
<img width="623" alt="image" src="https://user-images.githubusercontent.com/91465481/188111184-39ba13d9-59ac-4893-8fba-02d05f323e75.png">
