### ISSUE TITLE
[v2] HOMEPAGE: link "vai a..." dimensione font

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#62]
Il peso della font  "Vai a tutte le notizie" o "Vai ai numeri" o "Vai all'era tecnica"  sotto ai titoletti delle fasce orizzontali è diverso dalle altre CTA, dovrebbe essere bold

<img width="215" alt="image" src="https://user-images.githubusercontent.com/91465481/185641323-b09f5db8-1151-44eb-9219-1d49568cd5cd.png"><img width="163" alt="image" src="https://user-images.githubusercontent.com/91465481/185641283-d54da025-f634-46cf-b053-6ec09582cb86.png"> | vs | <img width="127" alt="image" src="https://user-images.githubusercontent.com/91465481/185641381-bd936161-bc71-4dd1-aa1e-188155edb71e.png">

**Comment by fmilla74** [comment]
Ok lo sistemiamo

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/91465481/188110060-7a2faea1-0c9d-4099-8ec7-378b2a2c88a7.png">
<img width="153" alt="image" src="https://user-images.githubusercontent.com/91465481/188110087-5dcab2b3-f3b1-4556-a698-d583f2f2de53.png">
<img width="247" alt="image" src="https://user-images.githubusercontent.com/91465481/188110115-857a1517-c743-450f-bf66-f37138ef9d9a.png">

**Comment by steps88** [comment]
"Conosci l'anagrafe" in homepage ha kerning (spazio tra lettere) diverso

**Comment by fmilla74** [comment]
rilasciato nella versione 2.3 a breve disponibile su github
