### ISSUE TITLE
[v2] TUTTE LE PAGINE: logotipo deve linkare alla home

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#63]
Cliccando sul logotipo 

> "Anagrafe nazionale
> Unica. Per tutti."

dovrebbe riportare alla home da qualsiasi pagina, ora non è un link

**Comment by fmilla74** [comment]
Possiamo sicuramente aggiungere il link al logotipo anche se è utilizzo comune usare il logo per tornare alla home page e non il testo che lo accompagna.  Comportamento che è stato anche evidenziato nei test di usabilità e ci ha fatto inserire il link esplicito per tornare alla home nella pagina di login
Inoltre, per garantire l’accessibilità  la scritta “Anagrafe nazionale Unica. Per tutti.” dovrà essere anticipata da “Home page” visibile solo ai lettori di schermo. 
Questo significa che l’utente che legge il sito con il lettore sentirà tutte le volte “Home page Anagrafe nazionale Unica. Per tutti.”,  un testo che a nostro avviso è un po’ troppo lungo e non in linea con il principio che i link devono essere sintetici.

Procediamo comunque con la modifica?

**Comment by steps88** [comment]
Potremmo considerare logo+logotipo come un unico elemento (come su Repubblica Digitale) così verrebbe letto una sola volta.. è possibile?

**Comment by fmilla74** [comment]
Per l'utente Il link sarà comunque unico anche se logo+logotipo sono due elementi separati. e viene letto una volta sola.
Mi sembra di capire che vuoi comunque che procediamo con questa modifica, giusto?

**Comment by steps88** [comment]
se viene letto una volta sola va bene no?

**Comment by fmilla74** [comment]
Come scritto prima, oltre al fatto del link, noi pensiamo che non sia utile avere il link anche sul testo che accompagna il logo. 
Se volete comunque prevederlo,  metto in coda la modifica. Avrei però bisogno di saperlo a breve per riuscire ad indirizzare la richiesta . Grazie

**Comment by steps88** [comment]
non son sicura di aver capito le due alternative, provo a riassumere (sto provando a leggere la pagina con VoiceOver del mac)

Se il logotipo "Anagrafe Nazionale Unica. Per tutti." **NON** è un link il lettore leggerà:
"logo anagrafe nazionale, link" e il logotipo Non viene letto

se invece il logotipo È un link diventerebbe:
"logo anagrafe nazionale, link" + " logo Anagrafe Nazionale Unica. Per tutti, link" 

giusto?

**Comment by fmilla74** [comment]
Se solo il logo è un link il lettore leggerà "Homepage Anagrafe nazionale" (Adesso l'alt è valorizzato male con "logo ...". dobbiamo cambiarlo ma stavo aspettando di capire se serve questa modifica)

Se logo+ logotipo sono link il lettore leggerà  "Home page Anagrafe Nazionale Unica. Per tutti,". Il link potrebbe essere più breve utilizzando l'arial-label ma è necessario una verifica con vari  lettori per essere sicuri del funzionamento.

**Comment by steps88** [comment]
Ok ora è chiaro. La metterei come modifica in coda, e farei in modo che il lettore nel caso di link legga solo "homepage Anagrafe Nazionale" o "link Anagrafe Nazionale". 
"Unica. Per tutti" è una tagline non necessaria alla fruizione del link, che quindi ometterei

**Comment by fmilla74** [comment]
rilasciato nella versione 2,2. 
Legge  "Homepage Anagrafe Nazionale"

**Comment by fmilla74** [comment]
@Stefania: questo punto posso ritenerlo risolto? Devo fare un nuovo rilascio e vorrei includer eventuale altre fix se serve. Grazie

**Comment by fmilla74** [comment]
rilasciato nella versione 2.3 a breve disponibile su github.

**Comment by steps88** [comment]
Verificato
