### ISSUE TITLE
[v2] HOMEPAGE: menu laterale frecce disallineate

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#66]
Le frecce degli menu secondari risultano disallineate (in alto) al testo, sia safari chrome e firefox
![Schermata 2022-08-19 alle 17 12 49](https://user-images.githubusercontent.com/91465481/185650589-c7bf8cc9-d134-47ac-a65c-f376b6025992.png)

**Comment by fmilla74** [comment]
OK lo sistemiamo

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/188105242-3fc5ccb9-7b1c-487a-884a-a25f0fd22f64.png">
