### ISSUE TITLE
[v2] COS'È L'ANAGRAFE: distanza elementi missione

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#67]
Distanziare maggiormente i 3 elementi nella fascia bianca

![Schermata 2022-08-19 alle 17 21 05](https://user-images.githubusercontent.com/91465481/185652447-fd78cd95-b7e4-4032-8fad-923f5a951356.png)

**Comment by fmilla74** [comment]
Ok, aumentiamo la distanza

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve
