### ISSUE TITLE
[v2] COS'È L'ANAGRAFE: accedi con SPID

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#68]
distanziare l'icona dal testo del link.

SPID è l'unica card che non rimanda all'accesso ma a come fare SPID, valorizzerei l'accesso piuttosto che il come farlo @gabripoggioli 

<img width="361" alt="image" src="https://user-images.githubusercontent.com/91465481/185653093-59e488d9-118b-4e82-9430-61545de6a26b.png">

**Comment by gabripoggioli** [comment]
Tutte e tre le card rimandano a link esterni, alle pagine dei siti ufficiali rispettivamente di [SPID](https://www.spid.gov.it/cos-e-spid/come-attivare-spid/), [CIE](https://www.cartaidentita.interno.gov.it/cittadini/entra-con-cie/) e [CNS](https://www.sistemats.it/) che spiegano come ottenere l'identità digitale e/o come utilizzarla (il modo in cui sono strutturate e trattate le informazioni varia da sito a sito). La CTA di accesso ai servizi anagrafici è presente subito sopra le 3 card.

<img width="1331" alt="Schermata 2022-08-26 alle 17 27 26" src="https://user-images.githubusercontent.com/101180195/186939835-23ef89ca-3749-4b97-9339-b42df7183532.png">

**Comment by gabripoggioli** [comment]
Riassegno a @fmilla74 in merito all'osservazione di @steps88 : 
"distanziare l'icona dal testo del link."

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/91465481/188105084-b46e4157-5f1c-4c9e-aac2-7ce1461b52c2.png">
