### ISSUE TITLE
[v2] DOMANDE FREQUENTI: indice dei contenuti + bug

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#69]
Quando "Indice dei contenuti" diventa sticky insieme all'header ci sono un paio di pixel di buco che lasciano intravedere il contenuto sottostante.

Il testo inoltre va in CAPS, come nella versione desktop altrimenti si confonde con gli accordion

**BUG**: Scrollando, al cambio sezione dovrebbe aggiornarsi anche la sezione dentro l'indice (su desktop viene evidenziata)

![Schermata 2022-08-19 alle 17 30 07](https://user-images.githubusercontent.com/91465481/185654390-7c70c134-9aa9-48c1-b546-9fe3718eaff5.png)

**Comment by fmilla74** [comment]
Ok, correggiamo

**Comment by fmilla74** [comment]
Riguardo al bug "Scrollando, al cambio sezione dovrebbe aggiornarsi anche la sezione dentro l'indice (su desktop viene evidenziata)"

Non l'abbiamo prevista  perché pensiamo possa essere poco utile visto che l'indice è chiuso e, una volta aperto. l'utente sceglie direttamente la sezione da visitare.  Abbiamo visto che anche su https://padigitale2026.gov.it/supporto/domande-frequenti/, da cui abbiamo preso spunto, non è implementato

**Comment by steps88** [comment]
capisco il punto e trovo sia un miglioramento ulteriore (anche al componente di padigitale) se l'indice si aggiorna allo scroll seguendo la sezione: per esempio se ho aperto un accordion dal contenuto particolarmente lungo sarei sempre consapevole della sezione in cui mi trovo (Vedi screenshot)

<img width="375" alt="image" src="https://user-images.githubusercontent.com/91465481/187221376-847f43c9-d014-47fd-b0a7-d3abb71dbefa.png">

**Comment by fmilla74** [comment]
rilasciato nella versione 2.1 

- Quando "Indice dei contenuti" diventa sticky insieme all'header ci sono un paio di pixel di buco che lasciano intravedere il contenuto sottostante.

- Il testo inoltre va in CAPS, come nella versione desktop altrimenti si confonde con gli accordion

**Comment by steps88** [comment]
Verificato
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/188104473-2069921f-9cfc-452c-acbd-a0e8ab888e74.png">
