### ISSUE TITLE
[v1] Homepage: Menu aperto mobile - allieneamento voci 2°livello

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#7]
le voci di secondo livello dovrebbero essere spostate più a destra rispetto a quelle di primo livello
<img width="245" alt="Schermata 2022-07-27 alle 09 57 12" src="https://user-images.githubusercontent.com/108679095/181194029-1700967c-9c9f-4de2-898a-22dadf3ff882.png">

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato
![Schermata 2022-08-17 alle 13 58 51](https://user-images.githubusercontent.com/91465481/185113103-2d7f0562-4bd0-4034-8ae5-19e1902ec405.png)
