### ISSUE TITLE
[V2] DOMANDE FREQUENTI: bug accordion visura

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#70]
il primo accordion dentro a "visura e autocertificazioni" non si chiude, ne desktop ne mobile

**Comment by fmilla74** [comment]
ok, correggiamo

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato
![ANPR accordion](https://user-images.githubusercontent.com/91465481/188102065-1902f4ba-c37f-44d7-af51-9bd561eb4b20.gif)
