### ISSUE TITLE
[v2] DOMANDE FREQUENTI: accordion già aperti, colore disattivo

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#71]
Atterrati sulla pagina, sarebbe preferibile che tutti gli accordion fossero chiusi, sia da desktop che mobile. 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/91465481/185656505-6fdf42f9-59ca-4113-b5ba-c9e414c1e3b5.png">

![Schermata 2022-08-19 alle 17 53 29](https://user-images.githubusercontent.com/91465481/185660094-29beba10-9496-4886-937b-9c539c807378.png)

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato
