### ISSUE TITLE
[v2] Mini footer: distanza link testuali

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#72]
da MOBILE, diminuire la distanza tra i link, e renderli come per nella parte del footer sopra

![Schermata 2022-08-19 alle 18 04 45](https://user-images.githubusercontent.com/91465481/185660451-7d71fb46-d864-41e7-bb56-5b996f2ac908.png)

**Comment by fmilla74** [comment]
Ok, correggiamo

**Comment by fmilla74** [comment]
correzione rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/188100429-ab346591-0da6-44ac-9171-eb2979df6686.png">
