### ISSUE TITLE
[v2] Risultati ricerca - Modifica titolo pagina e microcopy risultati trovati

### ISSUE THREAD

**Issue by gabripoggioli** [teamdigitale/anagrafenazionale.interno.it-site#73]
- [x]  Modificare il titolo di pagina "Risultati ricerca" in "Risultati della ricerca"

- [x]  Modificare il microcopy "Risultati ricerca: 26" in "Risultati trovati: 26"

<img width="970" alt="Schermata 2022-08-26 alle 19 26 33" src="https://user-images.githubusercontent.com/101180195/186959479-3680b84b-6845-4899-aef5-235f0f9650ef.png">

**Comment by fmilla74** [comment]
rilasciato nella versione 2,2

**Comment by steps88** [comment]
Verificato 
<img width="981" alt="image" src="https://user-images.githubusercontent.com/91465481/188126152-cf90bb28-4e09-41c9-b9e4-046e2d129262.png">
