### ISSUE TITLE
[V3] dimensioni header TBD

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#76]
Ridurre l'ingombro dell'header per far in modo che si veda più contenuto di pagina, ad esempio [vedi modello Comuni](https://italia.github.io/bootstrap-italia/docs/esempi/comuni/template-homepage/), se necessario ridurre anche la grandezza di logo+logotipo

Storico nella issue #49

**Comment by fmilla74** [comment]
@steps88: hai novità su questo punto?

**Comment by steps88** [comment]
@fmilla74 abbiamo deciso di lasciare la lavorazione ad un secondo momento. Chiudo la issue.
