### ISSUE TITLE
[v3] DOMANDE FREQUENTI: focus azzurro al clic/tap - Safari 

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#77]
Navigando il prototipo V3 da Safari, nella pagina Domande frequenti (ma anche le altre) al clic su alcune aree appaiono dei box azzurri, come di stato focus.

La cosa è particolarmente visibile da mobile proprio nella pagina **Domande frequenti** dove ci sono gli accordion navigabili.
Lo screenshot mobile si verifica anche con navigazione da smartphone, oltre che da simulatore.

Potete verificare il comportamento?

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/91465481/188191303-2544ebdb-c44a-4fdb-b803-b4eda817c11f.png">
<img width="713" alt="Screenshot 2022-09-02 at 10 58 00" src="https://user-images.githubusercontent.com/91465481/188191366-16b8d2fe-7edd-45d2-b5b4-eaa0fa808b80.png">

**Comment by fmilla74** [comment]
rilasciato nella versione 2.3 a breve disponibile su github

**Comment by steps88** [comment]
Verificato
