### ISSUE TITLE
[v3] Sticky header: logo quadrato disallineato

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#78]
Il logo quadrato ha perso l'allineamento al centro rispetto alla barra (nelle versioni precedenti era corretto)

<img width="343" alt="Screenshot 2022-09-02 at 11 57 40" src="https://user-images.githubusercontent.com/91465481/188191872-172a273e-133f-440f-a9f6-034a2e909e33.png">

A risoluzione tablet (tra 770 e 990px) invece il logo risulta molto vicino ai margini
<img width="812" alt="image" src="https://user-images.githubusercontent.com/91465481/188399033-16afc3fb-144f-4b40-b984-1b973d214cb4.png">

Dovrebbe mantenere dei margini ad ogni risoluzione

**Comment by fmilla74** [comment]
rilasciato nella versione 2.3 a breve disponibile su github

**Comment by steps88** [comment]
Verificato 
<img width="724" alt="image" src="https://user-images.githubusercontent.com/91465481/188640876-611f2cca-3a32-4f8e-b243-041b06e886d3.png">
