### ISSUE TITLE
[v1] HOMEPAGE: Menu mobile aperto - icona accedi

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#8]
Icona accedi diversa rispetto al prototipo
<img width="431" alt="Schermata 2022-07-27 alle 10 00 46" src="https://user-images.githubusercontent.com/108679095/181194303-120ae2bc-a308-4132-98ea-a8104bb35b5f.png">
o

**Comment by fcassandra** [comment]
Modifica disponibile nella versione 1.1 che rilasceremo in giornata.

**Comment by steps88** [comment]
Verificato
![Schermata 2022-08-17 alle 13 58 51](https://user-images.githubusercontent.com/91465481/185113291-6cf1dfe4-8b17-464c-87ea-985650b4af39.png)
