### ISSUE TITLE
[cx] NUMERI: distribuzione dell'utilizzo dei servizi - interazione mappa

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#81]
Come detto via mail il 15/9 la nostra proposta è di avere due tab - residenti e AIRE - con le rispettive scale di grandezza e colori da palette.

In generale bisognerebbe aggiungere 
- [x] una legenda delle grandezze (valore min e max)
- ~pulsanti di interazione con la mappa: zoom in, zoom out, ricentra~ non previsto dalla libreria

<img width="748" alt="image" src="https://user-images.githubusercontent.com/91465481/190363457-eb8b18ad-ea7c-48fd-b1cd-fc9d10606382.png">

Esempio di legenda con min/max
<img width="162" alt="image" src="https://user-images.githubusercontent.com/91465481/190364767-8e3f1213-ef50-40de-ad91-3c64b64be290.png">

**Comment by anbatistini** [comment]
Stiamo facendo delle prove sulla mappa potrebbe andare bene cosi (ovviamente nella legenda verranno inseriti i valori):
![aire](https://user-images.githubusercontent.com/51232022/190983966-95d4f125-1fd9-4978-8aa3-43d6a8f7d3aa.PNG)
![residenti](https://user-images.githubusercontent.com/51232022/190983985-e558da76-d7ed-4a5f-a764-baab7aba4806.PNG)
Per quanto riguarda i pulsanti di interazione, la libreria non li prevede, magari possiamo inserire un'informativa che spiega la possibilità di navigare la cartina

**Comment by steps88** [comment]
Molto bene! 
Sì corretto, come da mail di Claudia vorremmo inserire una spiegazione dell'utilizzo della mappa appena sotto al filtro.

**Comment by steps88** [comment]
Altri commenti di contenuto:
- aggiornare i colori da utilizzare secondo la palette condivisa, sia nella mappa che nella legenda
- utilizzare il colore in opacità o multiply per far vedere anche quelli che si sovrappongono
- aggiungere il separatore delle migliaia ai numeri in legenda

Attenzione che i nomi degli stati è in inglese, adeguare in ITALIANO. 


![Image](https://user-images.githubusercontent.com/91465481/192115792-e4d2fc57-1662-4854-b74f-54a1e3894776.png)

**Comment by steps88** [comment]
Per il testo di spiegazione dell'utilizzo della mappa appena sotto al filtro:
"Clicca e trascina per spostarti sulla mappa, o scrolla per fare zoom"

**Comment by rfamiglini** [comment]
@steps88 Smarcato. Come condiviso oggi, vi facciamo sapere se è possibile levare il nome degli stati in inglese e se è possibile cambiare il colore giallo

**Comment by steps88** [comment]
OK, tutto verificato, attendiamo aggiornamenti per il nome degli stati in inglese e il colore giallo in hover. 
Dicevamo anche di **dare un grado di zoom maggiore alla mappa nel tab RESIDENTI**



![Image](https://user-images.githubusercontent.com/91465481/194608887-5c6974e6-2e64-426f-a57f-4f0fad3af9f6.png)
![Image](https://user-images.githubusercontent.com/91465481/194608980-7250c614-ed75-4765-9a65-e0cbc43c5a9a.png)

**Comment by rfamiglini** [comment]
ciao @steps88 ,
siamo riusciti a cambiare il nome degli stati dall'inglese all'italiano, purtroppo il colore giallo in hover non è modificabile.
E' stato inoltre dato un grado di zoom maggiore alla mappa nel tab RESIDENTI

**Comment by steps88** [comment]
mmh capisco, e disattivare proprio il colore si può? benissimo per l'etichetta in italiano

**Comment by rfamiglini** [comment]
Purtroppo la libreria dietro la cartina è molto limitata per fare delle modifiche. 
Non siamo riusciti ne a cambiare colore ne a levarlo del tutto

**Comment by rfamiglini** [comment]
Sì è possibile tuttavia, come puoi vedere dall'immagine allegata, le palline risultano molto più grandi in corrispondenza dell'Europa, il che renderebbe la cartina sproporzionata.

![mappaAIRE](https://user-images.githubusercontent.com/88545256/199710400-3bb854f6-a859-49b2-a73c-4677e729ab41.PNG)

Come procediamo?

**Comment by steps88** [comment]
Si può riproporzionare la grandezza del min e max in modo da avere un min leggermente più piccolo. In realtà considerato che si può zoommare non mi spaventa la sovrapposizione dei cerchi sull'Europa..

**Comment by steps88** [comment]
Inserito zoom di default a livello mondiale per AIRE 
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/91465481/201683271-46743181-5ab4-4b77-a3d6-eda8779b5879.png">
