### ISSUE TITLE
[cx] NUMERI: stile legenda, etichette assi

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#83]
- [x] Le legende che ora hanno l'elemento cerchio vuoto, vorremmo fosse con cerchio pieno. <img width="121" alt="image" src="https://user-images.githubusercontent.com/91465481/190369876-d1bf715a-d9e8-423d-b9a7-97870e08ef20.png">
- [x] ridurre lo spazio tra il cerchio e la parola

- [x] Le **etichette** sugli assi nei vari filtri temporale sarebbe meglio fossero: 
    - ultimi 3 mesi > settimanale: n° giorno inizio settimana  es: `8 set`
    - ultimo anno > mensile: mese di 3 lettere + anno abbreviato in 2 cifre, possibilmente solo al cambio anno (dic - gen)     es: `dic 21`  `gen22`
    - dall'avvio > annuale:  4 cifre   es: `2021`

<img width="347" alt="image" src="https://user-images.githubusercontent.com/91465481/190372282-2f49c3fb-ad15-40fb-94a9-1f23a1ef3d3f.png">

**Comment by steps88** [comment]
`Mail 20/9 `
è  A giugno è stata condivisa l’aggregazione per mese poiché per i servizi di rettifica e cambio residenza si può avere una lavorazione di 90 gg e quindi avere il dettaglio della settimana non avrebbe avuto senso. L’unica soluzione a cui avevamo pensato era quella di considerare due tipi di intervallo, ma per omogeneità della pagina e di tutti i servizi avevi optato per un unico intervallo per mese e per tutti i servizi.

L’aggregazione settimanale è una modifica piuttosto onerosa per noi. E’ necessaria una rilavorazione della base dati, che ad oggi viene popolata su base mensile, una riscrittura delle query per avere il dettaglio settimanale e una modifica di tutti i grafici della pagina.

L’aggregazione per anno “dall’inizio del servizio” è invece meno onerosa. Tuttavia ci saranno dei casi, come per il cambio di residenza, in cui verrà sempre mostrato uno e un solo punto poiché il servizio è stato avviato nel 2022.

Le modifiche possono essere fatte ma non prima di un mese e mezzo.

**Comment by steps88** [comment]
Attenzione, lo spazio tra cerchio ed etichetta è troppo stretto, infatti quando cliccato l'elemento si sovrappone di poco alla scritta -- correggere


![Image](https://user-images.githubusercontent.com/91465481/192143457-90b9e473-df6f-47fc-800a-3690c1eef6ae.png)

**Comment by anbatistini** [comment]
abbiamo fatto alcune prove potrebbe andare bene così( a sinistra la modifica rispetto a destra):
![leggenda](https://user-images.githubusercontent.com/51232022/192471756-0351e5bb-b87f-4e47-8b3f-447f3a5944e0.JPG)
Senza selezione verrebbe così(ovviamente questo presuppone che ci sia dello spazio tra il pallino e la scritta):
![leggenda-2](https://user-images.githubusercontent.com/51232022/192472007-1dd83265-f108-4a14-a7f3-023eb1141a50.JPG)

**Comment by steps88** [comment]
Stiamo parlando dello spazio tra pallino e etichetta corretto? Ora quando cliccato la linea orizzontale sfiora la parola, aggiungerei un altro paio di pixel per staccare. Se ci sarà maggiore spazio quando non cliccato, amen, non si può avere tutto :D

ps: attenzione ai colori del grafico di dx, il bordeau è usato per AIRE, nella issue ho segnato quali colori usare nella vista complessiva

**Comment by anbatistini** [comment]
ok perfetto grazie, si correggiamo il colore come quello richiesto per carta libera e con bollo

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Lascio aperta solo per verificare le etichette d'asse quando sarò rilasciata la versione aggiornata con anni aggregati

**Comment by steps88** [comment]
quando sarò rilasciata la versione aggiornata con anni aggregati?

**Comment by steps88** [comment]
Abbiamo concordato che l'aggregazione per anni verrà lavorata appena ci saranno più dati (almeno due anni completi)
