### ISSUE TITLE
[cx] NUMERI: linechart - pallini pieni con outline bianco

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#84]
Per ogni linechart dove presenti, è possibile invertire i pallini DA bianchi con contorno colorato A pieni colorati con contorno bianco? 

**Se non è possibile** sarebbe più chiaro che si vedessero solo all'hover sul grafico, come avviene per l'area chart dei certificati.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/91465481/190379314-52c66f04-5603-4893-b1aa-b3f248edf072.png">

**Comment by anbatistini** [comment]
sono inseriti su tutti i grafici i pallini coloranti pieni sia sul grafico che nella legenda, la modifica è consultabile alla url fornita

**Comment by steps88** [comment]
@anbatistini pieni colorati con contorno bianco non è possibile? 
se la risposta è no, meglio che appaiano solo all'hover

**Comment by rfamiglini** [comment]
@steps88 Smarcato. I pallini compaiono in tutti i grafici solo all'hover.

**Comment by steps88** [comment]
Verificato
