### ISSUE TITLE
[cx] NUMERI: distribuzione dell'utilizzo dei servizi - stile tooltip mappa

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#86]
Allineare lo stile del contenuto nel tooltip come previsto nel mockup:
- Usare il bold per la regione e il totale
- eliminare "Regione"
- eliminare "Attività"
- eliminare "numero"
- aggiungere il separatore delle migliaia

La riga dovrebbe leggere:

**Lombardia**
AUTOCERTIFICAZIONE: 132.781
...ecc

<img width="181" alt="image" src="https://user-images.githubusercontent.com/91465481/192116062-e686f503-a7e9-483a-a55b-34a4747d4a74.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/91465481/192115905-e29d75e1-05ec-4de2-99c1-ab1a0a39ddec.png">

**Comment by rfamiglini** [comment]
@steps88 Smarcato
