### ISSUE TITLE
[cx] NUMERI: VERSIONE MOBILE - fix

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#87]
PERSONE IN ANAGRAFE NAZIONALE
Correggere la sovrapposizione del grafico col testo; **-- FATTO** manca la legenda **--MANCA**
<img width="348" alt="image" src="https://user-images.githubusercontent.com/91465481/192143763-2e858abb-1a49-4750-858a-dec564237e5a.png">

**DISTRIBUZIONE DEI SERVIZI**
Verificare che la select usata sia quella nativa del browser, al momento esce dallo schermo **--FATTO**
<img width="403" alt="image" src="https://user-images.githubusercontent.com/91465481/192143872-73003924-09ea-464c-982c-83ab77e1e3e2.png">

Correggere la posizione del tooltip, in modo che non esca dallo schermo **--FATTO**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/91465481/192143976-4280fd0f-e9fa-4eae-beed-f2634d232aaf.png">

SERVIZI PIÙ UTILIZZATI / ACCESSI TOTALI / MODALITÀ DI ACCESSO
Correggere le spaziature tra card, andare a capo per ogni modalità, in modo da non avere tutto compresso e sovrapposto **--FATTO**
<img width="303" alt="image" src="https://user-images.githubusercontent.com/91465481/192144071-9858a36d-5eea-4714-898e-fbef48f4d22c.png">

CERTIFICATI
diminuire lo spazio tra filtro e titolo **--FATTO**
<img width="304" alt="image" src="https://user-images.githubusercontent.com/91465481/192144206-f773060b-a248-49b6-a3f6-1af35c406675.png">

I 5 CERTIFICATI PIU EMESSI
distanziare la legenda dal grafico **--FATTO**
<img width="290" alt="image" src="https://user-images.githubusercontent.com/91465481/192145324-e82145ad-b7cb-4ab1-a7b9-d5eb6ca3e044.png">

VISURA E AUTOCERTIFICAZIONI
Diminuire le spaziature tra tra titolo e filtro, e tra card dei grafici **--FATTO**
<img width="307" alt="image" src="https://user-images.githubusercontent.com/91465481/192145445-862d3263-be9e-4272-8628-ec6fd34cb53b.png">

RETTIFICA DATI
Diminuire la spaziature tra titolo e filtro, e tra card dei grafici **--FATTO**
<img width="303" alt="image" src="https://user-images.githubusercontent.com/91465481/192145689-03e4ccca-dd1d-4c47-ae7c-ee752c0f7a3a.png">

Richieste di rettifica per stato di lavorazione: allineare i margini sx e top del titolo come negli altri titoli **--FATTO**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/91465481/192145561-d9832c87-b04b-484d-b08f-ee77e3107829.png"> vs <img width="298" alt="image" src="https://user-images.githubusercontent.com/91465481/192145632-24de3066-974e-4592-a1d6-a56f628ab4fe.png">

CAMBIO DI RESIDENZA
Diminuire la spaziature tra titolo e filtro, e tra card dei grafici **--FATTO**
<img width="305" alt="image" src="https://user-images.githubusercontent.com/91465481/192145664-36e5fc4b-c96b-487c-9a75-1b58ffd6b58d.png">
<img width="307" alt="image" src="https://user-images.githubusercontent.com/91465481/192145733-2596fdea-748d-436b-8509-e96706e994db.png">

Fare in modo che i tab non vadano su due righe, ma a scroll orizzontale  **--NON NECESSARIO dopo cambio copy**
<img width="301" alt="image" src="https://user-images.githubusercontent.com/91465481/192145871-cbb10733-6bdc-44df-8cfb-f681707d916b.png">

TIPOLOGIE DI CAMBIO RESIDENZA / SPOSTAMENTI DI RESIDENZA
Allineare i margini sx e top del titolo come negli altri titoli **--FATTO**
<img width="303" alt="image" src="https://user-images.githubusercontent.com/91465481/192145957-a7fa7728-c607-453c-b6a9-6b5f2644180a.png">

Spostamenti: attenzione che le etichette a dx sono troncate ed escono dallo schermo
<img width="306" alt="image" src="https://user-images.githubusercontent.com/91465481/192146022-7f0e0fa7-d176-4d9f-91d5-3485c39592a7.png">

**Comment by rfamiglini** [comment]
@steps88 Smarcato

**Comment by steps88** [comment]
Rimane da smarcare:
- [ ] la distanza tra le card ancora non è omogenea: tra le card nella primissima fascia generale (**Persone in Anagrafe, la mappa, ecc) c'è più margine che tra le card all'interno delle singole fasce di servizio (es. Certificati). La distanza da adottare è quella usata nelle fasce dei singoli servizi.
- [ ] le etichette numeriche nelle barre di Richieste di rettifica più frequenti escono dalla card (es. Residenza: Denominazione toponimo) -- _vedi screen_
- [ ] Spostamenti di residenza: non è più responsive ma scrolla orizzontalmente -- _vedi screen_

![Image](https://user-images.githubusercontent.com/91465481/194624862-3dd6a67a-3a32-4543-9547-5281d6fdbdbe.png)


![Image](https://user-images.githubusercontent.com/91465481/194625415-7eea96c1-18f1-4d1d-9800-51b849de0f46.png)

**Comment by steps88** [comment]
- [ ] ridurre i margini laterali in coerenza con le altre pagine interne del sito 
- [ ] allineare l'icona **( i )** alla riga superiore della card e verificare le dimensioni (già segnalato #30 )
<img width="334" alt="image" src="https://user-images.githubusercontent.com/91465481/198059046-e647a82e-1996-414c-80d6-acfd26c46eb8.png"><img width="474" alt="image" src="https://user-images.githubusercontent.com/91465481/198062416-54b0cda3-98b6-4b7e-904a-9431c5e1d20e.png">


- [ ] **area dati incompleti** per "Ultimi 3 mesi" è spostata oltre l'asse x 
<img width="253" alt="image" src="https://user-images.githubusercontent.com/91465481/198069923-6971fa95-130f-454b-91de-870eb903c31a.png">

- [ ] ricontrollare i **tab** per non mandarli a capo, ma attivare lo scroll orizzontale con sfumatura verso destra o parola tronca perchè sia segnalato 
<img width="315" alt="image" src="https://user-images.githubusercontent.com/91465481/198070352-40fe9d1a-d327-42fb-9eff-d582b80741c2.png">

**Comment by rfamiglini** [comment]
@steps88 abbiamo preso come riferimento il card-body da design system, in particolare i css delle card nella home page del sito pubblico. Di fatti il padding della card è 2 rem sia in numeri che in homepage. Forse non abbiamo capito cosa s'intende per "ridurre i margini", ci sapresti dare un riferimento all'interno del sito?

**Comment by steps88** [comment]
Mi spiego meglio: il `container` della pagina sembra essere uguale alle altre sezioni (es. Certificati), MA la pagina Numeri ha un secondo `container` che aggiunge padding dx e sx, riducendo l'ingombro del testo
<img width="431" alt="image" src="https://user-images.githubusercontent.com/91465481/198691249-c9075d60-5e49-4b1b-911d-4b674e3e6784.png">

https://user-images.githubusercontent.com/91465481/198692390-2aa83e49-23ce-406b-89e6-bf3934e06e2b.mp4

**Comment by rfamiglini** [comment]
Le fix sono state tutte effettuate, stiamo lavorando ancora sulla responsività della barra grigia in versione mobile che sembra essere poco gestibile

**Comment by steps88** [comment]
Considero ancora aperte quelle NON smarcate con flag, allego evidenze:

- Manca la legenda
<img width="367" alt="image" src="https://user-images.githubusercontent.com/91465481/199790791-04d7444d-5229-46f3-ad7a-7ea5457d6247.png">

- l'icona (i) è allineata solo in alcune card 
<img width="369" alt="image" src="https://user-images.githubusercontent.com/91465481/199791147-c6eec030-9d21-44ad-a1a4-dd5e99b9bb57.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/91465481/199791185-f6fb34c0-6936-4161-9164-96acb093db44.png">

- lo scroll orizzontale dei tab si ferma a metà schermo, sembra che l'etichetta AIRE potrebbe starci senza attivare lo scroll.. si vede una scrollbar, scrolla l'intero grafico
![ANPR tab scroll bar](https://user-images.githubusercontent.com/91465481/199791301-bc4eeb68-af0b-4643-a7ef-49c773c27bb7.gif)

**Comment by rfamiglini** [comment]
E' stato deciso di levare la legenda nella prima card in modalità mobile poiché non è stato possibile mettere "Residenti" e "AIRE" uno sotto l'altro (in quanto questa fa parte del grafico stesso). Tenerli uno accanto all'altro non favoriva la leggibilità poiché si accavallavano

**Comment by steps88** [comment]
Ciambella portata sotto al testo 
Grafico spostamenti corretto, scroll orizzontale sistemato.
Allineamenti dell'icona ( i ) sistemati
Troncatura etichette nelle rettifiche sistemate
Scroll orizzontale dei tab con + di 2 opzioni sistemati

<img width="350" alt="image" src="https://user-images.githubusercontent.com/91465481/201689338-e8685c86-5f15-4ee2-aa29-181ff91e87ac.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/91465481/201684632-f8b64af7-df80-4eb3-9baf-8220eb0ef86b.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/91465481/201685050-223f25b3-c9ac-484f-8282-dac417611cf9.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/91465481/201685096-750cb545-3de6-4662-9f95-1c276578218d.png">
