### ISSUE TITLE
[v1] Homepage: slim header

### ISSUE THREAD

**Issue by FraCrea** [teamdigitale/anagrafenazionale.interno.it-site#9]
Verificare la dimensione dalla cta "accedi" rispetto al prototipo; manca una linea grigia che divide lo slim header dall'heade
<img width="499" alt="Schermata 2022-07-27 alle 10 02 30" src="https://user-images.githubusercontent.com/108679095/181194987-f13f9bca-3947-4b68-af09-f1aec311b22b.png">
r

**Comment by fcassandra** [comment]
Nel mockup non è prevista coerentemente con il vostro design system

**Comment by steps88** [comment]
Nel [mockup](https://xd.adobe.com/view/f9fd0853-8e58-4bcf-8eac-59e5a47481a5-acae/screen/8bfd3f26-aeb2-4d0b-8924-5a92677e90b8/) è presente
<img width="692" alt="image" src="https://user-images.githubusercontent.com/91465481/185114833-5822645a-dd1c-4889-b5f4-0c6b9ef78a23.png">

così come nel nostro design system [vedi qui](https://bootstrap-italia-next-git-fe-3cf9f6-dip-trasformazione-digitale.vercel.app/docs/menu-di-navigazione/header/#versione-chiara-2)

<img width="373" alt="image" src="https://user-images.githubusercontent.com/91465481/185114503-31cf2a99-1efa-4b95-9b3f-72c1a726c895.png">

**Comment by fmilla74** [comment]
Qual'è il colore della riga?

**Comment by fmilla74** [comment]
modifiche rilasciata nella versione 2.1 disponibile a breve

**Comment by steps88** [comment]
Verificato dimensione CTA, riga e colore 
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/91465481/188125733-8ace96a2-2b9c-4ecf-9bff-dede953cfb7a.png">
<img width="378" alt="image" src="https://user-images.githubusercontent.com/91465481/188125846-71445948-6ff0-40ea-9982-e901e600e603.png">
