### ISSUE TITLE
[cx] NUMERI: esplicitare legenda interattiva

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#90]
Sarebbe possibile sotto ad ogni legenda inserire in piccolino la dicitura "la legenda è interattiva: seleziona gli elementi per filtrare il grafico"

**Comment by rfamiglini** [comment]
@steps88 
Smarcato.
Come da condivisione diminuiamo la dimensione e usiamo il font del portale.

**Comment by steps88** [comment]
Per reference <img width="587" alt="image" src="https://user-images.githubusercontent.com/91465481/194633940-71bf58bb-54e5-4aa6-8698-daefea3fcaf5.png">

**Comment by steps88** [comment]
Ridurrei la font ulteriormente, alla pari della grandezza della font in legenda

**Comment by steps88** [comment]
Verificato desktop e mobile
<img width="755" alt="image" src="https://user-images.githubusercontent.com/91465481/199963373-b8df7fa6-5cbb-4db0-9bab-98986b4a8e71.png">
<img width="278" alt="image" src="https://user-images.githubusercontent.com/91465481/199963450-30dbe702-3e5f-43b7-a834-3f14d6fa50a5.png">
