### ISSUE TITLE
[WP] HOMEPAGE: dropdown lingua, footer, sticky header

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#95]
- [x] MINIHEADER: il dropdown del cambio lingua non funziona, al clic non succede nulla --da Firefox, sia desktop sia mobile
- [x] CAROUSEL: typo nella 3 img, manca la i alla CTA "scopri tutti i **servzi**"

<img width="831" alt="image" src="https://user-images.githubusercontent.com/91465481/196889386-b0d387c3-96f7-4b7a-8d59-892ed36bbe04.png">

FOOTER

- [x] BUG - Sotto al footer c'è del codice, su tutte le pagine --da Firefox, sia desktop sia mobile
- [x] L'area cliccabile delle voci va ben oltre la scritta della singola voce, ne risulta che in aree vuote si può cliccare ma non è chiaro cosa si sta cliccando

https://user-images.githubusercontent.com/91465481/196905866-a145a234-f693-4801-a5df-f028d4fab06e.mp4

- [x] PERCHÈ L'ANAGRAFE: la CTA "scopri cos'è l'anagrafe" ha dimensioni diverse dalle altre CTA presenti in pagina 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/91465481/196908491-0609fe58-d913-485c-be50-07500a34ff0b.png">

**DA MOBILE**:

- ~nello STICKY HEADER il logo ANPR risulta percettivamente spostato verso l'alto e non allineato alla riga bassa del menu~ È CENTRATO E COSTRUITO SBILANCIATO VERSO IL BASSO
<img width="430" alt="image" src="https://user-images.githubusercontent.com/91465481/196905660-a2f48d53-9fb1-4ea0-993e-2f1f5f145cb8.png">

- [x] Il titolo di fascia SERVIZI ANAGRAFICI non ha gli stessi margini laterali degli altri titoli di fascia (motivo per cui la freccia della CTA va a capo probabilmente) 
<img width="424" alt="image" src="https://user-images.githubusercontent.com/91465481/196905292-a243615a-e10e-4b97-8555-5b523bfd4804.png"><img width="375" alt="image" src="https://user-images.githubusercontent.com/91465481/196906713-46ab4f93-5ba6-4920-98e4-c2110dfdd7ca.png">

- [x] nel MINI FOOTER le voci non sono allineate a quelle del MAIN FOOTER 
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/196913025-c7966438-5f13-4d7c-b99e-a54956629a54.png">

**Comment by steps88** [comment]
Typo verificato <img width="297" alt="image" src="https://user-images.githubusercontent.com/91465481/197158694-0b21780c-0aeb-40eb-b8be-35c57a2017b2.png">

**Comment by fmilla74** [comment]
@steps88: Anche mettendo al titolo di fascia SERVIZI ANAGRAFICI gli stessi margini laterali degli altri titoli di fascia la CTA va a capo su mobile. Cambiamo la CTA in Scopri tutti i servizi come nello slider?

**Comment by steps88** [comment]
@fmilla74 andrei con "Vai ai servizi anagrafici", dovrebbe risolvere la questione a capo.

**Comment by fmilla74** [comment]
I link ad una determinata pagina dovrebbero avere lo stesso nome, questo per l'accessibilità. Aggiorno con "Vai ai servizi anagrafici" anche la CTA della terza slide dello slider

**Comment by steps88** [comment]
Va bene

**Comment by fmilla74** [comment]
Il titolo di fascia SERVIZI ANAGRAFICI non ha gli stessi margini laterali degli altri titoli di fascia (motivo per cui la freccia della CTA va a capo probabilmente) --> corretto

 BUG - Sotto al footer c'è del codice, su tutte le pagine --da Firefox, sia desktop sia mobile --> corretto

L'area cliccabile delle voci va ben oltre la scritta della singola voce, ne risulta che in aree vuote si può cliccare ma non è chiaro cosa si sta cliccando --> corretto

**Comment by steps88** [comment]
Manca solo l'allineamento delle voci nel minifooter
> nel MINI FOOTER le voci non sono allineate a quelle del MAIN FOOTER

Il resto verificato

![ANPR footer area link](https://user-images.githubusercontent.com/91465481/198698795-d2ad83bc-9655-4849-b3fb-85e570d89f4b.gif)
![ANPR margini servizi AN](https://user-images.githubusercontent.com/91465481/198698822-b2fd9774-08a5-41e4-84d2-0374bd39e593.gif)

**Comment by fmilla74** [comment]
mii footer allineato

**Comment by steps88** [comment]
È un piacere fare affari con te, @fmilla74 . Verificato!
<img width="377" alt="image" src="https://user-images.githubusercontent.com/91465481/199959092-6f833df1-de3b-4b29-bf18-df9f84a29a54.png">
