### ISSUE TITLE
[WP] MISSIONE/NOTIZIE: modulo feedback, colore link notizie

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#97]
- PAGINA MISSIONE: È saltato il modulo feedback
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/91465481/196917519-3c5d639b-8069-482f-82a9-e255f1523b55.png">

- PAGINA NOTIZIE: il colore dei link attivi va in #06c, manca l'hover che si scurisce (come nel Leggi i più/Scopri di più)
<img width="833" alt="image" src="https://user-images.githubusercontent.com/91465481/196918510-fd161947-8537-4194-9768-075adc8efc67.png">

**Comment by fmilla74** [comment]
La PAGINA NOTIZIE la correggiamo. Per il modulo feedback stai usando Safari?  abbiamo trovato un bug che  stiamo risolvendo

**Comment by steps88** [comment]
No Firefox, non lo vedo in nessuna pagina il modulo, nemmeno Chrome (o Edge)

**Comment by steps88** [comment]
Nel sito in produzione vedo il Modulo feedback ✅  sia Chrome che Firefox e ok il mobile. Unica cosa che mi è sfuggita finora è il colore della scritta nel captcha "Inserisci i caratteri che vedi o che senti", non mi sembra raggiunga il contrasto necessario per accessibilità. Meglio metterlo in bianco
<img width="848" alt="image" src="https://user-images.githubusercontent.com/91465481/197485940-ed219472-58ce-4b2d-9f7f-019cca601cf5.png">

**Comment by fmilla74** [comment]
"Inserisci i caratteri che vedi o che senti" ora è bianco, puoi verificarlo in produzione

**Comment by steps88** [comment]
Per il colore dei link Notizie, meglio creare una issue separata? 

Modulo feedback verificato 
<img width="376" alt="image" src="https://user-images.githubusercontent.com/91465481/198046192-a99824b8-0a01-4032-9532-8681a9bb65b6.png">

**Comment by fmilla74** [comment]
non serve, appena lo rilascio ti informo su questa issue

**Comment by fmilla74** [comment]
colore link notizie corretto

**Comment by steps88** [comment]
Verificato
![ANPR link hover notizie](https://user-images.githubusercontent.com/91465481/198695130-2d602fdb-079c-4bf9-8453-24351983c2f3.gif)

**Comment by steps88** [comment]
@fmilla74 si è perso il cambiamento all'hover del link
![ANPR bug link notizie hover](https://user-images.githubusercontent.com/91465481/207043261-4c78a4e3-276e-45a0-9f1e-809c6a5d0c1c.gif)

**Comment by fmilla74** [comment]
@steps88 @Clou-dia il problema è stato risolto

**Comment by steps88** [comment]
Verificato 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/91465481/207630207-6dd4ed36-4365-4e3d-a630-5457fb58330f.png">
<img width="303" alt="image" src="https://user-images.githubusercontent.com/91465481/207630247-4721461f-019c-403b-b664-0f3c58635b56.png">
