### ISSUE TITLE
[WP] SERVIZI ANAGRAFICI: icona Accedi in tutta sicurezza, spazio tra card mobile

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#98]
- saltata l'icona di fascia "Accedi in tutta sicurezza" -- Firefox e Chrome, sia desktop che mobile
<img width="880" alt="image" src="https://user-images.githubusercontent.com/91465481/196920242-5bdad640-9754-4c77-8d94-b4c4fc527faa.png">

**MOBILE**
- non c'è spazio tra le card di SPID, CIE, CNS 
 
<img width="335" alt="image" src="https://user-images.githubusercontent.com/91465481/196920876-9670db3d-0d47-4228-9e23-1f4c8b624334.png">

**Comment by fmilla74** [comment]
Adesso l'icona è ok. La spazio tra le card è da correggere

**Comment by fmilla74** [comment]
Spazio corretto

**Comment by steps88** [comment]
Corretto <img width="379" alt="image" src="https://user-images.githubusercontent.com/91465481/198695409-956648c7-d496-4e8d-b941-279882f7afdb.png">
