### ISSUE TITLE
[WP] CERTIFICATI: manca testo banner, link a fondo pagina, stile tabella

### ISSUE THREAD

**Issue by steps88** [teamdigitale/anagrafenazionale.interno.it-site#99]
- manca il testo del banner per effettuare l'accesso, sia desktop che mobile
<img width="402" alt="image" src="https://user-images.githubusercontent.com/91465481/196925380-53fde29d-00ca-493f-a422-5c6a091b77f5.png">
<img width="915" alt="image" src="https://user-images.githubusercontent.com/91465481/196925601-e1dfe0d0-930a-4efe-bb2d-be1f8ce7951e.png">

- a fondo pagina, è rimasto il link per tornare alle notizie > eliminare
- a fondo pagina, è rimasto il link al canale Youtube > eliminare
<img width="497" alt="image" src="https://user-images.githubusercontent.com/91465481/196925693-d0d48316-d7b2-4488-be13-bc6dc20fdddc.png">

- TABELLA: la formattazione che avevamo visto in html è diversa da questa wordpress, ci sono spazi tra le righe e manca la linea più spessa tra header e righe  -- sia desktop che mobile 
 _html_
<img width="953" alt="image" src="https://user-images.githubusercontent.com/91465481/196926342-fe81d938-83c7-4d7e-b25b-0636e9885f08.png">
_Wordpress_
<img width="887" alt="image" src="https://user-images.githubusercontent.com/91465481/196926469-8b3e8ab4-518d-4eee-a37c-ca9d104ee816.png">

- FYI: le pillole informative non fanno parte di questa pagina > eliminare

**Comment by fmilla74** [comment]
@steps88  A questo link puoi verificare solo la struttura del sito. I contenuti li stiamo caricando direttamente in produzione, tabella secondo quanto condiviso compresa

**Comment by fmilla74** [comment]
@steps nel documento dei contenuti non c'è il banner per accedere nella pagina dei certificati

**Comment by fmilla74** [comment]
puoi verificare la pagina sul sito di produzione

**Comment by steps88** [comment]
Pagina certificati OK. Per lo stile di tabella meglio aprire una issue separata apposita?

**Comment by steps88** [comment]
E per verificare la visualizzazione del banner (nel caso in futuro lo andremo ad inserire in una delle pagine) come possiamo verificarlo?

**Comment by fmilla74** [comment]
lo trovi nella pagina dei certificati

**Comment by steps88** [comment]
Tabelle di decodifica aggiornate, link rimossi 
<img width="764" alt="image" src="https://user-images.githubusercontent.com/91465481/200881723-64f04b48-345d-4fda-a8d8-ee0dc5c50678.png">
<img width="334" alt="image" src="https://user-images.githubusercontent.com/91465481/200881793-b797eb75-f68f-4284-b29b-ad39ed67a108.png">
